//! MIG-056 §D — Federated query builders.
//!
//! Pure-function helpers that compose SQL for federated `UNION ALL`
//! queries across the active universe (schema alias `main`) and any
//! attached cUniverses (aliases `cu0`, `cu1`, …). Consumed by §E
//! (lens), §F (status bar / libraryStats), and §G (global search).
//!
//! ## The predicate-pushdown contract (Architect §7.2)
//!
//! Per Agent 3's Citus lesson (Postgres FDW abandoned for sharding
//! because of fetch-then-filter perf cliffs): **WHERE clauses MUST
//! be pushed into each `UNION ALL` branch, not applied to the outer
//! query**. The builders here enforce this at compile time: callers
//! provide the per-branch WHERE clauses; the builder inlines them
//! into each branch.
//!
//! Anti-pattern (rejected — never produced by these builders):
//!
//! ```sql
//! SELECT * FROM (
//!     SELECT * FROM main.note_meta UNION ALL
//!     SELECT * FROM cu0.note_meta UNION ALL ...
//! ) WHERE created_at >= ?     -- WRONG: filters AFTER union; pulls all rows
//! ```
//!
//! Correct pattern (what these builders produce):
//!
//! ```sql
//! SELECT * FROM main.note_meta WHERE created_at >= ?
//! UNION ALL
//! SELECT * FROM cu0.note_meta WHERE created_at >= ?
//! UNION ALL ...
//! -- ORDER BY + LIMIT at outer level only
//! ```
//!
//! ## The Citus warning (Architect §4 / Agent 3)
//!
//! Architect §4 explicitly rejects Citus's mistake of trying to be a
//! generic query planner. These builders are intentionally **small +
//! explicit**. The supported shapes:
//!
//! - Per-branch projection (`select_cols`)
//! - Per-branch joins (`joins`) — schema-qualified
//! - Per-branch WHERE (`where_clauses`)
//! - Outer ORDER BY on a single column
//! - Outer LIMIT
//!
//! Anything more complex (subqueries, window functions, cross-branch
//! correlated subqueries, GROUP BY across the union) is **out of
//! scope for v1** — callers fall back to active-only queries or
//! split into multiple federated queries with app-side merging.

/// Build a per-schema SELECT clause: `SELECT <cols> FROM <schema>.<table>
/// [joins...] [WHERE clauses]`.
///
/// `schema` — SQL identifier (e.g., `"main"`, `"cu0"`). MUST be
/// alphanumeric (validated by `is_safe_schema_alias`).
/// `select_cols` — list of column expressions; each is interpolated
/// AS-IS (caller must ensure each is safe SQL).
/// `joins` — list of JOIN fragments (e.g., `"LEFT JOIN cu0.note_summaries
/// ON cu0.note_summaries.path = cu0.note_meta.path"`). Empty = no joins.
/// `where_clauses` — list of WHERE clause fragments (e.g.,
/// `"cu0.note_meta.created_at >= ?"`). Combined with `AND`. Empty =
/// no WHERE. Parameter binding is the caller's responsibility — these
/// fragments contain `?` placeholders.
///
/// # Panics
///
/// Panics if `schema` is not a valid SQL identifier (alphanumeric or
/// underscore). This is a programmer-error guard, not a runtime
/// concern — callers should always pass aliases generated by
/// `attach::schema_alias`.
pub fn per_schema_select(
    schema: &str,
    select_cols: &[&str],
    joins: &[&str],
    where_clauses: &[&str],
) -> String {
    if !is_safe_schema_alias(schema) {
        panic!(
            "per_schema_select: schema alias `{}` is not alphanumeric (caller programming error)",
            schema
        );
    }
    if select_cols.is_empty() {
        // Empty cols would generate invalid SQL — caller bug.
        panic!("per_schema_select: select_cols cannot be empty");
    }

    let mut sql = format!(
        "SELECT {} FROM {}.note_meta",
        select_cols.join(", "),
        schema
    );

    for join in joins {
        sql.push(' ');
        sql.push_str(join);
    }

    if !where_clauses.is_empty() {
        sql.push_str(" WHERE ");
        sql.push_str(&where_clauses.join(" AND "));
    }

    sql
}

/// Compose N per-schema SELECTs into a federated UNION ALL query
/// with optional outer ORDER BY + LIMIT.
///
/// `parts` — list of per-schema SELECT strings (typically from
/// `per_schema_select`). Empty list returns an empty string (caller
/// should detect this case before calling).
/// `outer_order` — `Some("note_meta.created_at DESC")` etc. or
/// `None` for no outer ORDER BY. The ORDER BY column must be present
/// in ALL per-schema SELECTs' projection.
/// `outer_limit` — `Some(50)` or `None`.
///
/// Per Architect §7.2 and Agent 1's findings: uses `UNION ALL`
/// (never `UNION` — the dedup overhead breaks plans).
///
/// # Returns
///
/// Empty string if `parts.is_empty()`. Otherwise a complete SQL
/// query suitable for `Connection::prepare`.
pub fn union_all_compose(
    parts: &[String],
    outer_order: Option<&str>,
    outer_limit: Option<usize>,
) -> String {
    if parts.is_empty() {
        return String::new();
    }

    let mut sql = parts.join(" UNION ALL ");

    if let Some(order) = outer_order {
        sql.push_str(" ORDER BY ");
        sql.push_str(order);
    }

    if let Some(limit) = outer_limit {
        sql.push_str(&format!(" LIMIT {}", limit));
    }

    sql
}

/// Validate a schema alias is alphanumeric (with optional underscore).
/// Used as a defensive check against SQL injection via the alias
/// position. In practice, aliases come from `attach::schema_alias(i)`
/// which generates `cu0..cu24` — all safe — but the validation locks
/// the contract.
pub(crate) fn is_safe_schema_alias(alias: &str) -> bool {
    if alias.is_empty() {
        return false;
    }
    alias.chars().all(|c| c.is_ascii_alphanumeric() || c == '_')
}

// ─── §D tests ───

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn per_schema_select_minimal_no_joins_no_where() {
        let sql = per_schema_select("main", &["path", "name"], &[], &[]);
        assert_eq!(sql, "SELECT path, name FROM main.note_meta");
    }

    #[test]
    fn per_schema_select_with_join_and_where() {
        let sql = per_schema_select(
            "cu0",
            &["cu0.note_meta.path", "cu0.note_summaries.headline"],
            &["LEFT JOIN cu0.note_summaries ON cu0.note_summaries.path = cu0.note_meta.path"],
            &["cu0.note_meta.created_at >= ?"],
        );
        assert!(sql.starts_with("SELECT cu0.note_meta.path, cu0.note_summaries.headline FROM cu0.note_meta"));
        assert!(sql.contains("LEFT JOIN cu0.note_summaries"));
        assert!(sql.ends_with("WHERE cu0.note_meta.created_at >= ?"));
    }

    #[test]
    fn per_schema_select_multiple_where_clauses_joined_with_and() {
        let sql = per_schema_select(
            "main",
            &["path"],
            &[],
            &["main.note_meta.created_at >= ?", "main.note_meta.library_name IN (?, ?)"],
        );
        assert!(sql.contains("main.note_meta.created_at >= ? AND main.note_meta.library_name IN (?, ?)"));
    }

    #[test]
    #[should_panic(expected = "alphanumeric")]
    fn per_schema_select_panics_on_unsafe_alias() {
        per_schema_select("main; DROP TABLE notes; --", &["path"], &[], &[]);
    }

    #[test]
    #[should_panic(expected = "select_cols cannot be empty")]
    fn per_schema_select_panics_on_empty_cols() {
        per_schema_select("main", &[], &[], &[]);
    }

    #[test]
    fn union_all_compose_empty_returns_empty_string() {
        let sql = union_all_compose(&[], None, None);
        assert_eq!(sql, "");
    }

    #[test]
    fn union_all_compose_single_part_no_union() {
        let sql = union_all_compose(
            &["SELECT path FROM main.note_meta".to_string()],
            None,
            None,
        );
        assert_eq!(sql, "SELECT path FROM main.note_meta");
    }

    #[test]
    fn union_all_compose_two_parts_uses_union_all_not_union() {
        let sql = union_all_compose(
            &[
                "SELECT path FROM main.note_meta".to_string(),
                "SELECT path FROM cu0.note_meta".to_string(),
            ],
            None,
            None,
        );
        // UNION ALL (not UNION) — dedup overhead avoidance per Agent 1
        assert!(sql.contains(" UNION ALL "));
        assert!(!sql.contains(" UNION ") || sql.contains(" UNION ALL "));
    }

    #[test]
    fn union_all_compose_with_outer_order_and_limit() {
        let sql = union_all_compose(
            &[
                "SELECT path, created_at FROM main.note_meta WHERE created_at >= ?".to_string(),
                "SELECT path, created_at FROM cu0.note_meta WHERE created_at >= ?".to_string(),
            ],
            Some("created_at DESC"),
            Some(50),
        );
        // ORDER BY + LIMIT applied AFTER UNION ALL
        assert!(sql.contains("UNION ALL"));
        assert!(sql.contains("ORDER BY created_at DESC"));
        assert!(sql.contains("LIMIT 50"));
        // Confirm WHERE is PER-BRANCH (not at outer level) — the
        // predicate-pushdown contract
        let order_pos = sql.find("ORDER BY").unwrap();
        let last_where = sql.rfind("WHERE").unwrap();
        assert!(
            last_where < order_pos,
            "all WHERE clauses must be BEFORE ORDER BY (per-branch, not outer)"
        );
    }

    #[test]
    fn is_safe_schema_alias_accepts_alphanumeric() {
        assert!(is_safe_schema_alias("main"));
        assert!(is_safe_schema_alias("cu0"));
        assert!(is_safe_schema_alias("cu24"));
        assert!(is_safe_schema_alias("a_b"));
    }

    #[test]
    fn is_safe_schema_alias_rejects_unsafe() {
        assert!(!is_safe_schema_alias(""));
        assert!(!is_safe_schema_alias("main;DROP"));
        assert!(!is_safe_schema_alias("main TABLE"));
        assert!(!is_safe_schema_alias("'injection'"));
        assert!(!is_safe_schema_alias("a-b"));
    }
}
