//! In-process telemetry counters for the Mind subsystem.
//!
//! Phase 0a (this commit) lands the `TelemetrySnapshot` type and a
//! default-zero `snapshot()` function so the `mind_telemetry_snapshot`
//! IPC command (Step C) has a real return type. Step E wires real atomics
//! into the orchestrator (Step D) so the snapshot reflects actual
//! counters incremented as turns flow through.
//!
//! Architect invariant 7 ("Local-First / no exfiltration"): the counters
//! are read-only via `mind_telemetry_snapshot` and never sent over the
//! network. No persistence in 0a (Phase 5 / MIG-053 decides whether the
//! cloud cost-meter persists per Concept Paper v1.1 §11.4).

use serde::{Deserialize, Serialize};

/// One read-out of the in-process counters. All fields default to zero;
/// real values plumb in through Step E.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct TelemetrySnapshot {
    /// Number of completed turns since the process started.
    pub turn_count: u64,
    /// Total prompt tokens passed to the provider across all turns.
    pub tokens_in: u64,
    /// Total tokens generated by the provider across all turns.
    pub tokens_out: u64,
    /// Number of tool-call events the dispatcher fielded.
    pub tool_calls_count: u64,
    /// Number of turns that hit the `max_tool_rounds_per_turn` budget
    /// abort (MA-4 — Concept Paper v1.1 §10.3).
    pub tool_call_rounds_exceeded_count: u64,
    /// Number of provider errors observed.
    pub errors_count: u64,
    /// p50 turn latency in milliseconds (0 until ≥1 turn completed).
    pub latency_ms_p50: u64,
    /// p99 turn latency in milliseconds (0 until ≥1 turn completed).
    pub latency_ms_p99: u64,
    /// Active provider identity (e.g. "local-stub", "anthropic-claude-stub").
    /// Empty string until the first turn runs.
    pub provider_id: String,
    /// Active model identity (e.g. "fanar-1-9b-q4km", "claude-sonnet-4-6").
    /// Empty string until the first turn runs.
    pub model_id: String,
}

/// Return a snapshot of the current counters.
///
/// Phase 0a returns `Default::default()` (all zeros). Step E swaps this
/// for a real read against atomic counters in the orchestrator.
pub fn snapshot() -> TelemetrySnapshot {
    TelemetrySnapshot::default()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn snapshot_starts_at_zero() {
        let s = snapshot();
        assert_eq!(s.turn_count, 0);
        assert_eq!(s.tokens_in, 0);
        assert_eq!(s.tokens_out, 0);
        assert_eq!(s.tool_calls_count, 0);
        assert_eq!(s.tool_call_rounds_exceeded_count, 0);
        assert_eq!(s.errors_count, 0);
        assert!(s.provider_id.is_empty());
        assert!(s.model_id.is_empty());
    }
}
