//! GBNF grammar generator — turns a tool-palette into a llama.cpp
//! GBNF (GGML BNF) grammar string the sampler can constrain on.
//!
//! ## Why this exists
//!
//! `llama-cpp-2`'s LocalProvider emits raw tokens — there's no native
//! tool-call parser. Without a grammar constraint, Fanar (and similar
//! smaller models) emits tool-call JSON in **shape-correct most of the
//! time but not all the time**: missing commas, mis-spelled tool names,
//! argument types swapped, prose mixed inside the JSON. That gap is
//! what scored 0/10 on MIG-047 §H's `bench_tool_use.exe`.
//!
//! ## What this produces
//!
//! A grammar describing ONE valid tool-call JSON shape — `tool-call`
//! is the root rule. The grammar is paired with llama-cpp-2's
//! `LlamaSampler::grammar_lazy` (introduced in upstream llama.cpp PR
//! #9639) which only ENFORCES the grammar once the model emits the
//! trigger word `{"tool":`. Up to that point, the model can produce
//! free prose; after the trigger, the grammar constrains the
//! continuation to a well-formed tool-call object.
//!
//! Why lazy + a single-shape grammar (not eager `prose | tool-call`):
//! - The eager alternation crashed llama.cpp's grammar engine
//!   (`GGML_ASSERT(!stacks.empty()) failed`) — the empty-prose branch
//!   creates an ambiguous parse path when the model emits the BOS
//!   token or other special tokens before the first text byte.
//! - Lazy grammar bypasses the problem: the grammar engine is
//!   completely inactive until the trigger word appears, so special
//!   tokens / whitespace / arbitrary prose pass through without
//!   touching the grammar state machine. Once `{"tool":` is emitted,
//!   the grammar takes over and forces a structurally-valid JSON
//!   close.
//!
//! ## Why a simple JSON shape, not full schema enforcement
//!
//! We could generate a per-tool schema-aware grammar (constraining
//! `args` to match the tool's input_schema exactly). That's a Phase 1.x
//! refinement — it's complex to generate from arbitrary JSON Schemas
//! and the validation can be done post-emission instead. For Phase 1
//! the grammar:
//!   1. Locks the wrapper to `{"tool":"<known-name>","args":{...}}`.
//!   2. Lets `args` be any valid JSON object.
//!
//! Argument-value validation is left to each tool's `serde_json::from_value`
//! call (already present in `tools/*.rs::run`); a malformed args object
//! turns into a tool error the model can recover from.
//!
//! Reference: llama.cpp GBNF spec
//! <https://github.com/ggml-org/llama.cpp/blob/master/grammars/README.md>

use crate::mind::provider::ToolSchema;

/// Build a GBNF grammar describing one well-formed tool-call JSON
/// whose `tool` field is one of the palette's tool names. The root
/// rule is named `tool-call`. Pair with `LlamaSampler::grammar_lazy`
/// and the trigger word emitted by [`trigger_word`] so the grammar
/// only constrains continuation AFTER the trigger appears.
pub fn from_tools(palette: &[ToolSchema]) -> String {
    let tool_name_alternation = if palette.is_empty() {
        // Edge case: no tools available. tool-call is technically
        // unreachable but the grammar still parses.
        r#""\"__no_tools__\"""#.to_string()
    } else {
        palette
            .iter()
            .map(|t| format!(r#""\"{}\"""#, t.name))
            .collect::<Vec<_>>()
            .join(" | ")
    };

    format!(
        r##"# Auto-generated by mind::orchestrator::gbnf::from_tools
# Single root: tool-call. Activated by LlamaSampler::grammar_lazy on
# the trigger word `{{"tool":` so prose flows freely until then.

tool-call ::= "{{" ws "\"tool\"" ws ":" ws tool-name ws "," ws "\"args\"" ws ":" ws object ws "}}"

# Tool name — one of the palette's tool names (auto-generated).
tool-name ::= {tool_names}

# Standard JSON value grammar (modelled on llama.cpp/grammars/json.gbnf).
value  ::= object | array | string | number | "true" | "false" | "null"

object ::=
  "{{" ws (
            string ws ":" ws value
    ("," ws string ws ":" ws value)*
  )? "}}"

array  ::=
  "[" ws (
            value
    ("," ws value)*
  )? "]"

string ::= "\"" (
    [^"\\\x00-\x1F] |
    "\\" (["\\/bfnrt] | "u" [0-9a-fA-F] [0-9a-fA-F] [0-9a-fA-F] [0-9a-fA-F])
  )* "\""

number ::= ("-")? ("0" | [1-9] [0-9]*) ("." [0-9]+)? ([eE] [-+]? [0-9]+)?

# Optional whitespace.
ws ::= [ \t\n]*
"##,
        tool_names = tool_name_alternation,
    )
}

/// Trigger word for `LlamaSampler::grammar_lazy`. When this exact byte
/// sequence appears in the sampled output, the grammar engine
/// activates and constrains the remaining continuation to match the
/// `tool-call` rule from [`from_tools`].
pub fn trigger_word() -> &'static [u8] {
    br#"{"tool":"#
}

/// Parse a (possibly partial) tool-call JSON object and extract
/// `(tool_name, args)`. Returns `Ok(None)` if the JSON parses but
/// doesn't match the tool-call shape; `Err` if JSON is malformed
/// (caller should keep buffering — incomplete).
pub fn try_parse_tool_call(
    buffer: &str,
) -> Result<Option<(String, serde_json::Value)>, serde_json::Error> {
    let v: serde_json::Value = serde_json::from_str(buffer.trim())?;
    let tool = v.get("tool").and_then(|t| t.as_str());
    let args = v.get("args").cloned();
    Ok(match (tool, args) {
        (Some(name), Some(args)) => Some((name.to_string(), args)),
        _ => None,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::mind::orchestrator::tools::ready_palette;
    use serde_json::json;

    fn dummy_tool(name: &str) -> ToolSchema {
        ToolSchema {
            name: name.into(),
            description: "test".into(),
            input_schema: json!({"type": "object"}),
        }
    }

    #[test]
    fn grammar_contains_tool_call_root() {
        let g = from_tools(&[dummy_tool("foo"), dummy_tool("bar")]);
        assert!(g.contains("tool-call ::="));
    }

    #[test]
    fn grammar_lists_all_tool_names_in_alternation() {
        let g = from_tools(&[dummy_tool("alpha"), dummy_tool("beta")]);
        assert!(g.contains(r#""\"alpha\"""#));
        assert!(g.contains(r#""\"beta\"""#));
    }

    #[test]
    fn grammar_handles_empty_palette() {
        let g = from_tools(&[]);
        // Should still produce a syntactically-valid grammar (tool-call
        // branch becomes unreachable).
        assert!(g.contains("tool-call ::="));
        assert!(g.contains("__no_tools__"));
    }

    #[test]
    fn trigger_word_matches_canonical_emit_prefix() {
        assert_eq!(trigger_word(), br#"{"tool":"#);
    }

    #[test]
    fn ready_palette_produces_valid_looking_grammar() {
        let palette = ready_palette();
        let g = from_tools(&palette);
        // Every tool name should appear in the grammar's alternation.
        for tool in &palette {
            let needle = format!(r#""\"{}\"""#, tool.name);
            assert!(g.contains(&needle), "missing tool {} in grammar:\n{}", tool.name, g);
        }
    }

    #[test]
    fn parses_complete_tool_call_json() {
        let raw = r#"{"tool":"search_notes","args":{"query":"canopus"}}"#;
        let result = try_parse_tool_call(raw).expect("parse ok");
        let (name, args) = result.expect("matches tool-call shape");
        assert_eq!(name, "search_notes");
        assert_eq!(args, json!({"query": "canopus"}));
    }

    #[test]
    fn returns_none_when_json_does_not_match_tool_call_shape() {
        let raw = r#"{"something": "else"}"#;
        let result = try_parse_tool_call(raw).expect("parse ok");
        assert!(result.is_none());
    }

    #[test]
    fn returns_err_on_incomplete_json() {
        let raw = r#"{"tool":"search_notes","args":{"#;
        assert!(try_parse_tool_call(raw).is_err());
    }
}
