#!/usr/bin/env python3
"""
MIG-022 §E.3.d — Backfill cece.taxonomy.* (277 keys) into 5 mixed-script locales:
ja, ko, zh, ru, tr.

Source of truth:
- src/lib/i18n/en.json    (277 English labels)
- src/lib/i18n/ar.json    (277 Arabic parallels)

This script holds the 5 × 277 translations inline as nested dicts and
writes each cece.taxonomy block into the corresponding locale file
(idempotent: rewrites cece.taxonomy from the table below every run).

Translation conventions:
- Tradition-specific terms (Arabic uṣūl + Sanskrit pramāṇa) keep the
  romanized term in ASCII parens, e.g. "Doubt (shakk)".
- Compound IDs translate the leaf-label only.
- CJK locales may use native punctuation; ko keeps ASCII per common KR
  tech convention. Romanizations stay ASCII.

Run:
    python lab/scripts/mig022_e3d_taxonomy_mixed.py

Don't touch en.json / ar.json / the 8 other locale files.
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(r"E:\مشاريع كلاود\Constellation")
I18N = ROOT / "src/lib/i18n"

LOCALES = ["ja", "ko", "zh", "ru", "tr"]

# ---------------------------------------------------------------------------
# 277 keys × 5 locales. Each locale dict maps the canonical taxonomy id
# (slash-separated, identical to en.json) → translated label.
# ---------------------------------------------------------------------------

JA = {
    "epistemic-content": "認識的コンテンツ",
    # --- sensory-inputs --------------------------------------------------
    "sensory-inputs": "感覚入力",
    "sensory-inputs/signal": "シグナル",
    "sensory-inputs/signal/physical": "物理的シグナル",
    "sensory-inputs/signal/physical/electromagnetic": "電磁的",
    "sensory-inputs/signal/physical/acoustic": "音響的",
    "sensory-inputs/signal/physical/mechanical": "機械的",
    "sensory-inputs/signal/physical/chemical": "化学的",
    "sensory-inputs/signal/biological": "生物学的シグナル",
    "sensory-inputs/signal/biological/neural": "神経的",
    "sensory-inputs/signal/biological/hormonal": "ホルモン的",
    "sensory-inputs/signal/biological/bioelectric": "生体電気的",
    "sensory-inputs/stimulus": "刺激",
    "sensory-inputs/stimulus/distal": "遠位刺激",
    "sensory-inputs/stimulus/proximal": "近位刺激",
    "sensory-inputs/stimulus/conditioned": "条件刺激",
    "sensory-inputs/stimulus/unconditioned": "無条件刺激",
    "sensory-inputs/sense-datum": "感覚与件",
    "sensory-inputs/sense-datum/visual": "視覚的クオリア",
    "sensory-inputs/sense-datum/auditory": "聴覚的クオリア",
    "sensory-inputs/sense-datum/tactile": "触覚的クオリア",
    "sensory-inputs/sense-datum/olfactory": "嗅覚的クオリア",
    "sensory-inputs/sense-datum/gustatory": "味覚的クオリア",
    "sensory-inputs/sense-datum/proprioceptive": "固有受容的クオリア",
    "sensory-inputs/percept": "知覚",
    "sensory-inputs/percept/indeterminate": "未規定知覚 (nirvikalpa)",
    "sensory-inputs/percept/indeterminate/pure-sensation": "純粋感覚",
    "sensory-inputs/percept/determinate": "規定知覚 (savikalpa)",
    "sensory-inputs/percept/determinate/object-recognition": "対象認識",
    "sensory-inputs/percept/determinate/categorized": "カテゴリ化された知覚",
    "sensory-inputs/percept/extraordinary": "超常的知覚 (alaukika)",
    "sensory-inputs/percept/extraordinary/generic": "普遍 (sāmānyalakṣaṇa)",
    "sensory-inputs/percept/extraordinary/acquired": "獲得 (jñānalakṣaṇa)",
    "sensory-inputs/percept/extraordinary/yogic": "ヨーガ的 (yogaja)",
    # --- symbolic-entities -----------------------------------------------
    "symbolic-entities": "象徴的存在",
    "symbolic-entities/sign": "記号 (パースの分類)",
    "symbolic-entities/sign/icon": "イコン — 類似による",
    "symbolic-entities/sign/icon/image": "イメージ",
    "symbolic-entities/sign/icon/diagram": "ダイアグラム",
    "symbolic-entities/sign/icon/metaphor": "メタファー",
    "symbolic-entities/sign/index": "インデックス — 因果的接続による",
    "symbolic-entities/sign/index/symptom": "症候",
    "symbolic-entities/sign/index/trace": "痕跡",
    "symbolic-entities/sign/index/pointer": "ポインター",
    "symbolic-entities/sign/symbol-conventional": "シンボル — 規約による",
    "symbolic-entities/sign/symbol-conventional/word": "語",
    "symbolic-entities/sign/symbol-conventional/numeral": "数字",
    "symbolic-entities/sign/symbol-conventional/logical-operator": "論理演算子",
    "symbolic-entities/symbol": "シンボル",
    "symbolic-entities/symbol/linguistic": "言語的シンボル",
    "symbolic-entities/symbol/linguistic/phoneme": "音素",
    "symbolic-entities/symbol/linguistic/morpheme": "形態素",
    "symbolic-entities/symbol/linguistic/lexeme": "語彙素",
    "symbolic-entities/symbol/mathematical": "数学的シンボル",
    "symbolic-entities/symbol/logical": "論理的シンボル",
    "symbolic-entities/symbol/iconographic": "図像的シンボル",
    "symbolic-entities/data": "データ",
    "symbolic-entities/data/structured": "構造化データ",
    "symbolic-entities/data/structured/tabular": "表形式",
    "symbolic-entities/data/structured/relational": "関係型",
    "symbolic-entities/data/semi-structured": "半構造化データ",
    "symbolic-entities/data/semi-structured/serialized": "JSON / XML / YAML",
    "symbolic-entities/data/unstructured": "非構造化データ",
    "symbolic-entities/data/unstructured/text": "テキスト",
    "symbolic-entities/data/unstructured/image": "画像",
    "symbolic-entities/data/unstructured/audio": "音声",
    "symbolic-entities/data/unstructured/video": "動画",
    "symbolic-entities/data/quantitative": "定量的データ",
    "symbolic-entities/data/qualitative": "定性的データ",
    "symbolic-entities/code": "コード",
    "symbolic-entities/code/natural-language": "自然言語コード",
    "symbolic-entities/code/formal-language": "形式言語コード",
    "symbolic-entities/code/computer": "コンピュータコード",
    "symbolic-entities/code/cryptographic": "暗号コード",
    "symbolic-entities/inscription": "刻記",
    "symbolic-entities/inscription/oral": "口承",
    "symbolic-entities/inscription/manuscript": "写本",
    "symbolic-entities/inscription/print": "印刷",
    "symbolic-entities/inscription/digital": "デジタル",
    # --- semantic-contents -----------------------------------------------
    "semantic-contents": "意味内容",
    "semantic-contents/concept": "概念 (taṣawwur)",
    "semantic-contents/concept/simple": "単純概念",
    "semantic-contents/concept/compound": "複合概念",
    "semantic-contents/concept/empirical": "経験的概念",
    "semantic-contents/concept/empirical/observational": "観察的",
    "semantic-contents/concept/empirical/experimental": "実験的",
    "semantic-contents/concept/a-priori": "ア・プリオリ概念",
    "semantic-contents/concept/a-priori/logical": "論理的",
    "semantic-contents/concept/a-priori/mathematical": "数学的",
    "semantic-contents/concept/concrete": "具体概念",
    "semantic-contents/concept/abstract": "抽象概念",
    "semantic-contents/idea": "観念",
    "semantic-contents/idea/innate": "生得観念 (デカルト)",
    "semantic-contents/idea/adventitious": "外来観念",
    "semantic-contents/idea/constructed": "構成観念",
    "semantic-contents/idea/clear-distinct": "明晰判明な観念",
    "semantic-contents/proposition": "命題 (qaḍiyyah)",
    "semantic-contents/proposition/categorical": "定言命題",
    "semantic-contents/proposition/categorical/universal-affirmative": "全称肯定",
    "semantic-contents/proposition/categorical/universal-negative": "全称否定",
    "semantic-contents/proposition/categorical/particular-affirmative": "特称肯定",
    "semantic-contents/proposition/categorical/particular-negative": "特称否定",
    "semantic-contents/proposition/hypothetical": "仮言命題",
    "semantic-contents/proposition/hypothetical/conjunctive": "連言的 (muttaṣilah)",
    "semantic-contents/proposition/hypothetical/disjunctive": "選言的 (munfaṣilah)",
    "semantic-contents/proposition/modal": "様相命題",
    "semantic-contents/proposition/modal/necessary": "必然",
    "semantic-contents/proposition/modal/possible": "可能",
    "semantic-contents/proposition/modal/impossible": "不可能",
    "semantic-contents/information": "情報 (DIKW T2)",
    "semantic-contents/information/syntactic": "統語的情報",
    "semantic-contents/information/semantic": "意味的情報",
    "semantic-contents/information/pragmatic": "語用的情報",
    "semantic-contents/fact": "事実 (wāqiʿah)",
    "semantic-contents/fact/empirical": "経験的事実",
    "semantic-contents/fact/mathematical": "数学的事実",
    "semantic-contents/fact/logical": "論理的事実",
    "semantic-contents/fact/historical": "歴史的事実",
    "semantic-contents/fact/moral": "道徳的事実",
    "semantic-contents/meaning": "意味 (maʿnā)",
    "semantic-contents/meaning/sense-vs-reference": "意義 vs. 指示 (フレーゲ)",
    "semantic-contents/meaning/connotation-vs-denotation": "内包 vs. 外延",
    "semantic-contents/meaning/literal-vs-figurative": "字義通り vs. 比喩的",
    "semantic-contents/definition": "定義 (ḥadd)",
    "semantic-contents/definition/real": "実質的定義",
    "semantic-contents/definition/nominal": "名目的定義",
    "semantic-contents/definition/genus-differentia": "類差定義",
    "semantic-contents/definition/ostensive": "直示的定義",
    # --- epistemic-states ------------------------------------------------
    "epistemic-states": "認識的状態",
    "epistemic-states/compound-ignorance": "複合的無知",
    "epistemic-states/simple-ignorance": "単純無知",
    "epistemic-states/illusion": "錯覚 (wahm)",
    "epistemic-states/illusion/perceptual": "知覚的錯覚",
    "epistemic-states/illusion/cognitive": "認知的錯覚",
    "epistemic-states/doubt": "疑い (shakk)",
    "epistemic-states/doubt/methodological": "方法論的懐疑",
    "epistemic-states/doubt/habitual": "習慣的懐疑",
    "epistemic-states/doubt/equipoised": "両端均衡的懐疑",
    "epistemic-states/opinion": "意見 (ẓann)",
    "epistemic-states/opinion/probable": "蓋然的意見",
    "epistemic-states/opinion/well-grounded": "十分に根拠ある意見",
    "epistemic-states/opinion/dispositional": "傾向的意見",
    "epistemic-states/belief": "信念 (iʿtiqād / taṣdīq)",
    "epistemic-states/belief/occurrent": "顕在的信念",
    "epistemic-states/belief/dispositional": "傾向的信念",
    "epistemic-states/belief/faith": "信仰 (īmān)",
    "epistemic-states/knowledge": "知識 (ʿilm / maʿrifah)",
    "epistemic-states/knowledge/by-mode": "表象様式による",
    "epistemic-states/knowledge/by-mode/acquired": "獲得知 (al-ʿilm al-ḥuṣūlī)",
    "epistemic-states/knowledge/by-mode/presential": "現前知 (al-ʿilm al-ḥuḍūrī)",
    "epistemic-states/knowledge/by-content": "内容種別による",
    "epistemic-states/knowledge/by-content/propositional": "命題的 (knowledge-that)",
    "epistemic-states/knowledge/by-content/propositional/a-priori-analytic": "ア・プリオリ — 分析的",
    "epistemic-states/knowledge/by-content/propositional/a-priori-synthetic": "ア・プリオリ — 総合的",
    "epistemic-states/knowledge/by-content/propositional/a-posteriori-empirical": "ア・ポステリオリ — 経験的",
    "epistemic-states/knowledge/by-content/propositional/a-posteriori-testimonial": "ア・ポステリオリ — 証言的",
    "epistemic-states/knowledge/by-content/procedural": "手続き的 (knowledge-how)",
    "epistemic-states/knowledge/by-content/procedural/motor": "運動技能",
    "epistemic-states/knowledge/by-content/procedural/cognitive": "認知技能",
    "epistemic-states/knowledge/by-content/procedural/social": "社会的技能",
    "epistemic-states/knowledge/by-content/acquaintance": "面識 (knowledge-of)",
    "epistemic-states/knowledge/by-content/acquaintance/direct-experience": "直接経験による",
    "epistemic-states/knowledge/by-content/acquaintance/memory": "記憶による",
    "epistemic-states/knowledge/by-content/tacit": "暗黙知 (ポランニー)",
    "epistemic-states/knowledge/by-source": "源泉による",
    "epistemic-states/knowledge/by-source/sensory": "感覚的知識",
    "epistemic-states/knowledge/by-source/rational": "理性的知識",
    "epistemic-states/knowledge/by-source/testimonial": "証言的知識",
    "epistemic-states/knowledge/by-source/revelatory": "啓示的知識",
    "epistemic-states/certainty": "確信 (yaqīn)",
    "epistemic-states/certainty/logical": "論理的確信",
    "epistemic-states/certainty/mathematical": "数学的確信",
    "epistemic-states/certainty/metaphysical": "形而上学的確信",
    "epistemic-states/certainty/moral": "道徳的確信",
    "epistemic-states/certainty/religious": "宗教的確信",
    "epistemic-states/certainty/religious/ilm-al-yaqin": "ʿIlm al-yaqīn — 確信の知",
    "epistemic-states/certainty/religious/ayn-al-yaqin": "ʿAyn al-yaqīn — 確信の眼",
    "epistemic-states/certainty/religious/haqq-al-yaqin": "Ḥaqq al-yaqīn — 確信の真理",
    # --- higher-order-constructs -----------------------------------------
    "higher-order-constructs": "高次構成",
    "higher-order-constructs/hypothesis": "仮説 (faraḍiyyah)",
    "higher-order-constructs/hypothesis/working": "作業仮説",
    "higher-order-constructs/hypothesis/statistical": "統計的仮説",
    "higher-order-constructs/hypothesis/statistical/null": "帰無仮説",
    "higher-order-constructs/hypothesis/statistical/alternative": "対立仮説",
    "higher-order-constructs/hypothesis/causal": "因果仮説",
    "higher-order-constructs/theory": "理論 (naẓariyyah)",
    "higher-order-constructs/theory/empirical": "経験的理論",
    "higher-order-constructs/theory/empirical/descriptive": "記述的",
    "higher-order-constructs/theory/empirical/explanatory": "説明的",
    "higher-order-constructs/theory/empirical/predictive": "予測的",
    "higher-order-constructs/theory/formal": "形式的理論",
    "higher-order-constructs/theory/normative": "規範的理論",
    "higher-order-constructs/model": "モデル (namūdhaj)",
    "higher-order-constructs/model/physical": "物理モデル",
    "higher-order-constructs/model/mathematical": "数学モデル",
    "higher-order-constructs/model/computational": "計算モデル",
    "higher-order-constructs/model/conceptual": "概念モデル",
    "higher-order-constructs/law": "法則 (qānūn)",
    "higher-order-constructs/law/natural": "自然法則",
    "higher-order-constructs/law/natural/universal": "普遍的法則",
    "higher-order-constructs/law/natural/statistical": "統計的法則",
    "higher-order-constructs/law/logical": "論理法則",
    "higher-order-constructs/law/logical/identity": "同一律",
    "higher-order-constructs/law/logical/non-contradiction": "矛盾律",
    "higher-order-constructs/law/logical/excluded-middle": "排中律",
    "higher-order-constructs/law/divine": "神聖法 (sharīʿah)",
    "higher-order-constructs/law/positive": "実定法",
    "higher-order-constructs/doctrine": "教説 (madhhab)",
    "higher-order-constructs/doctrine/religious": "宗教的教説",
    "higher-order-constructs/doctrine/philosophical": "哲学的教説",
    "higher-order-constructs/doctrine/scientific": "科学的教説",
    "higher-order-constructs/insight": "洞察 (baṣīrah)",
    "higher-order-constructs/insight/aesthetic": "美的洞察",
    "higher-order-constructs/insight/mystical": "神秘的洞察",
    "higher-order-constructs/insight/scientific": "科学的洞察",
    "higher-order-constructs/wisdom": "知恵 (ḥikmah)",
    "higher-order-constructs/wisdom/theoretical": "理論知 (sophia)",
    "higher-order-constructs/wisdom/practical": "実践知 (phronēsis)",
    "higher-order-constructs/wisdom/productive-craft": "制作技 (technē)",
    "higher-order-constructs/wisdom/spiritual": "霊的知恵",
    "higher-order-constructs/worldview": "世界観 (ruʾyah kawniyyah)",
    "higher-order-constructs/worldview/religious": "宗教的世界観",
    "higher-order-constructs/worldview/secular": "世俗的世界観",
    "higher-order-constructs/worldview/syncretic": "習合的世界観",
    # --- perception ------------------------------------------------------
    "perception": "知覚 / 感覚",
    "perception/external": "外的知覚",
    "perception/internal": "内的知覚",
    "perception/self": "自己知覚",
    "perception/extraordinary": "超常的知覚",
    # --- inference -------------------------------------------------------
    "inference": "推論 / 理性",
    "inference/deductive": "演繹的推論",
    "inference/inductive": "帰納的推論",
    "inference/abductive": "アブダクション的推論",
    "inference/necessary": "必然的理性",
    "inference/speculative": "思弁的理性",
    # --- testimony -------------------------------------------------------
    "testimony": "証言",
    "testimony/direct-witness": "直接目撃証言",
    "testimony/reported": "伝聞証言",
    "testimony/authoritative": "権威的証言",
    "testimony/scriptural": "聖典的証言",
    # --- mass-transmission -----------------------------------------------
    "mass-transmission": "集合的伝達 (al-tawatur)",
    "mass-transmission/verbal": "言語的集合伝達",
    "mass-transmission/meaning": "意味的集合伝達",
    "mass-transmission/practical": "実践的集合伝達",
    # --- comparison ------------------------------------------------------
    "comparison": "比較 / アナロジー",
    "comparison/ratio-legis": "ratio legis によるアナロジー",
    "comparison/indication": "指示によるアナロジー",
    "comparison/resemblance": "類似によるアナロジー",
    "comparison/a-fortiori": "a fortiori アナロジー",
    # --- postulation -----------------------------------------------------
    "postulation": "措定 / IBE",
    "postulation/from-perceived": "知覚された事実から",
    "postulation/from-heard": "聴取された事実から",
    "postulation/ibe": "最良説明への推論",
    # --- non-apprehension ------------------------------------------------
    "non-apprehension": "非把握",
    "non-apprehension/prior": "事前的不在",
    "non-apprehension/posterior": "事後的不在",
    "non-apprehension/mutual": "相互的不在",
    "non-apprehension/absolute": "絶対的不在",
    # --- memory ----------------------------------------------------------
    "memory": "記憶",
    "memory/recollection": "想起",
    "memory/recognition": "再認",
    "memory/episodic": "エピソード記憶",
    "memory/semantic": "意味記憶",
    # --- innate-disposition ----------------------------------------------
    "innate-disposition": "生得的素質 / 直観",
    "innate-disposition/primordial": "原初的素質 (スンナ派)",
    "innate-disposition/first-principles": "第一原理の直観",
    "innate-disposition/moral": "生得的道徳知",
    "innate-disposition/axioms": "自明の公理",
    # --- inspiration -----------------------------------------------------
    "inspiration": "霊感 / 神秘的把握",
    "inspiration/ilham": "Ilhām (霊感)",
    "inspiration/kashf": "Kashf (開示)",
    "inspiration/dream-vision": "真の夢幻",
    # --- revelation ------------------------------------------------------
    "revelation": "啓示",
    "revelation/recited": "誦読される啓示 (クルアーン)",
    "revelation/non-recited": "誦読されない啓示 (スンナ)",
    "revelation/modes-of-receiving": "啓示を受ける諸様式",
    # --- unclassifiable --------------------------------------------------
    "unclassifiable": "分類不能",
}

KO = {
    "epistemic-content": "인식적 내용",
    # --- sensory-inputs --------------------------------------------------
    "sensory-inputs": "감각 입력",
    "sensory-inputs/signal": "신호",
    "sensory-inputs/signal/physical": "물리적 신호",
    "sensory-inputs/signal/physical/electromagnetic": "전자기적",
    "sensory-inputs/signal/physical/acoustic": "음향적",
    "sensory-inputs/signal/physical/mechanical": "기계적",
    "sensory-inputs/signal/physical/chemical": "화학적",
    "sensory-inputs/signal/biological": "생물학적 신호",
    "sensory-inputs/signal/biological/neural": "신경적",
    "sensory-inputs/signal/biological/hormonal": "호르몬적",
    "sensory-inputs/signal/biological/bioelectric": "생체전기적",
    "sensory-inputs/stimulus": "자극",
    "sensory-inputs/stimulus/distal": "원위 자극",
    "sensory-inputs/stimulus/proximal": "근위 자극",
    "sensory-inputs/stimulus/conditioned": "조건 자극",
    "sensory-inputs/stimulus/unconditioned": "무조건 자극",
    "sensory-inputs/sense-datum": "감각 자료",
    "sensory-inputs/sense-datum/visual": "시각적 퀄리아",
    "sensory-inputs/sense-datum/auditory": "청각적 퀄리아",
    "sensory-inputs/sense-datum/tactile": "촉각적 퀄리아",
    "sensory-inputs/sense-datum/olfactory": "후각적 퀄리아",
    "sensory-inputs/sense-datum/gustatory": "미각적 퀄리아",
    "sensory-inputs/sense-datum/proprioceptive": "고유 수용성 퀄리아",
    "sensory-inputs/percept": "지각",
    "sensory-inputs/percept/indeterminate": "비규정적 지각 (nirvikalpa)",
    "sensory-inputs/percept/indeterminate/pure-sensation": "순수 감각",
    "sensory-inputs/percept/determinate": "규정적 지각 (savikalpa)",
    "sensory-inputs/percept/determinate/object-recognition": "대상 인식",
    "sensory-inputs/percept/determinate/categorized": "범주화된 지각",
    "sensory-inputs/percept/extraordinary": "초상적 지각 (alaukika)",
    "sensory-inputs/percept/extraordinary/generic": "보편적 (sāmānyalakṣaṇa)",
    "sensory-inputs/percept/extraordinary/acquired": "획득된 (jñānalakṣaṇa)",
    "sensory-inputs/percept/extraordinary/yogic": "요가적 (yogaja)",
    # --- symbolic-entities -----------------------------------------------
    "symbolic-entities": "상징적 실체",
    "symbolic-entities/sign": "기호 (퍼스의 분류)",
    "symbolic-entities/sign/icon": "아이콘 — 유사성에 의한",
    "symbolic-entities/sign/icon/image": "이미지",
    "symbolic-entities/sign/icon/diagram": "도해",
    "symbolic-entities/sign/icon/metaphor": "은유",
    "symbolic-entities/sign/index": "지표 — 인과적 연결에 의한",
    "symbolic-entities/sign/index/symptom": "증후",
    "symbolic-entities/sign/index/trace": "흔적",
    "symbolic-entities/sign/index/pointer": "포인터",
    "symbolic-entities/sign/symbol-conventional": "상징 — 약속에 의한",
    "symbolic-entities/sign/symbol-conventional/word": "단어",
    "symbolic-entities/sign/symbol-conventional/numeral": "숫자",
    "symbolic-entities/sign/symbol-conventional/logical-operator": "논리 연산자",
    "symbolic-entities/symbol": "상징",
    "symbolic-entities/symbol/linguistic": "언어적 상징",
    "symbolic-entities/symbol/linguistic/phoneme": "음소",
    "symbolic-entities/symbol/linguistic/morpheme": "형태소",
    "symbolic-entities/symbol/linguistic/lexeme": "어휘소",
    "symbolic-entities/symbol/mathematical": "수학적 상징",
    "symbolic-entities/symbol/logical": "논리적 상징",
    "symbolic-entities/symbol/iconographic": "도상적 상징",
    "symbolic-entities/data": "데이터",
    "symbolic-entities/data/structured": "구조화된 데이터",
    "symbolic-entities/data/structured/tabular": "표 형식",
    "symbolic-entities/data/structured/relational": "관계형",
    "symbolic-entities/data/semi-structured": "반구조화된 데이터",
    "symbolic-entities/data/semi-structured/serialized": "JSON / XML / YAML",
    "symbolic-entities/data/unstructured": "비구조화된 데이터",
    "symbolic-entities/data/unstructured/text": "텍스트",
    "symbolic-entities/data/unstructured/image": "이미지",
    "symbolic-entities/data/unstructured/audio": "오디오",
    "symbolic-entities/data/unstructured/video": "비디오",
    "symbolic-entities/data/quantitative": "정량적 데이터",
    "symbolic-entities/data/qualitative": "정성적 데이터",
    "symbolic-entities/code": "코드",
    "symbolic-entities/code/natural-language": "자연어 코드",
    "symbolic-entities/code/formal-language": "형식 언어 코드",
    "symbolic-entities/code/computer": "컴퓨터 코드",
    "symbolic-entities/code/cryptographic": "암호 코드",
    "symbolic-entities/inscription": "기록",
    "symbolic-entities/inscription/oral": "구술",
    "symbolic-entities/inscription/manuscript": "필사본",
    "symbolic-entities/inscription/print": "인쇄",
    "symbolic-entities/inscription/digital": "디지털",
    # --- semantic-contents -----------------------------------------------
    "semantic-contents": "의미 내용",
    "semantic-contents/concept": "개념 (taṣawwur)",
    "semantic-contents/concept/simple": "단순 개념",
    "semantic-contents/concept/compound": "복합 개념",
    "semantic-contents/concept/empirical": "경험적 개념",
    "semantic-contents/concept/empirical/observational": "관찰적",
    "semantic-contents/concept/empirical/experimental": "실험적",
    "semantic-contents/concept/a-priori": "선험적 개념",
    "semantic-contents/concept/a-priori/logical": "논리적",
    "semantic-contents/concept/a-priori/mathematical": "수학적",
    "semantic-contents/concept/concrete": "구체적 개념",
    "semantic-contents/concept/abstract": "추상적 개념",
    "semantic-contents/idea": "관념",
    "semantic-contents/idea/innate": "본유 관념 (데카르트)",
    "semantic-contents/idea/adventitious": "외래 관념",
    "semantic-contents/idea/constructed": "구성된 관념",
    "semantic-contents/idea/clear-distinct": "명석하고 판명한 관념",
    "semantic-contents/proposition": "명제 (qaḍiyyah)",
    "semantic-contents/proposition/categorical": "정언 명제",
    "semantic-contents/proposition/categorical/universal-affirmative": "전칭 긍정",
    "semantic-contents/proposition/categorical/universal-negative": "전칭 부정",
    "semantic-contents/proposition/categorical/particular-affirmative": "특칭 긍정",
    "semantic-contents/proposition/categorical/particular-negative": "특칭 부정",
    "semantic-contents/proposition/hypothetical": "가언 명제",
    "semantic-contents/proposition/hypothetical/conjunctive": "연언적 (muttaṣilah)",
    "semantic-contents/proposition/hypothetical/disjunctive": "선언적 (munfaṣilah)",
    "semantic-contents/proposition/modal": "양상 명제",
    "semantic-contents/proposition/modal/necessary": "필연",
    "semantic-contents/proposition/modal/possible": "가능",
    "semantic-contents/proposition/modal/impossible": "불가능",
    "semantic-contents/information": "정보 (DIKW T2)",
    "semantic-contents/information/syntactic": "통사적 정보",
    "semantic-contents/information/semantic": "의미적 정보",
    "semantic-contents/information/pragmatic": "화용적 정보",
    "semantic-contents/fact": "사실 (wāqiʿah)",
    "semantic-contents/fact/empirical": "경험적 사실",
    "semantic-contents/fact/mathematical": "수학적 사실",
    "semantic-contents/fact/logical": "논리적 사실",
    "semantic-contents/fact/historical": "역사적 사실",
    "semantic-contents/fact/moral": "도덕적 사실",
    "semantic-contents/meaning": "의미 (maʿnā)",
    "semantic-contents/meaning/sense-vs-reference": "뜻 vs. 지시 (프레게)",
    "semantic-contents/meaning/connotation-vs-denotation": "내포 vs. 외연",
    "semantic-contents/meaning/literal-vs-figurative": "축자적 vs. 비유적",
    "semantic-contents/definition": "정의 (ḥadd)",
    "semantic-contents/definition/real": "실질적 정의",
    "semantic-contents/definition/nominal": "명목적 정의",
    "semantic-contents/definition/genus-differentia": "유-종차 정의",
    "semantic-contents/definition/ostensive": "지시적 정의",
    # --- epistemic-states ------------------------------------------------
    "epistemic-states": "인식적 상태",
    "epistemic-states/compound-ignorance": "복합적 무지",
    "epistemic-states/simple-ignorance": "단순 무지",
    "epistemic-states/illusion": "착각 (wahm)",
    "epistemic-states/illusion/perceptual": "지각적 착각",
    "epistemic-states/illusion/cognitive": "인지적 착각",
    "epistemic-states/doubt": "의심 (shakk)",
    "epistemic-states/doubt/methodological": "방법적 의심",
    "epistemic-states/doubt/habitual": "습관적 의심",
    "epistemic-states/doubt/equipoised": "양단 균형 의심",
    "epistemic-states/opinion": "의견 (ẓann)",
    "epistemic-states/opinion/probable": "개연적 의견",
    "epistemic-states/opinion/well-grounded": "근거가 충분한 의견",
    "epistemic-states/opinion/dispositional": "성향적 의견",
    "epistemic-states/belief": "믿음 (iʿtiqād / taṣdīq)",
    "epistemic-states/belief/occurrent": "현행적 믿음",
    "epistemic-states/belief/dispositional": "성향적 믿음",
    "epistemic-states/belief/faith": "신앙 (īmān)",
    "epistemic-states/knowledge": "지식 (ʿilm / maʿrifah)",
    "epistemic-states/knowledge/by-mode": "표상 양식별",
    "epistemic-states/knowledge/by-mode/acquired": "획득지 (al-ʿilm al-ḥuṣūlī)",
    "epistemic-states/knowledge/by-mode/presential": "현전지 (al-ʿilm al-ḥuḍūrī)",
    "epistemic-states/knowledge/by-content": "내용 유형별",
    "epistemic-states/knowledge/by-content/propositional": "명제적 (knowledge-that)",
    "epistemic-states/knowledge/by-content/propositional/a-priori-analytic": "선험적 — 분석적",
    "epistemic-states/knowledge/by-content/propositional/a-priori-synthetic": "선험적 — 종합적",
    "epistemic-states/knowledge/by-content/propositional/a-posteriori-empirical": "후험적 — 경험적",
    "epistemic-states/knowledge/by-content/propositional/a-posteriori-testimonial": "후험적 — 증언적",
    "epistemic-states/knowledge/by-content/procedural": "절차적 (knowledge-how)",
    "epistemic-states/knowledge/by-content/procedural/motor": "운동 기능",
    "epistemic-states/knowledge/by-content/procedural/cognitive": "인지 기능",
    "epistemic-states/knowledge/by-content/procedural/social": "사회적 기능",
    "epistemic-states/knowledge/by-content/acquaintance": "면식 (knowledge-of)",
    "epistemic-states/knowledge/by-content/acquaintance/direct-experience": "직접 경험에 의한",
    "epistemic-states/knowledge/by-content/acquaintance/memory": "기억에 의한",
    "epistemic-states/knowledge/by-content/tacit": "암묵지 (폴라니)",
    "epistemic-states/knowledge/by-source": "원천별",
    "epistemic-states/knowledge/by-source/sensory": "감각적 지식",
    "epistemic-states/knowledge/by-source/rational": "이성적 지식",
    "epistemic-states/knowledge/by-source/testimonial": "증언적 지식",
    "epistemic-states/knowledge/by-source/revelatory": "계시적 지식",
    "epistemic-states/certainty": "확신 (yaqīn)",
    "epistemic-states/certainty/logical": "논리적 확신",
    "epistemic-states/certainty/mathematical": "수학적 확신",
    "epistemic-states/certainty/metaphysical": "형이상학적 확신",
    "epistemic-states/certainty/moral": "도덕적 확신",
    "epistemic-states/certainty/religious": "종교적 확신",
    "epistemic-states/certainty/religious/ilm-al-yaqin": "ʿIlm al-yaqīn — 확신의 지식",
    "epistemic-states/certainty/religious/ayn-al-yaqin": "ʿAyn al-yaqīn — 확신의 눈",
    "epistemic-states/certainty/religious/haqq-al-yaqin": "Ḥaqq al-yaqīn — 확신의 진리",
    # --- higher-order-constructs -----------------------------------------
    "higher-order-constructs": "고차 구성물",
    "higher-order-constructs/hypothesis": "가설 (faraḍiyyah)",
    "higher-order-constructs/hypothesis/working": "작업 가설",
    "higher-order-constructs/hypothesis/statistical": "통계적 가설",
    "higher-order-constructs/hypothesis/statistical/null": "귀무가설",
    "higher-order-constructs/hypothesis/statistical/alternative": "대립가설",
    "higher-order-constructs/hypothesis/causal": "인과적 가설",
    "higher-order-constructs/theory": "이론 (naẓariyyah)",
    "higher-order-constructs/theory/empirical": "경험적 이론",
    "higher-order-constructs/theory/empirical/descriptive": "기술적",
    "higher-order-constructs/theory/empirical/explanatory": "설명적",
    "higher-order-constructs/theory/empirical/predictive": "예측적",
    "higher-order-constructs/theory/formal": "형식적 이론",
    "higher-order-constructs/theory/normative": "규범적 이론",
    "higher-order-constructs/model": "모델 (namūdhaj)",
    "higher-order-constructs/model/physical": "물리 모델",
    "higher-order-constructs/model/mathematical": "수학 모델",
    "higher-order-constructs/model/computational": "계산 모델",
    "higher-order-constructs/model/conceptual": "개념 모델",
    "higher-order-constructs/law": "법칙 (qānūn)",
    "higher-order-constructs/law/natural": "자연법칙",
    "higher-order-constructs/law/natural/universal": "보편 법칙",
    "higher-order-constructs/law/natural/statistical": "통계 법칙",
    "higher-order-constructs/law/logical": "논리 법칙",
    "higher-order-constructs/law/logical/identity": "동일률",
    "higher-order-constructs/law/logical/non-contradiction": "모순율",
    "higher-order-constructs/law/logical/excluded-middle": "배중률",
    "higher-order-constructs/law/divine": "신법 (sharīʿah)",
    "higher-order-constructs/law/positive": "실정법",
    "higher-order-constructs/doctrine": "교의 (madhhab)",
    "higher-order-constructs/doctrine/religious": "종교적 교의",
    "higher-order-constructs/doctrine/philosophical": "철학적 교의",
    "higher-order-constructs/doctrine/scientific": "과학적 교의",
    "higher-order-constructs/insight": "통찰 (baṣīrah)",
    "higher-order-constructs/insight/aesthetic": "미적 통찰",
    "higher-order-constructs/insight/mystical": "신비적 통찰",
    "higher-order-constructs/insight/scientific": "과학적 통찰",
    "higher-order-constructs/wisdom": "지혜 (ḥikmah)",
    "higher-order-constructs/wisdom/theoretical": "이론적 지혜 (sophia)",
    "higher-order-constructs/wisdom/practical": "실천적 지혜 (phronēsis)",
    "higher-order-constructs/wisdom/productive-craft": "제작적 기예 (technē)",
    "higher-order-constructs/wisdom/spiritual": "영적 지혜",
    "higher-order-constructs/worldview": "세계관 (ruʾyah kawniyyah)",
    "higher-order-constructs/worldview/religious": "종교적 세계관",
    "higher-order-constructs/worldview/secular": "세속적 세계관",
    "higher-order-constructs/worldview/syncretic": "혼합주의적 세계관",
    # --- perception ------------------------------------------------------
    "perception": "지각 / 감각",
    "perception/external": "외적 지각",
    "perception/internal": "내적 지각",
    "perception/self": "자기 지각",
    "perception/extraordinary": "초상적 지각",
    # --- inference -------------------------------------------------------
    "inference": "추론 / 이성",
    "inference/deductive": "연역 추론",
    "inference/inductive": "귀납 추론",
    "inference/abductive": "가추 추론",
    "inference/necessary": "필연적 이성",
    "inference/speculative": "사변적 이성",
    # --- testimony -------------------------------------------------------
    "testimony": "증언",
    "testimony/direct-witness": "직접 목격 증언",
    "testimony/reported": "전언적 증언",
    "testimony/authoritative": "권위적 증언",
    "testimony/scriptural": "경전적 증언",
    # --- mass-transmission -----------------------------------------------
    "mass-transmission": "집단 전승 (al-tawatur)",
    "mass-transmission/verbal": "언어적 집단 전승",
    "mass-transmission/meaning": "의미적 집단 전승",
    "mass-transmission/practical": "실천적 집단 전승",
    # --- comparison ------------------------------------------------------
    "comparison": "비교 / 유비",
    "comparison/ratio-legis": "ratio legis에 의한 유비",
    "comparison/indication": "지시에 의한 유비",
    "comparison/resemblance": "유사성에 의한 유비",
    "comparison/a-fortiori": "a fortiori 유비",
    # --- postulation -----------------------------------------------------
    "postulation": "가정 / IBE",
    "postulation/from-perceived": "지각된 사실로부터",
    "postulation/from-heard": "전해 들은 사실로부터",
    "postulation/ibe": "최선의 설명으로의 추론",
    # --- non-apprehension ------------------------------------------------
    "non-apprehension": "비파악",
    "non-apprehension/prior": "사전적 부재",
    "non-apprehension/posterior": "사후적 부재",
    "non-apprehension/mutual": "상호적 부재",
    "non-apprehension/absolute": "절대적 부재",
    # --- memory ----------------------------------------------------------
    "memory": "기억",
    "memory/recollection": "회상",
    "memory/recognition": "재인",
    "memory/episodic": "일화 기억",
    "memory/semantic": "의미 기억",
    # --- innate-disposition ----------------------------------------------
    "innate-disposition": "본유적 성향 / 직관",
    "innate-disposition/primordial": "원초적 성향 (수니파)",
    "innate-disposition/first-principles": "제일원리의 직관",
    "innate-disposition/moral": "본유적 도덕 지식",
    "innate-disposition/axioms": "자명한 공리",
    # --- inspiration -----------------------------------------------------
    "inspiration": "영감 / 신비적 파악",
    "inspiration/ilham": "Ilhām (영감)",
    "inspiration/kashf": "Kashf (현현)",
    "inspiration/dream-vision": "참된 꿈 환영",
    # --- revelation ------------------------------------------------------
    "revelation": "계시",
    "revelation/recited": "낭송된 계시 (꾸란)",
    "revelation/non-recited": "낭송되지 않은 계시 (순나)",
    "revelation/modes-of-receiving": "계시를 받는 양식들",
    # --- unclassifiable --------------------------------------------------
    "unclassifiable": "분류 불가",
}

ZH = {
    "epistemic-content": "认知内容",
    # --- sensory-inputs --------------------------------------------------
    "sensory-inputs": "感觉输入",
    "sensory-inputs/signal": "信号",
    "sensory-inputs/signal/physical": "物理信号",
    "sensory-inputs/signal/physical/electromagnetic": "电磁",
    "sensory-inputs/signal/physical/acoustic": "声学",
    "sensory-inputs/signal/physical/mechanical": "机械",
    "sensory-inputs/signal/physical/chemical": "化学",
    "sensory-inputs/signal/biological": "生物信号",
    "sensory-inputs/signal/biological/neural": "神经",
    "sensory-inputs/signal/biological/hormonal": "激素",
    "sensory-inputs/signal/biological/bioelectric": "生物电",
    "sensory-inputs/stimulus": "刺激",
    "sensory-inputs/stimulus/distal": "远端刺激",
    "sensory-inputs/stimulus/proximal": "近端刺激",
    "sensory-inputs/stimulus/conditioned": "条件刺激",
    "sensory-inputs/stimulus/unconditioned": "无条件刺激",
    "sensory-inputs/sense-datum": "感觉与料",
    "sensory-inputs/sense-datum/visual": "视觉感质",
    "sensory-inputs/sense-datum/auditory": "听觉感质",
    "sensory-inputs/sense-datum/tactile": "触觉感质",
    "sensory-inputs/sense-datum/olfactory": "嗅觉感质",
    "sensory-inputs/sense-datum/gustatory": "味觉感质",
    "sensory-inputs/sense-datum/proprioceptive": "本体感觉感质",
    "sensory-inputs/percept": "知觉",
    "sensory-inputs/percept/indeterminate": "无定知觉 (nirvikalpa)",
    "sensory-inputs/percept/indeterminate/pure-sensation": "纯粹感觉",
    "sensory-inputs/percept/determinate": "有定知觉 (savikalpa)",
    "sensory-inputs/percept/determinate/object-recognition": "对象识别",
    "sensory-inputs/percept/determinate/categorized": "范畴化知觉",
    "sensory-inputs/percept/extraordinary": "超凡知觉 (alaukika)",
    "sensory-inputs/percept/extraordinary/generic": "类相 (sāmānyalakṣaṇa)",
    "sensory-inputs/percept/extraordinary/acquired": "习得 (jñānalakṣaṇa)",
    "sensory-inputs/percept/extraordinary/yogic": "瑜伽 (yogaja)",
    # --- symbolic-entities -----------------------------------------------
    "symbolic-entities": "符号实体",
    "symbolic-entities/sign": "符号 (皮尔士分类)",
    "symbolic-entities/sign/icon": "肖像符号 — 凭相似",
    "symbolic-entities/sign/icon/image": "图像",
    "symbolic-entities/sign/icon/diagram": "图表",
    "symbolic-entities/sign/icon/metaphor": "隐喻",
    "symbolic-entities/sign/index": "指示符号 — 凭因果联系",
    "symbolic-entities/sign/index/symptom": "症候",
    "symbolic-entities/sign/index/trace": "痕迹",
    "symbolic-entities/sign/index/pointer": "指针",
    "symbolic-entities/sign/symbol-conventional": "象征符号 — 凭约定",
    "symbolic-entities/sign/symbol-conventional/word": "词",
    "symbolic-entities/sign/symbol-conventional/numeral": "数字",
    "symbolic-entities/sign/symbol-conventional/logical-operator": "逻辑算子",
    "symbolic-entities/symbol": "象征",
    "symbolic-entities/symbol/linguistic": "语言象征",
    "symbolic-entities/symbol/linguistic/phoneme": "音素",
    "symbolic-entities/symbol/linguistic/morpheme": "语素",
    "symbolic-entities/symbol/linguistic/lexeme": "词位",
    "symbolic-entities/symbol/mathematical": "数学象征",
    "symbolic-entities/symbol/logical": "逻辑象征",
    "symbolic-entities/symbol/iconographic": "图像志象征",
    "symbolic-entities/data": "数据",
    "symbolic-entities/data/structured": "结构化数据",
    "symbolic-entities/data/structured/tabular": "表格型",
    "symbolic-entities/data/structured/relational": "关系型",
    "symbolic-entities/data/semi-structured": "半结构化数据",
    "symbolic-entities/data/semi-structured/serialized": "JSON / XML / YAML",
    "symbolic-entities/data/unstructured": "非结构化数据",
    "symbolic-entities/data/unstructured/text": "文本",
    "symbolic-entities/data/unstructured/image": "图像",
    "symbolic-entities/data/unstructured/audio": "音频",
    "symbolic-entities/data/unstructured/video": "视频",
    "symbolic-entities/data/quantitative": "定量数据",
    "symbolic-entities/data/qualitative": "定性数据",
    "symbolic-entities/code": "代码",
    "symbolic-entities/code/natural-language": "自然语言代码",
    "symbolic-entities/code/formal-language": "形式语言代码",
    "symbolic-entities/code/computer": "计算机代码",
    "symbolic-entities/code/cryptographic": "密码学代码",
    "symbolic-entities/inscription": "铭刻",
    "symbolic-entities/inscription/oral": "口传",
    "symbolic-entities/inscription/manuscript": "手稿",
    "symbolic-entities/inscription/print": "印刷",
    "symbolic-entities/inscription/digital": "数字",
    # --- semantic-contents -----------------------------------------------
    "semantic-contents": "语义内容",
    "semantic-contents/concept": "概念 (taṣawwur)",
    "semantic-contents/concept/simple": "简单概念",
    "semantic-contents/concept/compound": "复合概念",
    "semantic-contents/concept/empirical": "经验概念",
    "semantic-contents/concept/empirical/observational": "观察性",
    "semantic-contents/concept/empirical/experimental": "实验性",
    "semantic-contents/concept/a-priori": "先验概念",
    "semantic-contents/concept/a-priori/logical": "逻辑性",
    "semantic-contents/concept/a-priori/mathematical": "数学性",
    "semantic-contents/concept/concrete": "具体概念",
    "semantic-contents/concept/abstract": "抽象概念",
    "semantic-contents/idea": "观念",
    "semantic-contents/idea/innate": "天赋观念 (笛卡尔)",
    "semantic-contents/idea/adventitious": "外来观念",
    "semantic-contents/idea/constructed": "构造观念",
    "semantic-contents/idea/clear-distinct": "清楚明白的观念",
    "semantic-contents/proposition": "命题 (qaḍiyyah)",
    "semantic-contents/proposition/categorical": "直言命题",
    "semantic-contents/proposition/categorical/universal-affirmative": "全称肯定",
    "semantic-contents/proposition/categorical/universal-negative": "全称否定",
    "semantic-contents/proposition/categorical/particular-affirmative": "特称肯定",
    "semantic-contents/proposition/categorical/particular-negative": "特称否定",
    "semantic-contents/proposition/hypothetical": "假言命题",
    "semantic-contents/proposition/hypothetical/conjunctive": "合取 (muttaṣilah)",
    "semantic-contents/proposition/hypothetical/disjunctive": "析取 (munfaṣilah)",
    "semantic-contents/proposition/modal": "模态命题",
    "semantic-contents/proposition/modal/necessary": "必然",
    "semantic-contents/proposition/modal/possible": "可能",
    "semantic-contents/proposition/modal/impossible": "不可能",
    "semantic-contents/information": "信息 (DIKW T2)",
    "semantic-contents/information/syntactic": "句法信息",
    "semantic-contents/information/semantic": "语义信息",
    "semantic-contents/information/pragmatic": "语用信息",
    "semantic-contents/fact": "事实 (wāqiʿah)",
    "semantic-contents/fact/empirical": "经验事实",
    "semantic-contents/fact/mathematical": "数学事实",
    "semantic-contents/fact/logical": "逻辑事实",
    "semantic-contents/fact/historical": "历史事实",
    "semantic-contents/fact/moral": "道德事实",
    "semantic-contents/meaning": "意义 (maʿnā)",
    "semantic-contents/meaning/sense-vs-reference": "涵义与指称 (弗雷格)",
    "semantic-contents/meaning/connotation-vs-denotation": "内涵与外延",
    "semantic-contents/meaning/literal-vs-figurative": "字面与比喻",
    "semantic-contents/definition": "定义 (ḥadd)",
    "semantic-contents/definition/real": "实质定义",
    "semantic-contents/definition/nominal": "名义定义",
    "semantic-contents/definition/genus-differentia": "属差定义",
    "semantic-contents/definition/ostensive": "实指定义",
    # --- epistemic-states ------------------------------------------------
    "epistemic-states": "认知状态",
    "epistemic-states/compound-ignorance": "复合无知",
    "epistemic-states/simple-ignorance": "简单无知",
    "epistemic-states/illusion": "幻觉 (wahm)",
    "epistemic-states/illusion/perceptual": "知觉幻觉",
    "epistemic-states/illusion/cognitive": "认知幻觉",
    "epistemic-states/doubt": "怀疑 (shakk)",
    "epistemic-states/doubt/methodological": "方法论怀疑",
    "epistemic-states/doubt/habitual": "习惯性怀疑",
    "epistemic-states/doubt/equipoised": "两端均衡怀疑",
    "epistemic-states/opinion": "意见 (ẓann)",
    "epistemic-states/opinion/probable": "概然意见",
    "epistemic-states/opinion/well-grounded": "有充分根据的意见",
    "epistemic-states/opinion/dispositional": "倾向性意见",
    "epistemic-states/belief": "信念 (iʿtiqād / taṣdīq)",
    "epistemic-states/belief/occurrent": "现行信念",
    "epistemic-states/belief/dispositional": "倾向性信念",
    "epistemic-states/belief/faith": "信仰 (īmān)",
    "epistemic-states/knowledge": "知识 (ʿilm / maʿrifah)",
    "epistemic-states/knowledge/by-mode": "按表征方式",
    "epistemic-states/knowledge/by-mode/acquired": "获得知 (al-ʿilm al-ḥuṣūlī)",
    "epistemic-states/knowledge/by-mode/presential": "在场知 (al-ʿilm al-ḥuḍūrī)",
    "epistemic-states/knowledge/by-content": "按内容类型",
    "epistemic-states/knowledge/by-content/propositional": "命题性 (knowledge-that)",
    "epistemic-states/knowledge/by-content/propositional/a-priori-analytic": "先验 — 分析",
    "epistemic-states/knowledge/by-content/propositional/a-priori-synthetic": "先验 — 综合",
    "epistemic-states/knowledge/by-content/propositional/a-posteriori-empirical": "后验 — 经验",
    "epistemic-states/knowledge/by-content/propositional/a-posteriori-testimonial": "后验 — 证言",
    "epistemic-states/knowledge/by-content/procedural": "程序性 (knowledge-how)",
    "epistemic-states/knowledge/by-content/procedural/motor": "运动技能",
    "epistemic-states/knowledge/by-content/procedural/cognitive": "认知技能",
    "epistemic-states/knowledge/by-content/procedural/social": "社交技能",
    "epistemic-states/knowledge/by-content/acquaintance": "亲知 (knowledge-of)",
    "epistemic-states/knowledge/by-content/acquaintance/direct-experience": "凭直接经验",
    "epistemic-states/knowledge/by-content/acquaintance/memory": "凭记忆",
    "epistemic-states/knowledge/by-content/tacit": "默会知识 (波兰尼)",
    "epistemic-states/knowledge/by-source": "按来源",
    "epistemic-states/knowledge/by-source/sensory": "感觉知识",
    "epistemic-states/knowledge/by-source/rational": "理性知识",
    "epistemic-states/knowledge/by-source/testimonial": "证言知识",
    "epistemic-states/knowledge/by-source/revelatory": "启示知识",
    "epistemic-states/certainty": "确定性 (yaqīn)",
    "epistemic-states/certainty/logical": "逻辑确定性",
    "epistemic-states/certainty/mathematical": "数学确定性",
    "epistemic-states/certainty/metaphysical": "形而上学确定性",
    "epistemic-states/certainty/moral": "道德确定性",
    "epistemic-states/certainty/religious": "宗教确定性",
    "epistemic-states/certainty/religious/ilm-al-yaqin": "ʿIlm al-yaqīn — 确信之知",
    "epistemic-states/certainty/religious/ayn-al-yaqin": "ʿAyn al-yaqīn — 确信之眼",
    "epistemic-states/certainty/religious/haqq-al-yaqin": "Ḥaqq al-yaqīn — 确信之真",
    # --- higher-order-constructs -----------------------------------------
    "higher-order-constructs": "高阶建构",
    "higher-order-constructs/hypothesis": "假设 (faraḍiyyah)",
    "higher-order-constructs/hypothesis/working": "工作假设",
    "higher-order-constructs/hypothesis/statistical": "统计假设",
    "higher-order-constructs/hypothesis/statistical/null": "零假设",
    "higher-order-constructs/hypothesis/statistical/alternative": "备择假设",
    "higher-order-constructs/hypothesis/causal": "因果假设",
    "higher-order-constructs/theory": "理论 (naẓariyyah)",
    "higher-order-constructs/theory/empirical": "经验理论",
    "higher-order-constructs/theory/empirical/descriptive": "描述性",
    "higher-order-constructs/theory/empirical/explanatory": "解释性",
    "higher-order-constructs/theory/empirical/predictive": "预测性",
    "higher-order-constructs/theory/formal": "形式理论",
    "higher-order-constructs/theory/normative": "规范理论",
    "higher-order-constructs/model": "模型 (namūdhaj)",
    "higher-order-constructs/model/physical": "物理模型",
    "higher-order-constructs/model/mathematical": "数学模型",
    "higher-order-constructs/model/computational": "计算模型",
    "higher-order-constructs/model/conceptual": "概念模型",
    "higher-order-constructs/law": "定律 (qānūn)",
    "higher-order-constructs/law/natural": "自然律",
    "higher-order-constructs/law/natural/universal": "普遍律",
    "higher-order-constructs/law/natural/statistical": "统计律",
    "higher-order-constructs/law/logical": "逻辑律",
    "higher-order-constructs/law/logical/identity": "同一律",
    "higher-order-constructs/law/logical/non-contradiction": "矛盾律",
    "higher-order-constructs/law/logical/excluded-middle": "排中律",
    "higher-order-constructs/law/divine": "神圣法 (sharīʿah)",
    "higher-order-constructs/law/positive": "实定法",
    "higher-order-constructs/doctrine": "教义 (madhhab)",
    "higher-order-constructs/doctrine/religious": "宗教教义",
    "higher-order-constructs/doctrine/philosophical": "哲学教义",
    "higher-order-constructs/doctrine/scientific": "科学教义",
    "higher-order-constructs/insight": "洞见 (baṣīrah)",
    "higher-order-constructs/insight/aesthetic": "审美洞见",
    "higher-order-constructs/insight/mystical": "神秘洞见",
    "higher-order-constructs/insight/scientific": "科学洞见",
    "higher-order-constructs/wisdom": "智慧 (ḥikmah)",
    "higher-order-constructs/wisdom/theoretical": "理论智慧 (sophia)",
    "higher-order-constructs/wisdom/practical": "实践智慧 (phronēsis)",
    "higher-order-constructs/wisdom/productive-craft": "技艺 (technē)",
    "higher-order-constructs/wisdom/spiritual": "灵性智慧",
    "higher-order-constructs/worldview": "世界观 (ruʾyah kawniyyah)",
    "higher-order-constructs/worldview/religious": "宗教世界观",
    "higher-order-constructs/worldview/secular": "世俗世界观",
    "higher-order-constructs/worldview/syncretic": "融合世界观",
    # --- perception ------------------------------------------------------
    "perception": "知觉 / 感觉",
    "perception/external": "外部知觉",
    "perception/internal": "内部知觉",
    "perception/self": "自我知觉",
    "perception/extraordinary": "超凡知觉",
    # --- inference -------------------------------------------------------
    "inference": "推论 / 理性",
    "inference/deductive": "演绎推论",
    "inference/inductive": "归纳推论",
    "inference/abductive": "溯因推论",
    "inference/necessary": "必然理性",
    "inference/speculative": "思辨理性",
    # --- testimony -------------------------------------------------------
    "testimony": "证言",
    "testimony/direct-witness": "直接见证证言",
    "testimony/reported": "转述证言",
    "testimony/authoritative": "权威证言",
    "testimony/scriptural": "经典证言",
    # --- mass-transmission -----------------------------------------------
    "mass-transmission": "众传 (al-tawatur)",
    "mass-transmission/verbal": "言语众传",
    "mass-transmission/meaning": "意义众传",
    "mass-transmission/practical": "实践众传",
    # --- comparison ------------------------------------------------------
    "comparison": "比较 / 类比",
    "comparison/ratio-legis": "凭法理类比",
    "comparison/indication": "凭指示类比",
    "comparison/resemblance": "凭相似类比",
    "comparison/a-fortiori": "举重明轻类比",
    # --- postulation -----------------------------------------------------
    "postulation": "假设 / IBE",
    "postulation/from-perceived": "从所知觉的事实",
    "postulation/from-heard": "从所听闻的事实",
    "postulation/ibe": "最佳解释推论",
    # --- non-apprehension ------------------------------------------------
    "non-apprehension": "非把握",
    "non-apprehension/prior": "先在缺失",
    "non-apprehension/posterior": "后在缺失",
    "non-apprehension/mutual": "相互缺失",
    "non-apprehension/absolute": "绝对缺失",
    # --- memory ----------------------------------------------------------
    "memory": "记忆",
    "memory/recollection": "回忆",
    "memory/recognition": "再认",
    "memory/episodic": "情景记忆",
    "memory/semantic": "语义记忆",
    # --- innate-disposition ----------------------------------------------
    "innate-disposition": "本性 / 直觉",
    "innate-disposition/primordial": "原初本性 (逊尼派)",
    "innate-disposition/first-principles": "第一原理直觉",
    "innate-disposition/moral": "本有道德知识",
    "innate-disposition/axioms": "自明公理",
    # --- inspiration -----------------------------------------------------
    "inspiration": "灵感 / 神秘把握",
    "inspiration/ilham": "Ilhām (灵感)",
    "inspiration/kashf": "Kashf (启示)",
    "inspiration/dream-vision": "真梦境",
    # --- revelation ------------------------------------------------------
    "revelation": "启示",
    "revelation/recited": "诵读启示 (古兰经)",
    "revelation/non-recited": "非诵读启示 (圣行)",
    "revelation/modes-of-receiving": "接受启示的方式",
    # --- unclassifiable --------------------------------------------------
    "unclassifiable": "不可分类",
}

RU = {
    "epistemic-content": "Эпистемическое содержание",
    # --- sensory-inputs --------------------------------------------------
    "sensory-inputs": "Сенсорные входы",
    "sensory-inputs/signal": "Сигнал",
    "sensory-inputs/signal/physical": "Физический сигнал",
    "sensory-inputs/signal/physical/electromagnetic": "Электромагнитный",
    "sensory-inputs/signal/physical/acoustic": "Акустический",
    "sensory-inputs/signal/physical/mechanical": "Механический",
    "sensory-inputs/signal/physical/chemical": "Химический",
    "sensory-inputs/signal/biological": "Биологический сигнал",
    "sensory-inputs/signal/biological/neural": "Нейронный",
    "sensory-inputs/signal/biological/hormonal": "Гормональный",
    "sensory-inputs/signal/biological/bioelectric": "Биоэлектрический",
    "sensory-inputs/stimulus": "Стимул",
    "sensory-inputs/stimulus/distal": "Дистальный стимул",
    "sensory-inputs/stimulus/proximal": "Проксимальный стимул",
    "sensory-inputs/stimulus/conditioned": "Условный стимул",
    "sensory-inputs/stimulus/unconditioned": "Безусловный стимул",
    "sensory-inputs/sense-datum": "Чувственное данное",
    "sensory-inputs/sense-datum/visual": "Зрительные квалиа",
    "sensory-inputs/sense-datum/auditory": "Слуховые квалиа",
    "sensory-inputs/sense-datum/tactile": "Тактильные квалиа",
    "sensory-inputs/sense-datum/olfactory": "Обонятельные квалиа",
    "sensory-inputs/sense-datum/gustatory": "Вкусовые квалиа",
    "sensory-inputs/sense-datum/proprioceptive": "Проприоцептивные квалиа",
    "sensory-inputs/percept": "Перцепт",
    "sensory-inputs/percept/indeterminate": "Неопределённый перцепт (nirvikalpa)",
    "sensory-inputs/percept/indeterminate/pure-sensation": "Чистое ощущение",
    "sensory-inputs/percept/determinate": "Определённый перцепт (savikalpa)",
    "sensory-inputs/percept/determinate/object-recognition": "Распознавание объекта",
    "sensory-inputs/percept/determinate/categorized": "Категоризованное восприятие",
    "sensory-inputs/percept/extraordinary": "Необыкновенное восприятие (alaukika)",
    "sensory-inputs/percept/extraordinary/generic": "Родовое (sāmānyalakṣaṇa)",
    "sensory-inputs/percept/extraordinary/acquired": "Приобретённое (jñānalakṣaṇa)",
    "sensory-inputs/percept/extraordinary/yogic": "Йогическое (yogaja)",
    # --- symbolic-entities -----------------------------------------------
    "symbolic-entities": "Символические сущности",
    "symbolic-entities/sign": "Знак (классификация Пирса)",
    "symbolic-entities/sign/icon": "Икона — по сходству",
    "symbolic-entities/sign/icon/image": "Образ",
    "symbolic-entities/sign/icon/diagram": "Диаграмма",
    "symbolic-entities/sign/icon/metaphor": "Метафора",
    "symbolic-entities/sign/index": "Индекс — по причинной связи",
    "symbolic-entities/sign/index/symptom": "Симптом",
    "symbolic-entities/sign/index/trace": "След",
    "symbolic-entities/sign/index/pointer": "Указатель",
    "symbolic-entities/sign/symbol-conventional": "Символ — по конвенции",
    "symbolic-entities/sign/symbol-conventional/word": "Слово",
    "symbolic-entities/sign/symbol-conventional/numeral": "Цифра",
    "symbolic-entities/sign/symbol-conventional/logical-operator": "Логический оператор",
    "symbolic-entities/symbol": "Символ",
    "symbolic-entities/symbol/linguistic": "Лингвистический символ",
    "symbolic-entities/symbol/linguistic/phoneme": "Фонема",
    "symbolic-entities/symbol/linguistic/morpheme": "Морфема",
    "symbolic-entities/symbol/linguistic/lexeme": "Лексема",
    "symbolic-entities/symbol/mathematical": "Математический символ",
    "symbolic-entities/symbol/logical": "Логический символ",
    "symbolic-entities/symbol/iconographic": "Иконографический символ",
    "symbolic-entities/data": "Данные",
    "symbolic-entities/data/structured": "Структурированные данные",
    "symbolic-entities/data/structured/tabular": "Табличные",
    "symbolic-entities/data/structured/relational": "Реляционные",
    "symbolic-entities/data/semi-structured": "Полуструктурированные данные",
    "symbolic-entities/data/semi-structured/serialized": "JSON / XML / YAML",
    "symbolic-entities/data/unstructured": "Неструктурированные данные",
    "symbolic-entities/data/unstructured/text": "Текст",
    "symbolic-entities/data/unstructured/image": "Изображение",
    "symbolic-entities/data/unstructured/audio": "Аудио",
    "symbolic-entities/data/unstructured/video": "Видео",
    "symbolic-entities/data/quantitative": "Количественные данные",
    "symbolic-entities/data/qualitative": "Качественные данные",
    "symbolic-entities/code": "Код",
    "symbolic-entities/code/natural-language": "Код естественного языка",
    "symbolic-entities/code/formal-language": "Код формального языка",
    "symbolic-entities/code/computer": "Компьютерный код",
    "symbolic-entities/code/cryptographic": "Криптографический код",
    "symbolic-entities/inscription": "Запись",
    "symbolic-entities/inscription/oral": "Устная",
    "symbolic-entities/inscription/manuscript": "Рукописная",
    "symbolic-entities/inscription/print": "Печатная",
    "symbolic-entities/inscription/digital": "Цифровая",
    # --- semantic-contents -----------------------------------------------
    "semantic-contents": "Семантические содержания",
    "semantic-contents/concept": "Понятие (taṣawwur)",
    "semantic-contents/concept/simple": "Простое понятие",
    "semantic-contents/concept/compound": "Составное понятие",
    "semantic-contents/concept/empirical": "Эмпирическое понятие",
    "semantic-contents/concept/empirical/observational": "Наблюдательное",
    "semantic-contents/concept/empirical/experimental": "Экспериментальное",
    "semantic-contents/concept/a-priori": "Априорное понятие",
    "semantic-contents/concept/a-priori/logical": "Логическое",
    "semantic-contents/concept/a-priori/mathematical": "Математическое",
    "semantic-contents/concept/concrete": "Конкретное понятие",
    "semantic-contents/concept/abstract": "Абстрактное понятие",
    "semantic-contents/idea": "Идея",
    "semantic-contents/idea/innate": "Врождённая идея (Декарт)",
    "semantic-contents/idea/adventitious": "Привходящая идея",
    "semantic-contents/idea/constructed": "Сконструированная идея",
    "semantic-contents/idea/clear-distinct": "Ясная и отчётливая идея",
    "semantic-contents/proposition": "Суждение (qaḍiyyah)",
    "semantic-contents/proposition/categorical": "Категорическое суждение",
    "semantic-contents/proposition/categorical/universal-affirmative": "Общеутвердительное",
    "semantic-contents/proposition/categorical/universal-negative": "Общеотрицательное",
    "semantic-contents/proposition/categorical/particular-affirmative": "Частноутвердительное",
    "semantic-contents/proposition/categorical/particular-negative": "Частноотрицательное",
    "semantic-contents/proposition/hypothetical": "Гипотетическое суждение",
    "semantic-contents/proposition/hypothetical/conjunctive": "Конъюнктивное (muttaṣilah)",
    "semantic-contents/proposition/hypothetical/disjunctive": "Дизъюнктивное (munfaṣilah)",
    "semantic-contents/proposition/modal": "Модальное суждение",
    "semantic-contents/proposition/modal/necessary": "Необходимое",
    "semantic-contents/proposition/modal/possible": "Возможное",
    "semantic-contents/proposition/modal/impossible": "Невозможное",
    "semantic-contents/information": "Информация (DIKW T2)",
    "semantic-contents/information/syntactic": "Синтаксическая информация",
    "semantic-contents/information/semantic": "Семантическая информация",
    "semantic-contents/information/pragmatic": "Прагматическая информация",
    "semantic-contents/fact": "Факт (wāqiʿah)",
    "semantic-contents/fact/empirical": "Эмпирический факт",
    "semantic-contents/fact/mathematical": "Математический факт",
    "semantic-contents/fact/logical": "Логический факт",
    "semantic-contents/fact/historical": "Исторический факт",
    "semantic-contents/fact/moral": "Моральный факт",
    "semantic-contents/meaning": "Значение (maʿnā)",
    "semantic-contents/meaning/sense-vs-reference": "Смысл и значение (Фреге)",
    "semantic-contents/meaning/connotation-vs-denotation": "Коннотация и денотация",
    "semantic-contents/meaning/literal-vs-figurative": "Буквальное и переносное",
    "semantic-contents/definition": "Определение (ḥadd)",
    "semantic-contents/definition/real": "Реальное определение",
    "semantic-contents/definition/nominal": "Номинальное определение",
    "semantic-contents/definition/genus-differentia": "Через род и видовое отличие",
    "semantic-contents/definition/ostensive": "Остенсивное определение",
    # --- epistemic-states ------------------------------------------------
    "epistemic-states": "Эпистемические состояния",
    "epistemic-states/compound-ignorance": "Сложное неведение",
    "epistemic-states/simple-ignorance": "Простое неведение",
    "epistemic-states/illusion": "Иллюзия (wahm)",
    "epistemic-states/illusion/perceptual": "Перцептивная иллюзия",
    "epistemic-states/illusion/cognitive": "Когнитивная иллюзия",
    "epistemic-states/doubt": "Сомнение (shakk)",
    "epistemic-states/doubt/methodological": "Методологическое сомнение",
    "epistemic-states/doubt/habitual": "Привычное сомнение",
    "epistemic-states/doubt/equipoised": "Равновесное сомнение",
    "epistemic-states/opinion": "Мнение (ẓann)",
    "epistemic-states/opinion/probable": "Вероятное мнение",
    "epistemic-states/opinion/well-grounded": "Хорошо обоснованное мнение",
    "epistemic-states/opinion/dispositional": "Диспозициональное мнение",
    "epistemic-states/belief": "Вера / убеждение (iʿtiqād / taṣdīq)",
    "epistemic-states/belief/occurrent": "Актуальное убеждение",
    "epistemic-states/belief/dispositional": "Диспозициональное убеждение",
    "epistemic-states/belief/faith": "Религиозная вера (īmān)",
    "epistemic-states/knowledge": "Знание (ʿilm / maʿrifah)",
    "epistemic-states/knowledge/by-mode": "По способу представления",
    "epistemic-states/knowledge/by-mode/acquired": "Приобретённое (al-ʿilm al-ḥuṣūlī)",
    "epistemic-states/knowledge/by-mode/presential": "Презентное (al-ʿilm al-ḥuḍūrī)",
    "epistemic-states/knowledge/by-content": "По типу содержания",
    "epistemic-states/knowledge/by-content/propositional": "Пропозициональное (knowledge-that)",
    "epistemic-states/knowledge/by-content/propositional/a-priori-analytic": "Априорное — аналитическое",
    "epistemic-states/knowledge/by-content/propositional/a-priori-synthetic": "Априорное — синтетическое",
    "epistemic-states/knowledge/by-content/propositional/a-posteriori-empirical": "Апостериорное — эмпирическое",
    "epistemic-states/knowledge/by-content/propositional/a-posteriori-testimonial": "Апостериорное — свидетельское",
    "epistemic-states/knowledge/by-content/procedural": "Процедурное (knowledge-how)",
    "epistemic-states/knowledge/by-content/procedural/motor": "Двигательный навык",
    "epistemic-states/knowledge/by-content/procedural/cognitive": "Когнитивный навык",
    "epistemic-states/knowledge/by-content/procedural/social": "Социальный навык",
    "epistemic-states/knowledge/by-content/acquaintance": "Знание-знакомство (knowledge-of)",
    "epistemic-states/knowledge/by-content/acquaintance/direct-experience": "Через прямой опыт",
    "epistemic-states/knowledge/by-content/acquaintance/memory": "Через память",
    "epistemic-states/knowledge/by-content/tacit": "Неявное знание (Полани)",
    "epistemic-states/knowledge/by-source": "По источнику",
    "epistemic-states/knowledge/by-source/sensory": "Чувственное знание",
    "epistemic-states/knowledge/by-source/rational": "Рациональное знание",
    "epistemic-states/knowledge/by-source/testimonial": "Свидетельское знание",
    "epistemic-states/knowledge/by-source/revelatory": "Откровенное знание",
    "epistemic-states/certainty": "Достоверность (yaqīn)",
    "epistemic-states/certainty/logical": "Логическая достоверность",
    "epistemic-states/certainty/mathematical": "Математическая достоверность",
    "epistemic-states/certainty/metaphysical": "Метафизическая достоверность",
    "epistemic-states/certainty/moral": "Моральная достоверность",
    "epistemic-states/certainty/religious": "Религиозная достоверность",
    "epistemic-states/certainty/religious/ilm-al-yaqin": "ʿIlm al-yaqīn — знание достоверности",
    "epistemic-states/certainty/religious/ayn-al-yaqin": "ʿAyn al-yaqīn — око достоверности",
    "epistemic-states/certainty/religious/haqq-al-yaqin": "Ḥaqq al-yaqīn — истина достоверности",
    # --- higher-order-constructs -----------------------------------------
    "higher-order-constructs": "Конструкты высшего порядка",
    "higher-order-constructs/hypothesis": "Гипотеза (faraḍiyyah)",
    "higher-order-constructs/hypothesis/working": "Рабочая гипотеза",
    "higher-order-constructs/hypothesis/statistical": "Статистическая гипотеза",
    "higher-order-constructs/hypothesis/statistical/null": "Нулевая гипотеза",
    "higher-order-constructs/hypothesis/statistical/alternative": "Альтернативная гипотеза",
    "higher-order-constructs/hypothesis/causal": "Причинная гипотеза",
    "higher-order-constructs/theory": "Теория (naẓariyyah)",
    "higher-order-constructs/theory/empirical": "Эмпирическая теория",
    "higher-order-constructs/theory/empirical/descriptive": "Дескриптивная",
    "higher-order-constructs/theory/empirical/explanatory": "Объяснительная",
    "higher-order-constructs/theory/empirical/predictive": "Предсказательная",
    "higher-order-constructs/theory/formal": "Формальная теория",
    "higher-order-constructs/theory/normative": "Нормативная теория",
    "higher-order-constructs/model": "Модель (namūdhaj)",
    "higher-order-constructs/model/physical": "Физическая модель",
    "higher-order-constructs/model/mathematical": "Математическая модель",
    "higher-order-constructs/model/computational": "Вычислительная модель",
    "higher-order-constructs/model/conceptual": "Концептуальная модель",
    "higher-order-constructs/law": "Закон (qānūn)",
    "higher-order-constructs/law/natural": "Закон природы",
    "higher-order-constructs/law/natural/universal": "Универсальный закон",
    "higher-order-constructs/law/natural/statistical": "Статистический закон",
    "higher-order-constructs/law/logical": "Логический закон",
    "higher-order-constructs/law/logical/identity": "Тождество",
    "higher-order-constructs/law/logical/non-contradiction": "Непротиворечие",
    "higher-order-constructs/law/logical/excluded-middle": "Исключённое третье",
    "higher-order-constructs/law/divine": "Божественный закон (sharīʿah)",
    "higher-order-constructs/law/positive": "Позитивный закон",
    "higher-order-constructs/doctrine": "Доктрина (madhhab)",
    "higher-order-constructs/doctrine/religious": "Религиозная доктрина",
    "higher-order-constructs/doctrine/philosophical": "Философская доктрина",
    "higher-order-constructs/doctrine/scientific": "Научная доктрина",
    "higher-order-constructs/insight": "Прозрение (baṣīrah)",
    "higher-order-constructs/insight/aesthetic": "Эстетическое прозрение",
    "higher-order-constructs/insight/mystical": "Мистическое прозрение",
    "higher-order-constructs/insight/scientific": "Научное прозрение",
    "higher-order-constructs/wisdom": "Мудрость (ḥikmah)",
    "higher-order-constructs/wisdom/theoretical": "Теоретическая мудрость (sophia)",
    "higher-order-constructs/wisdom/practical": "Практическая мудрость (phronēsis)",
    "higher-order-constructs/wisdom/productive-craft": "Творческое искусство (technē)",
    "higher-order-constructs/wisdom/spiritual": "Духовная мудрость",
    "higher-order-constructs/worldview": "Мировоззрение (ruʾyah kawniyyah)",
    "higher-order-constructs/worldview/religious": "Религиозное мировоззрение",
    "higher-order-constructs/worldview/secular": "Светское мировоззрение",
    "higher-order-constructs/worldview/syncretic": "Синкретическое мировоззрение",
    # --- perception ------------------------------------------------------
    "perception": "Восприятие / Ощущение",
    "perception/external": "Внешнее восприятие",
    "perception/internal": "Внутреннее восприятие",
    "perception/self": "Самовосприятие",
    "perception/extraordinary": "Необыкновенное восприятие",
    # --- inference -------------------------------------------------------
    "inference": "Умозаключение / Разум",
    "inference/deductive": "Дедуктивное умозаключение",
    "inference/inductive": "Индуктивное умозаключение",
    "inference/abductive": "Абдуктивное умозаключение",
    "inference/necessary": "Необходимый разум",
    "inference/speculative": "Спекулятивный разум",
    # --- testimony -------------------------------------------------------
    "testimony": "Свидетельство",
    "testimony/direct-witness": "Прямое свидетельство очевидца",
    "testimony/reported": "Передаваемое свидетельство",
    "testimony/authoritative": "Авторитетное свидетельство",
    "testimony/scriptural": "Священное свидетельство",
    # --- mass-transmission -----------------------------------------------
    "mass-transmission": "Массовая передача (al-tawatur)",
    "mass-transmission/verbal": "Словесная массовая передача",
    "mass-transmission/meaning": "Смысловая массовая передача",
    "mass-transmission/practical": "Практическая массовая передача",
    # --- comparison ------------------------------------------------------
    "comparison": "Сравнение / Аналогия",
    "comparison/ratio-legis": "Аналогия по ratio legis",
    "comparison/indication": "Аналогия по указанию",
    "comparison/resemblance": "Аналогия по сходству",
    "comparison/a-fortiori": "Аналогия a fortiori",
    # --- postulation -----------------------------------------------------
    "postulation": "Постулирование / IBE",
    "postulation/from-perceived": "От воспринятого факта",
    "postulation/from-heard": "От услышанного факта",
    "postulation/ibe": "Вывод к лучшему объяснению",
    # --- non-apprehension ------------------------------------------------
    "non-apprehension": "Неуловление",
    "non-apprehension/prior": "Предшествующее отсутствие",
    "non-apprehension/posterior": "Последующее отсутствие",
    "non-apprehension/mutual": "Взаимное отсутствие",
    "non-apprehension/absolute": "Абсолютное отсутствие",
    # --- memory ----------------------------------------------------------
    "memory": "Память",
    "memory/recollection": "Воспоминание",
    "memory/recognition": "Узнавание",
    "memory/episodic": "Эпизодическая память",
    "memory/semantic": "Семантическая память",
    # --- innate-disposition ----------------------------------------------
    "innate-disposition": "Врождённая предрасположенность / Интуиция",
    "innate-disposition/primordial": "Изначальная предрасположенность (суннизм)",
    "innate-disposition/first-principles": "Интуиция первоначал",
    "innate-disposition/moral": "Врождённое моральное знание",
    "innate-disposition/axioms": "Самоочевидные аксиомы",
    # --- inspiration -----------------------------------------------------
    "inspiration": "Вдохновение / Мистическое постижение",
    "inspiration/ilham": "Ilhām (вдохновение)",
    "inspiration/kashf": "Kashf (раскрытие)",
    "inspiration/dream-vision": "Истинное сновидение",
    # --- revelation ------------------------------------------------------
    "revelation": "Откровение",
    "revelation/recited": "Возвещаемое откровение (Коран)",
    "revelation/non-recited": "Невозвещаемое откровение (Сунна)",
    "revelation/modes-of-receiving": "Способы получения откровения",
    # --- unclassifiable --------------------------------------------------
    "unclassifiable": "Неклассифицируемое",
}

TR = {
    "epistemic-content": "Epistemik içerik",
    # --- sensory-inputs --------------------------------------------------
    "sensory-inputs": "Duyusal girdiler",
    "sensory-inputs/signal": "Sinyal",
    "sensory-inputs/signal/physical": "Fiziksel sinyal",
    "sensory-inputs/signal/physical/electromagnetic": "Elektromanyetik",
    "sensory-inputs/signal/physical/acoustic": "Akustik",
    "sensory-inputs/signal/physical/mechanical": "Mekanik",
    "sensory-inputs/signal/physical/chemical": "Kimyasal",
    "sensory-inputs/signal/biological": "Biyolojik sinyal",
    "sensory-inputs/signal/biological/neural": "Sinirsel",
    "sensory-inputs/signal/biological/hormonal": "Hormonal",
    "sensory-inputs/signal/biological/bioelectric": "Biyoelektrik",
    "sensory-inputs/stimulus": "Uyaran",
    "sensory-inputs/stimulus/distal": "Uzak uyaran",
    "sensory-inputs/stimulus/proximal": "Yakın uyaran",
    "sensory-inputs/stimulus/conditioned": "Koşullu uyaran",
    "sensory-inputs/stimulus/unconditioned": "Koşulsuz uyaran",
    "sensory-inputs/sense-datum": "Duyu verisi",
    "sensory-inputs/sense-datum/visual": "Görsel qualia",
    "sensory-inputs/sense-datum/auditory": "İşitsel qualia",
    "sensory-inputs/sense-datum/tactile": "Dokunsal qualia",
    "sensory-inputs/sense-datum/olfactory": "Koku qualia",
    "sensory-inputs/sense-datum/gustatory": "Tat qualia",
    "sensory-inputs/sense-datum/proprioceptive": "Propriyoseptif qualia",
    "sensory-inputs/percept": "Algı",
    "sensory-inputs/percept/indeterminate": "Belirsiz algı (nirvikalpa)",
    "sensory-inputs/percept/indeterminate/pure-sensation": "Saf duyum",
    "sensory-inputs/percept/determinate": "Belirli algı (savikalpa)",
    "sensory-inputs/percept/determinate/object-recognition": "Nesne tanıma",
    "sensory-inputs/percept/determinate/categorized": "Kategorize edilmiş algı",
    "sensory-inputs/percept/extraordinary": "Olağanüstü algı (alaukika)",
    "sensory-inputs/percept/extraordinary/generic": "Tümel (sāmānyalakṣaṇa)",
    "sensory-inputs/percept/extraordinary/acquired": "Kazanılmış (jñānalakṣaṇa)",
    "sensory-inputs/percept/extraordinary/yogic": "Yogik (yogaja)",
    # --- symbolic-entities -----------------------------------------------
    "symbolic-entities": "Simgesel varlıklar",
    "symbolic-entities/sign": "İşaret (Peirce sınıflaması)",
    "symbolic-entities/sign/icon": "İkon — benzerlik yoluyla",
    "symbolic-entities/sign/icon/image": "İmge",
    "symbolic-entities/sign/icon/diagram": "Diyagram",
    "symbolic-entities/sign/icon/metaphor": "Metafor",
    "symbolic-entities/sign/index": "İndeks — nedensel bağ yoluyla",
    "symbolic-entities/sign/index/symptom": "Belirti",
    "symbolic-entities/sign/index/trace": "İz",
    "symbolic-entities/sign/index/pointer": "İşaretçi",
    "symbolic-entities/sign/symbol-conventional": "Sembol — uzlaşı yoluyla",
    "symbolic-entities/sign/symbol-conventional/word": "Sözcük",
    "symbolic-entities/sign/symbol-conventional/numeral": "Rakam",
    "symbolic-entities/sign/symbol-conventional/logical-operator": "Mantıksal operatör",
    "symbolic-entities/symbol": "Sembol",
    "symbolic-entities/symbol/linguistic": "Dilsel sembol",
    "symbolic-entities/symbol/linguistic/phoneme": "Sesbirim",
    "symbolic-entities/symbol/linguistic/morpheme": "Biçimbirim",
    "symbolic-entities/symbol/linguistic/lexeme": "Sözcükbirim",
    "symbolic-entities/symbol/mathematical": "Matematiksel sembol",
    "symbolic-entities/symbol/logical": "Mantıksal sembol",
    "symbolic-entities/symbol/iconographic": "İkonografik sembol",
    "symbolic-entities/data": "Veri",
    "symbolic-entities/data/structured": "Yapılandırılmış veri",
    "symbolic-entities/data/structured/tabular": "Tablo biçimi",
    "symbolic-entities/data/structured/relational": "İlişkisel",
    "symbolic-entities/data/semi-structured": "Yarı yapılandırılmış veri",
    "symbolic-entities/data/semi-structured/serialized": "JSON / XML / YAML",
    "symbolic-entities/data/unstructured": "Yapılandırılmamış veri",
    "symbolic-entities/data/unstructured/text": "Metin",
    "symbolic-entities/data/unstructured/image": "Görüntü",
    "symbolic-entities/data/unstructured/audio": "Ses",
    "symbolic-entities/data/unstructured/video": "Video",
    "symbolic-entities/data/quantitative": "Niceliksel veri",
    "symbolic-entities/data/qualitative": "Niteliksel veri",
    "symbolic-entities/code": "Kod",
    "symbolic-entities/code/natural-language": "Doğal dil kodu",
    "symbolic-entities/code/formal-language": "Biçimsel dil kodu",
    "symbolic-entities/code/computer": "Bilgisayar kodu",
    "symbolic-entities/code/cryptographic": "Kriptografik kod",
    "symbolic-entities/inscription": "Kayıt",
    "symbolic-entities/inscription/oral": "Sözlü",
    "symbolic-entities/inscription/manuscript": "El yazması",
    "symbolic-entities/inscription/print": "Basılı",
    "symbolic-entities/inscription/digital": "Dijital",
    # --- semantic-contents -----------------------------------------------
    "semantic-contents": "Anlamsal içerikler",
    "semantic-contents/concept": "Kavram (taṣawwur)",
    "semantic-contents/concept/simple": "Basit kavram",
    "semantic-contents/concept/compound": "Bileşik kavram",
    "semantic-contents/concept/empirical": "Deneyimsel kavram",
    "semantic-contents/concept/empirical/observational": "Gözlemsel",
    "semantic-contents/concept/empirical/experimental": "Deneysel",
    "semantic-contents/concept/a-priori": "A priori kavram",
    "semantic-contents/concept/a-priori/logical": "Mantıksal",
    "semantic-contents/concept/a-priori/mathematical": "Matematiksel",
    "semantic-contents/concept/concrete": "Somut kavram",
    "semantic-contents/concept/abstract": "Soyut kavram",
    "semantic-contents/idea": "Fikir",
    "semantic-contents/idea/innate": "Doğuştan fikir (Descartes)",
    "semantic-contents/idea/adventitious": "Sonradan gelen fikir",
    "semantic-contents/idea/constructed": "İnşa edilmiş fikir",
    "semantic-contents/idea/clear-distinct": "Açık ve seçik fikir",
    "semantic-contents/proposition": "Önerme (qaḍiyyah)",
    "semantic-contents/proposition/categorical": "Kategorik önerme",
    "semantic-contents/proposition/categorical/universal-affirmative": "Tümel olumlu",
    "semantic-contents/proposition/categorical/universal-negative": "Tümel olumsuz",
    "semantic-contents/proposition/categorical/particular-affirmative": "Tikel olumlu",
    "semantic-contents/proposition/categorical/particular-negative": "Tikel olumsuz",
    "semantic-contents/proposition/hypothetical": "Şartlı önerme",
    "semantic-contents/proposition/hypothetical/conjunctive": "Bitişik (muttaṣilah)",
    "semantic-contents/proposition/hypothetical/disjunctive": "Ayrık (munfaṣilah)",
    "semantic-contents/proposition/modal": "Kipsel önerme",
    "semantic-contents/proposition/modal/necessary": "Zorunlu",
    "semantic-contents/proposition/modal/possible": "Mümkün",
    "semantic-contents/proposition/modal/impossible": "İmkânsız",
    "semantic-contents/information": "Enformasyon (DIKW T2)",
    "semantic-contents/information/syntactic": "Sözdizimsel enformasyon",
    "semantic-contents/information/semantic": "Anlamsal enformasyon",
    "semantic-contents/information/pragmatic": "Pragmatik enformasyon",
    "semantic-contents/fact": "Olgu (wāqiʿah)",
    "semantic-contents/fact/empirical": "Deneyimsel olgu",
    "semantic-contents/fact/mathematical": "Matematiksel olgu",
    "semantic-contents/fact/logical": "Mantıksal olgu",
    "semantic-contents/fact/historical": "Tarihsel olgu",
    "semantic-contents/fact/moral": "Ahlaki olgu",
    "semantic-contents/meaning": "Anlam (maʿnā)",
    "semantic-contents/meaning/sense-vs-reference": "Anlam ve gönderim (Frege)",
    "semantic-contents/meaning/connotation-vs-denotation": "Çağrışım ve gösterim",
    "semantic-contents/meaning/literal-vs-figurative": "Düz anlam ve mecazi anlam",
    "semantic-contents/definition": "Tanım (ḥadd)",
    "semantic-contents/definition/real": "Gerçek tanım",
    "semantic-contents/definition/nominal": "Nominal tanım",
    "semantic-contents/definition/genus-differentia": "Cins ve ayrım",
    "semantic-contents/definition/ostensive": "Gösterimsel tanım",
    # --- epistemic-states ------------------------------------------------
    "epistemic-states": "Epistemik durumlar",
    "epistemic-states/compound-ignorance": "Bileşik cehalet",
    "epistemic-states/simple-ignorance": "Basit cehalet",
    "epistemic-states/illusion": "Yanılsama (wahm)",
    "epistemic-states/illusion/perceptual": "Algısal yanılsama",
    "epistemic-states/illusion/cognitive": "Bilişsel yanılsama",
    "epistemic-states/doubt": "Şüphe (shakk)",
    "epistemic-states/doubt/methodological": "Yöntemsel şüphe",
    "epistemic-states/doubt/habitual": "Alışkanlığa dayalı şüphe",
    "epistemic-states/doubt/equipoised": "Eşit ağırlıklı şüphe",
    "epistemic-states/opinion": "Zan (ẓann)",
    "epistemic-states/opinion/probable": "Galip zan",
    "epistemic-states/opinion/well-grounded": "İyi temellendirilmiş zan",
    "epistemic-states/opinion/dispositional": "Yatkınlığa dayalı zan",
    "epistemic-states/belief": "İnanç / tasdik (iʿtiqād / taṣdīq)",
    "epistemic-states/belief/occurrent": "Edimsel inanç",
    "epistemic-states/belief/dispositional": "Yatkınlığa dayalı inanç",
    "epistemic-states/belief/faith": "İman (īmān)",
    "epistemic-states/knowledge": "Bilgi (ʿilm / maʿrifah)",
    "epistemic-states/knowledge/by-mode": "Temsil tarzına göre",
    "epistemic-states/knowledge/by-mode/acquired": "Kazanılmış (al-ʿilm al-ḥuṣūlī)",
    "epistemic-states/knowledge/by-mode/presential": "Huzuri (al-ʿilm al-ḥuḍūrī)",
    "epistemic-states/knowledge/by-content": "İçerik türüne göre",
    "epistemic-states/knowledge/by-content/propositional": "Önermesel (knowledge-that)",
    "epistemic-states/knowledge/by-content/propositional/a-priori-analytic": "A priori — analitik",
    "epistemic-states/knowledge/by-content/propositional/a-priori-synthetic": "A priori — sentetik",
    "epistemic-states/knowledge/by-content/propositional/a-posteriori-empirical": "A posteriori — deneyimsel",
    "epistemic-states/knowledge/by-content/propositional/a-posteriori-testimonial": "A posteriori — şahitliğe dayalı",
    "epistemic-states/knowledge/by-content/procedural": "Edimsel (knowledge-how)",
    "epistemic-states/knowledge/by-content/procedural/motor": "Motor beceri",
    "epistemic-states/knowledge/by-content/procedural/cognitive": "Bilişsel beceri",
    "epistemic-states/knowledge/by-content/procedural/social": "Sosyal beceri",
    "epistemic-states/knowledge/by-content/acquaintance": "Tanışıklık (knowledge-of)",
    "epistemic-states/knowledge/by-content/acquaintance/direct-experience": "Doğrudan deneyim yoluyla",
    "epistemic-states/knowledge/by-content/acquaintance/memory": "Bellek yoluyla",
    "epistemic-states/knowledge/by-content/tacit": "Örtük bilgi (Polanyi)",
    "epistemic-states/knowledge/by-source": "Kaynağa göre",
    "epistemic-states/knowledge/by-source/sensory": "Duyusal bilgi",
    "epistemic-states/knowledge/by-source/rational": "Akli bilgi",
    "epistemic-states/knowledge/by-source/testimonial": "Şahitliğe dayalı bilgi",
    "epistemic-states/knowledge/by-source/revelatory": "Vahye dayalı bilgi",
    "epistemic-states/certainty": "Kesinlik (yaqīn)",
    "epistemic-states/certainty/logical": "Mantıksal kesinlik",
    "epistemic-states/certainty/mathematical": "Matematiksel kesinlik",
    "epistemic-states/certainty/metaphysical": "Metafiziksel kesinlik",
    "epistemic-states/certainty/moral": "Ahlaki kesinlik",
    "epistemic-states/certainty/religious": "Dini kesinlik",
    "epistemic-states/certainty/religious/ilm-al-yaqin": "ʿIlm al-yaqīn — yakîn ilmi",
    "epistemic-states/certainty/religious/ayn-al-yaqin": "ʿAyn al-yaqīn — yakîn aynı",
    "epistemic-states/certainty/religious/haqq-al-yaqin": "Ḥaqq al-yaqīn — yakîn hakikati",
    # --- higher-order-constructs -----------------------------------------
    "higher-order-constructs": "Üst düzey yapılar",
    "higher-order-constructs/hypothesis": "Hipotez (faraḍiyyah)",
    "higher-order-constructs/hypothesis/working": "Çalışma hipotezi",
    "higher-order-constructs/hypothesis/statistical": "İstatistiksel hipotez",
    "higher-order-constructs/hypothesis/statistical/null": "Sıfır hipotezi",
    "higher-order-constructs/hypothesis/statistical/alternative": "Alternatif hipotez",
    "higher-order-constructs/hypothesis/causal": "Nedensel hipotez",
    "higher-order-constructs/theory": "Kuram (naẓariyyah)",
    "higher-order-constructs/theory/empirical": "Deneyimsel kuram",
    "higher-order-constructs/theory/empirical/descriptive": "Betimsel",
    "higher-order-constructs/theory/empirical/explanatory": "Açıklayıcı",
    "higher-order-constructs/theory/empirical/predictive": "Öngörücü",
    "higher-order-constructs/theory/formal": "Biçimsel kuram",
    "higher-order-constructs/theory/normative": "Normatif kuram",
    "higher-order-constructs/model": "Model (namūdhaj)",
    "higher-order-constructs/model/physical": "Fiziksel model",
    "higher-order-constructs/model/mathematical": "Matematiksel model",
    "higher-order-constructs/model/computational": "Hesaplamalı model",
    "higher-order-constructs/model/conceptual": "Kavramsal model",
    "higher-order-constructs/law": "Yasa (qānūn)",
    "higher-order-constructs/law/natural": "Doğa yasası",
    "higher-order-constructs/law/natural/universal": "Tümel yasa",
    "higher-order-constructs/law/natural/statistical": "İstatistiksel yasa",
    "higher-order-constructs/law/logical": "Mantık yasası",
    "higher-order-constructs/law/logical/identity": "Özdeşlik",
    "higher-order-constructs/law/logical/non-contradiction": "Çelişmezlik",
    "higher-order-constructs/law/logical/excluded-middle": "Üçüncü hâlin imkânsızlığı",
    "higher-order-constructs/law/divine": "İlahi yasa (sharīʿah)",
    "higher-order-constructs/law/positive": "Pozitif hukuk",
    "higher-order-constructs/doctrine": "Doktrin (madhhab)",
    "higher-order-constructs/doctrine/religious": "Dini doktrin",
    "higher-order-constructs/doctrine/philosophical": "Felsefi doktrin",
    "higher-order-constructs/doctrine/scientific": "Bilimsel doktrin",
    "higher-order-constructs/insight": "Basiret (baṣīrah)",
    "higher-order-constructs/insight/aesthetic": "Estetik basiret",
    "higher-order-constructs/insight/mystical": "Mistik basiret",
    "higher-order-constructs/insight/scientific": "Bilimsel basiret",
    "higher-order-constructs/wisdom": "Hikmet (ḥikmah)",
    "higher-order-constructs/wisdom/theoretical": "Teorik hikmet (sophia)",
    "higher-order-constructs/wisdom/practical": "Pratik hikmet (phronēsis)",
    "higher-order-constructs/wisdom/productive-craft": "Üretken zanaat (technē)",
    "higher-order-constructs/wisdom/spiritual": "Manevi hikmet",
    "higher-order-constructs/worldview": "Dünya görüşü (ruʾyah kawniyyah)",
    "higher-order-constructs/worldview/religious": "Dini dünya görüşü",
    "higher-order-constructs/worldview/secular": "Seküler dünya görüşü",
    "higher-order-constructs/worldview/syncretic": "Sinkretik dünya görüşü",
    # --- perception ------------------------------------------------------
    "perception": "Algı / Duyum",
    "perception/external": "Dış algı",
    "perception/internal": "İç algı",
    "perception/self": "Öz algı",
    "perception/extraordinary": "Olağanüstü algı",
    # --- inference -------------------------------------------------------
    "inference": "Çıkarım / Akıl",
    "inference/deductive": "Tümdengelimsel çıkarım",
    "inference/inductive": "Tümevarımsal çıkarım",
    "inference/abductive": "Abdüktif çıkarım",
    "inference/necessary": "Zorunlu akıl",
    "inference/speculative": "Nazari akıl",
    # --- testimony -------------------------------------------------------
    "testimony": "Şahitlik",
    "testimony/direct-witness": "Doğrudan şahitlik",
    "testimony/reported": "Nakledilen şahitlik",
    "testimony/authoritative": "Otoriter şahitlik",
    "testimony/scriptural": "Nakli şahitlik",
    # --- mass-transmission -----------------------------------------------
    "mass-transmission": "Tevatür (al-tawatur)",
    "mass-transmission/verbal": "Lafzi tevatür",
    "mass-transmission/meaning": "Manevi tevatür",
    "mass-transmission/practical": "Ameli tevatür",
    # --- comparison ------------------------------------------------------
    "comparison": "Kıyas / Analoji",
    "comparison/ratio-legis": "İllet kıyası",
    "comparison/indication": "Delalet kıyası",
    "comparison/resemblance": "Şebeh kıyası",
    "comparison/a-fortiori": "Evla kıyas",
    # --- postulation -----------------------------------------------------
    "postulation": "Varsayım / IBE",
    "postulation/from-perceived": "Algılanan olgudan",
    "postulation/from-heard": "İşitilen olgudan",
    "postulation/ibe": "En iyi açıklamaya çıkarım",
    # --- non-apprehension ------------------------------------------------
    "non-apprehension": "Kavrayışsızlık",
    "non-apprehension/prior": "Önceki yokluk",
    "non-apprehension/posterior": "Sonraki yokluk",
    "non-apprehension/mutual": "Karşılıklı yokluk",
    "non-apprehension/absolute": "Mutlak yokluk",
    # --- memory ----------------------------------------------------------
    "memory": "Bellek",
    "memory/recollection": "Hatırlama",
    "memory/recognition": "Tanıma",
    "memory/episodic": "Olaysal bellek",
    "memory/semantic": "Anlamsal bellek",
    # --- innate-disposition ----------------------------------------------
    "innate-disposition": "Doğuştan yatkınlık / Sezgi",
    "innate-disposition/primordial": "Fıtri yatkınlık (Sünni)",
    "innate-disposition/first-principles": "İlk ilkelerin sezgisi",
    "innate-disposition/moral": "Doğuştan ahlaki bilgi",
    "innate-disposition/axioms": "Apaçık aksiyomlar",
    # --- inspiration -----------------------------------------------------
    "inspiration": "İlham / Mistik kavrayış",
    "inspiration/ilham": "Ilhām (ilham)",
    "inspiration/kashf": "Kashf (keşf)",
    "inspiration/dream-vision": "Sadık rüya",
    # --- revelation ------------------------------------------------------
    "revelation": "Vahiy",
    "revelation/recited": "Tilavet edilen vahiy (Kur'an)",
    "revelation/non-recited": "Tilavet edilmeyen vahiy (Sünnet)",
    "revelation/modes-of-receiving": "Vahyin alınış tarzları",
    # --- unclassifiable --------------------------------------------------
    "unclassifiable": "Sınıflandırılamaz",
}


TRANSLATIONS = {
    "ja": JA,
    "ko": KO,
    "zh": ZH,
    "ru": RU,
    "tr": TR,
}


def main() -> None:
    # Load canonical key list from en.json — this is the parity reference.
    with (I18N / "en.json").open("r", encoding="utf-8") as f:
        en = json.load(f)
    canonical_keys = list(en["cece"]["taxonomy"].keys())
    expected_count = len(canonical_keys)
    print(f"en.json cece.taxonomy: {expected_count} keys (canonical)")
    if expected_count != 277:
        print(f"  WARNING: expected 277, got {expected_count}")

    canon_set = set(canonical_keys)

    for loc in LOCALES:
        block = TRANSLATIONS[loc]
        loc_set = set(block.keys())
        missing = canon_set - loc_set
        extra = loc_set - canon_set
        if missing:
            print(f"\n[{loc}] MISSING {len(missing)} keys (will not write):")
            for k in sorted(missing):
                print(f"  - {k}")
            raise SystemExit(f"Aborting: {loc} is incomplete")
        if extra:
            print(f"\n[{loc}] EXTRA {len(extra)} keys (will not write):")
            for k in sorted(extra):
                print(f"  - {k}")
            raise SystemExit(f"Aborting: {loc} has stray keys")

        # Reorder block to match canonical key order.
        ordered = {k: block[k] for k in canonical_keys}

        path = I18N / f"{loc}.json"
        with path.open("r", encoding="utf-8") as f:
            data = json.load(f)
        cece = data.setdefault("cece", {})
        existing = cece.get("taxonomy")
        cece["taxonomy"] = ordered
        with path.open("w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)
            f.write("\n")
        action = "REPLACED" if existing is not None else "ADDED"
        print(f"[{loc}] {action} cece.taxonomy: {len(ordered)} keys -> {path.name}")


if __name__ == "__main__":
    main()
