#!/usr/bin/env python3
"""
MIG-022 §E.3.d — Backfill the 277-key cece.taxonomy block into 4 Latin-script
locales: de, es, fr, pt.

Source of truth: src/lib/i18n/en.json + src/lib/i18n/ar.json (already seeded
by §E.3.a). This script holds the de/es/fr/pt translations as nested dicts and
applies them to each locale JSON file (insert/replace cece.taxonomy).

Translation guidelines (per §E.3.d brief):
  1. Tradition-specific terms (Arabic uṣūl + Sanskrit pramāṇa) — keep the
     romanized term in parens as a scholarly anchor (shakk, qiyas, anumana,
     al-tawatur, etc.) — do NOT translate the parenthetical.
  2. Abstract terms without parenthetical — translate cleanly.
  3. Compound IDs translate the leaf-label only (id is the path).
  4. Preserve Title Case + parens + slashes for OR.
  5. French: typographic spacing — narrow non-breaking before ":" and ";".
     Other Latin locales: standard space.
  6. Portuguese: European Portuguese conventions where they diverge.

Run:
    python lab/scripts/mig022_e3d_taxonomy_latin.py

Idempotent: re-running rewrites cece.taxonomy from this file's translation
dicts (the source of truth for de/es/fr/pt). Safe to re-run after edits.
"""
import json
from pathlib import Path

ROOT = Path(r"E:\مشاريع كلاود\Constellation")
LOCALE_DIR = ROOT / "src/lib/i18n"

# Order canonical for insertion (after 'disambiguation', before any trailing
# meta keys — matches en.json where 'taxonomy' is the last cece key).
INSERT_AFTER = "disambiguation"


# =============================================================================
# DE — German
# =============================================================================
DE = {
    "epistemic-content": "Epistemischer Inhalt",
    "sensory-inputs": "Sinneswahrnehmungen",
    "sensory-inputs/signal": "Signal",
    "sensory-inputs/signal/physical": "Physikalisches Signal",
    "sensory-inputs/signal/physical/electromagnetic": "Elektromagnetisch",
    "sensory-inputs/signal/physical/acoustic": "Akustisch",
    "sensory-inputs/signal/physical/mechanical": "Mechanisch",
    "sensory-inputs/signal/physical/chemical": "Chemisch",
    "sensory-inputs/signal/biological": "Biologisches Signal",
    "sensory-inputs/signal/biological/neural": "Neural",
    "sensory-inputs/signal/biological/hormonal": "Hormonell",
    "sensory-inputs/signal/biological/bioelectric": "Bioelektrisch",
    "sensory-inputs/stimulus": "Reiz",
    "sensory-inputs/stimulus/distal": "Distaler Reiz",
    "sensory-inputs/stimulus/proximal": "Proximaler Reiz",
    "sensory-inputs/stimulus/conditioned": "Konditionierter Reiz",
    "sensory-inputs/stimulus/unconditioned": "Unkonditionierter Reiz",
    "sensory-inputs/sense-datum": "Sinnesdatum",
    "sensory-inputs/sense-datum/visual": "Visuelle Qualia",
    "sensory-inputs/sense-datum/auditory": "Auditive Qualia",
    "sensory-inputs/sense-datum/tactile": "Taktile Qualia",
    "sensory-inputs/sense-datum/olfactory": "Olfaktorische Qualia",
    "sensory-inputs/sense-datum/gustatory": "Gustatorische Qualia",
    "sensory-inputs/sense-datum/proprioceptive": "Propriozeptive Qualia",
    "sensory-inputs/percept": "Perzept",
    "sensory-inputs/percept/indeterminate": "Unbestimmtes Perzept (nirvikalpa)",
    "sensory-inputs/percept/indeterminate/pure-sensation": "Reine Empfindung",
    "sensory-inputs/percept/determinate": "Bestimmtes Perzept (savikalpa)",
    "sensory-inputs/percept/determinate/object-recognition": "Objekterkennung",
    "sensory-inputs/percept/determinate/categorized": "Kategorisierte Wahrnehmung",
    "sensory-inputs/percept/extraordinary": "Außerordentliche Wahrnehmung (alaukika)",
    "sensory-inputs/percept/extraordinary/generic": "Generisch (sāmānyalakṣaṇa)",
    "sensory-inputs/percept/extraordinary/acquired": "Erworben (jñānalakṣaṇa)",
    "sensory-inputs/percept/extraordinary/yogic": "Yogisch (yogaja)",
    "symbolic-entities": "Symbolische Entitäten",
    "symbolic-entities/sign": "Zeichen (Peirce-Klassifikation)",
    "symbolic-entities/sign/icon": "Ikon — durch Ähnlichkeit",
    "symbolic-entities/sign/icon/image": "Bild",
    "symbolic-entities/sign/icon/diagram": "Diagramm",
    "symbolic-entities/sign/icon/metaphor": "Metapher",
    "symbolic-entities/sign/index": "Index — durch kausale Verbindung",
    "symbolic-entities/sign/index/symptom": "Symptom",
    "symbolic-entities/sign/index/trace": "Spur",
    "symbolic-entities/sign/index/pointer": "Zeiger",
    "symbolic-entities/sign/symbol-conventional": "Symbol — durch Konvention",
    "symbolic-entities/sign/symbol-conventional/word": "Wort",
    "symbolic-entities/sign/symbol-conventional/numeral": "Zahlzeichen",
    "symbolic-entities/sign/symbol-conventional/logical-operator": "Logischer Operator",
    "symbolic-entities/symbol": "Symbol",
    "symbolic-entities/symbol/linguistic": "Sprachliches Symbol",
    "symbolic-entities/symbol/linguistic/phoneme": "Phonem",
    "symbolic-entities/symbol/linguistic/morpheme": "Morphem",
    "symbolic-entities/symbol/linguistic/lexeme": "Lexem",
    "symbolic-entities/symbol/mathematical": "Mathematisches Symbol",
    "symbolic-entities/symbol/logical": "Logisches Symbol",
    "symbolic-entities/symbol/iconographic": "Ikonografisches Symbol",
    "symbolic-entities/data": "Daten",
    "symbolic-entities/data/structured": "Strukturierte Daten",
    "symbolic-entities/data/structured/tabular": "Tabellarisch",
    "symbolic-entities/data/structured/relational": "Relational",
    "symbolic-entities/data/semi-structured": "Halbstrukturierte Daten",
    "symbolic-entities/data/semi-structured/serialized": "JSON / XML / YAML",
    "symbolic-entities/data/unstructured": "Unstrukturierte Daten",
    "symbolic-entities/data/unstructured/text": "Text",
    "symbolic-entities/data/unstructured/image": "Bild",
    "symbolic-entities/data/unstructured/audio": "Audio",
    "symbolic-entities/data/unstructured/video": "Video",
    "symbolic-entities/data/quantitative": "Quantitative Daten",
    "symbolic-entities/data/qualitative": "Qualitative Daten",
    "symbolic-entities/code": "Code",
    "symbolic-entities/code/natural-language": "Natürlichsprachlicher Code",
    "symbolic-entities/code/formal-language": "Formalsprachlicher Code",
    "symbolic-entities/code/computer": "Computer-Code",
    "symbolic-entities/code/cryptographic": "Kryptografischer Code",
    "symbolic-entities/inscription": "Inskription",
    "symbolic-entities/inscription/oral": "Mündlich",
    "symbolic-entities/inscription/manuscript": "Handschrift",
    "symbolic-entities/inscription/print": "Druck",
    "symbolic-entities/inscription/digital": "Digital",
    "semantic-contents": "Semantische Inhalte",
    "semantic-contents/concept": "Begriff (taṣawwur)",
    "semantic-contents/concept/simple": "Einfacher Begriff",
    "semantic-contents/concept/compound": "Zusammengesetzter Begriff",
    "semantic-contents/concept/empirical": "Empirischer Begriff",
    "semantic-contents/concept/empirical/observational": "Beobachtend",
    "semantic-contents/concept/empirical/experimental": "Experimentell",
    "semantic-contents/concept/a-priori": "A-priori-Begriff",
    "semantic-contents/concept/a-priori/logical": "Logisch",
    "semantic-contents/concept/a-priori/mathematical": "Mathematisch",
    "semantic-contents/concept/concrete": "Konkreter Begriff",
    "semantic-contents/concept/abstract": "Abstrakter Begriff",
    "semantic-contents/idea": "Idee",
    "semantic-contents/idea/innate": "Angeborene Idee (kartesisch)",
    "semantic-contents/idea/adventitious": "Adventitielle Idee",
    "semantic-contents/idea/constructed": "Konstruierte Idee",
    "semantic-contents/idea/clear-distinct": "Klare und deutliche Idee",
    "semantic-contents/proposition": "Proposition (qaḍiyyah)",
    "semantic-contents/proposition/categorical": "Kategorische Proposition",
    "semantic-contents/proposition/categorical/universal-affirmative": "Universal bejahend",
    "semantic-contents/proposition/categorical/universal-negative": "Universal verneinend",
    "semantic-contents/proposition/categorical/particular-affirmative": "Partikular bejahend",
    "semantic-contents/proposition/categorical/particular-negative": "Partikular verneinend",
    "semantic-contents/proposition/hypothetical": "Hypothetische Proposition",
    "semantic-contents/proposition/hypothetical/conjunctive": "Konjunktiv (muttaṣilah)",
    "semantic-contents/proposition/hypothetical/disjunctive": "Disjunktiv (munfaṣilah)",
    "semantic-contents/proposition/modal": "Modale Proposition",
    "semantic-contents/proposition/modal/necessary": "Notwendig",
    "semantic-contents/proposition/modal/possible": "Möglich",
    "semantic-contents/proposition/modal/impossible": "Unmöglich",
    "semantic-contents/information": "Information (DIKW T2)",
    "semantic-contents/information/syntactic": "Syntaktische Information",
    "semantic-contents/information/semantic": "Semantische Information",
    "semantic-contents/information/pragmatic": "Pragmatische Information",
    "semantic-contents/fact": "Tatsache (wāqiʿah)",
    "semantic-contents/fact/empirical": "Empirische Tatsache",
    "semantic-contents/fact/mathematical": "Mathematische Tatsache",
    "semantic-contents/fact/logical": "Logische Tatsache",
    "semantic-contents/fact/historical": "Historische Tatsache",
    "semantic-contents/fact/moral": "Moralische Tatsache",
    "semantic-contents/meaning": "Bedeutung (maʿnā)",
    "semantic-contents/meaning/sense-vs-reference": "Sinn vs. Bedeutung (Frege)",
    "semantic-contents/meaning/connotation-vs-denotation": "Konnotation vs. Denotation",
    "semantic-contents/meaning/literal-vs-figurative": "Wörtlich vs. figurativ",
    "semantic-contents/definition": "Definition (ḥadd)",
    "semantic-contents/definition/real": "Realdefinition",
    "semantic-contents/definition/nominal": "Nominaldefinition",
    "semantic-contents/definition/genus-differentia": "Genus-Differentia",
    "semantic-contents/definition/ostensive": "Ostensive Definition",
    "epistemic-states": "Epistemische Zustände",
    "epistemic-states/compound-ignorance": "Zusammengesetzte Unwissenheit",
    "epistemic-states/simple-ignorance": "Einfache Unwissenheit",
    "epistemic-states/illusion": "Illusion (wahm)",
    "epistemic-states/illusion/perceptual": "Wahrnehmungsillusion",
    "epistemic-states/illusion/cognitive": "Kognitive Illusion",
    "epistemic-states/doubt": "Zweifel (shakk)",
    "epistemic-states/doubt/methodological": "Methodischer Zweifel",
    "epistemic-states/doubt/habitual": "Gewohnheitsmäßiger Zweifel",
    "epistemic-states/doubt/equipoised": "Ausgewogener Zweifel",
    "epistemic-states/opinion": "Meinung (ẓann)",
    "epistemic-states/opinion/probable": "Wahrscheinliche Meinung",
    "epistemic-states/opinion/well-grounded": "Gut begründete Meinung",
    "epistemic-states/opinion/dispositional": "Dispositionelle Meinung",
    "epistemic-states/belief": "Glaube (iʿtiqād / taṣdīq)",
    "epistemic-states/belief/occurrent": "Aktualer Glaube",
    "epistemic-states/belief/dispositional": "Dispositioneller Glaube",
    "epistemic-states/belief/faith": "Glaube (īmān)",
    "epistemic-states/knowledge": "Wissen (ʿilm / maʿrifah)",
    "epistemic-states/knowledge/by-mode": "Nach Repräsentationsmodus",
    "epistemic-states/knowledge/by-mode/acquired": "Erworben (al-ʿilm al-ḥuṣūlī)",
    "epistemic-states/knowledge/by-mode/presential": "Präsential (al-ʿilm al-ḥuḍūrī)",
    "epistemic-states/knowledge/by-content": "Nach Inhaltstyp",
    "epistemic-states/knowledge/by-content/propositional": "Propositional (Wissen-dass)",
    "epistemic-states/knowledge/by-content/propositional/a-priori-analytic": "A priori — analytisch",
    "epistemic-states/knowledge/by-content/propositional/a-priori-synthetic": "A priori — synthetisch",
    "epistemic-states/knowledge/by-content/propositional/a-posteriori-empirical": "A posteriori — empirisch",
    "epistemic-states/knowledge/by-content/propositional/a-posteriori-testimonial": "A posteriori — testimonial",
    "epistemic-states/knowledge/by-content/procedural": "Prozedural (Wissen-wie)",
    "epistemic-states/knowledge/by-content/procedural/motor": "Motorische Fertigkeit",
    "epistemic-states/knowledge/by-content/procedural/cognitive": "Kognitive Fertigkeit",
    "epistemic-states/knowledge/by-content/procedural/social": "Soziale Fertigkeit",
    "epistemic-states/knowledge/by-content/acquaintance": "Bekanntschaft (Wissen-von)",
    "epistemic-states/knowledge/by-content/acquaintance/direct-experience": "Durch direkte Erfahrung",
    "epistemic-states/knowledge/by-content/acquaintance/memory": "Durch Gedächtnis",
    "epistemic-states/knowledge/by-content/tacit": "Implizit (Polanyi)",
    "epistemic-states/knowledge/by-source": "Nach Quelle",
    "epistemic-states/knowledge/by-source/sensory": "Sinnliches Wissen",
    "epistemic-states/knowledge/by-source/rational": "Rationales Wissen",
    "epistemic-states/knowledge/by-source/testimonial": "Zeugnisbasiertes Wissen",
    "epistemic-states/knowledge/by-source/revelatory": "Offenbarungswissen",
    "epistemic-states/certainty": "Gewissheit (yaqīn)",
    "epistemic-states/certainty/logical": "Logische Gewissheit",
    "epistemic-states/certainty/mathematical": "Mathematische Gewissheit",
    "epistemic-states/certainty/metaphysical": "Metaphysische Gewissheit",
    "epistemic-states/certainty/moral": "Moralische Gewissheit",
    "epistemic-states/certainty/religious": "Religiöse Gewissheit",
    "epistemic-states/certainty/religious/ilm-al-yaqin": "ʿIlm al-yaqīn — Wissen der Gewissheit",
    "epistemic-states/certainty/religious/ayn-al-yaqin": "ʿAyn al-yaqīn — Auge der Gewissheit",
    "epistemic-states/certainty/religious/haqq-al-yaqin": "Ḥaqq al-yaqīn — Wahrheit der Gewissheit",
    "higher-order-constructs": "Konstrukte höherer Ordnung",
    "higher-order-constructs/hypothesis": "Hypothese (faraḍiyyah)",
    "higher-order-constructs/hypothesis/working": "Arbeitshypothese",
    "higher-order-constructs/hypothesis/statistical": "Statistische Hypothese",
    "higher-order-constructs/hypothesis/statistical/null": "Nullhypothese",
    "higher-order-constructs/hypothesis/statistical/alternative": "Alternativhypothese",
    "higher-order-constructs/hypothesis/causal": "Kausale Hypothese",
    "higher-order-constructs/theory": "Theorie (naẓariyyah)",
    "higher-order-constructs/theory/empirical": "Empirische Theorie",
    "higher-order-constructs/theory/empirical/descriptive": "Deskriptiv",
    "higher-order-constructs/theory/empirical/explanatory": "Erklärend",
    "higher-order-constructs/theory/empirical/predictive": "Prädiktiv",
    "higher-order-constructs/theory/formal": "Formale Theorie",
    "higher-order-constructs/theory/normative": "Normative Theorie",
    "higher-order-constructs/model": "Modell (namūdhaj)",
    "higher-order-constructs/model/physical": "Physikalisches Modell",
    "higher-order-constructs/model/mathematical": "Mathematisches Modell",
    "higher-order-constructs/model/computational": "Berechnungsmodell",
    "higher-order-constructs/model/conceptual": "Konzeptuelles Modell",
    "higher-order-constructs/law": "Gesetz (qānūn)",
    "higher-order-constructs/law/natural": "Naturgesetz",
    "higher-order-constructs/law/natural/universal": "Universelles Gesetz",
    "higher-order-constructs/law/natural/statistical": "Statistisches Gesetz",
    "higher-order-constructs/law/logical": "Logisches Gesetz",
    "higher-order-constructs/law/logical/identity": "Identität",
    "higher-order-constructs/law/logical/non-contradiction": "Widerspruchsfreiheit",
    "higher-order-constructs/law/logical/excluded-middle": "Ausgeschlossenes Drittes",
    "higher-order-constructs/law/divine": "Göttliches Gesetz (sharīʿah)",
    "higher-order-constructs/law/positive": "Positives Recht",
    "higher-order-constructs/doctrine": "Lehre (madhhab)",
    "higher-order-constructs/doctrine/religious": "Religiöse Lehre",
    "higher-order-constructs/doctrine/philosophical": "Philosophische Lehre",
    "higher-order-constructs/doctrine/scientific": "Wissenschaftliche Lehre",
    "higher-order-constructs/insight": "Einsicht (baṣīrah)",
    "higher-order-constructs/insight/aesthetic": "Ästhetische Einsicht",
    "higher-order-constructs/insight/mystical": "Mystische Einsicht",
    "higher-order-constructs/insight/scientific": "Wissenschaftliche Einsicht",
    "higher-order-constructs/wisdom": "Weisheit (ḥikmah)",
    "higher-order-constructs/wisdom/theoretical": "Theoretische Weisheit (sophia)",
    "higher-order-constructs/wisdom/practical": "Praktische Weisheit (phronēsis)",
    "higher-order-constructs/wisdom/productive-craft": "Produktives Handwerk (technē)",
    "higher-order-constructs/wisdom/spiritual": "Spirituelle Weisheit",
    "higher-order-constructs/worldview": "Weltanschauung (ruʾyah kawniyyah)",
    "higher-order-constructs/worldview/religious": "Religiöse Weltanschauung",
    "higher-order-constructs/worldview/secular": "Säkulare Weltanschauung",
    "higher-order-constructs/worldview/syncretic": "Synkretistische Weltanschauung",
    "perception": "Wahrnehmung / Empfindung",
    "perception/external": "Äußere Wahrnehmung",
    "perception/internal": "Innere Wahrnehmung",
    "perception/self": "Selbstwahrnehmung",
    "perception/extraordinary": "Außerordentliche Wahrnehmung",
    "inference": "Inferenz / Vernunft",
    "inference/deductive": "Deduktive Inferenz",
    "inference/inductive": "Induktive Inferenz",
    "inference/abductive": "Abduktive Inferenz",
    "inference/necessary": "Notwendige Vernunft",
    "inference/speculative": "Spekulative Vernunft",
    "testimony": "Zeugnis",
    "testimony/direct-witness": "Direktes Augenzeugnis",
    "testimony/reported": "Berichtetes Zeugnis",
    "testimony/authoritative": "Autoritatives Zeugnis",
    "testimony/scriptural": "Schriftliches Zeugnis",
    "mass-transmission": "Massenüberlieferung (al-tawatur)",
    "mass-transmission/verbal": "Wörtliche Massenüberlieferung",
    "mass-transmission/meaning": "Sinngemäße Massenüberlieferung",
    "mass-transmission/practical": "Praktische Massenüberlieferung",
    "comparison": "Vergleich / Analogie",
    "comparison/ratio-legis": "Analogie nach ratio legis",
    "comparison/indication": "Analogie durch Indikation",
    "comparison/resemblance": "Analogie durch Ähnlichkeit",
    "comparison/a-fortiori": "A-fortiori-Analogie",
    "postulation": "Postulation / IBE",
    "postulation/from-perceived": "Aus wahrgenommener Tatsache",
    "postulation/from-heard": "Aus gehörter Tatsache",
    "postulation/ibe": "Schluss auf die beste Erklärung",
    "non-apprehension": "Nicht-Erfassung",
    "non-apprehension/prior": "Vorhergehende Abwesenheit",
    "non-apprehension/posterior": "Nachfolgende Abwesenheit",
    "non-apprehension/mutual": "Gegenseitige Abwesenheit",
    "non-apprehension/absolute": "Absolute Abwesenheit",
    "memory": "Gedächtnis",
    "memory/recollection": "Erinnerung",
    "memory/recognition": "Wiedererkennung",
    "memory/episodic": "Episodisches Gedächtnis",
    "memory/semantic": "Semantisches Gedächtnis",
    "innate-disposition": "Angeborene Disposition / Intuition",
    "innate-disposition/primordial": "Ursprüngliche Disposition (Sunna)",
    "innate-disposition/first-principles": "Intuition der ersten Prinzipien",
    "innate-disposition/moral": "Angeborenes moralisches Wissen",
    "innate-disposition/axioms": "Selbstverständliche Axiome",
    "inspiration": "Inspiration / Mystische Erfassung",
    "inspiration/ilham": "Ilhām (Inspiration)",
    "inspiration/kashf": "Kashf (Enthüllung)",
    "inspiration/dream-vision": "Wahre Traumvision",
    "revelation": "Offenbarung",
    "revelation/recited": "Rezitierte Offenbarung (Koran)",
    "revelation/non-recited": "Nicht-rezitierte Offenbarung (Sunna)",
    "revelation/modes-of-receiving": "Modi des Offenbarungsempfangs",
    "unclassifiable": "Nicht klassifizierbar",
}


# =============================================================================
# ES — Spanish
# =============================================================================
ES = {
    "epistemic-content": "Contenido epistémico",
    "sensory-inputs": "Entradas sensoriales",
    "sensory-inputs/signal": "Señal",
    "sensory-inputs/signal/physical": "Señal física",
    "sensory-inputs/signal/physical/electromagnetic": "Electromagnética",
    "sensory-inputs/signal/physical/acoustic": "Acústica",
    "sensory-inputs/signal/physical/mechanical": "Mecánica",
    "sensory-inputs/signal/physical/chemical": "Química",
    "sensory-inputs/signal/biological": "Señal biológica",
    "sensory-inputs/signal/biological/neural": "Neural",
    "sensory-inputs/signal/biological/hormonal": "Hormonal",
    "sensory-inputs/signal/biological/bioelectric": "Bioeléctrica",
    "sensory-inputs/stimulus": "Estímulo",
    "sensory-inputs/stimulus/distal": "Estímulo distal",
    "sensory-inputs/stimulus/proximal": "Estímulo proximal",
    "sensory-inputs/stimulus/conditioned": "Estímulo condicionado",
    "sensory-inputs/stimulus/unconditioned": "Estímulo incondicionado",
    "sensory-inputs/sense-datum": "Dato sensorial",
    "sensory-inputs/sense-datum/visual": "Cualia visual",
    "sensory-inputs/sense-datum/auditory": "Cualia auditiva",
    "sensory-inputs/sense-datum/tactile": "Cualia táctil",
    "sensory-inputs/sense-datum/olfactory": "Cualia olfativa",
    "sensory-inputs/sense-datum/gustatory": "Cualia gustativa",
    "sensory-inputs/sense-datum/proprioceptive": "Cualia propioceptiva",
    "sensory-inputs/percept": "Percepto",
    "sensory-inputs/percept/indeterminate": "Percepto indeterminado (nirvikalpa)",
    "sensory-inputs/percept/indeterminate/pure-sensation": "Sensación pura",
    "sensory-inputs/percept/determinate": "Percepto determinado (savikalpa)",
    "sensory-inputs/percept/determinate/object-recognition": "Reconocimiento de objetos",
    "sensory-inputs/percept/determinate/categorized": "Percepción categorizada",
    "sensory-inputs/percept/extraordinary": "Percepción extraordinaria (alaukika)",
    "sensory-inputs/percept/extraordinary/generic": "Genérica (sāmānyalakṣaṇa)",
    "sensory-inputs/percept/extraordinary/acquired": "Adquirida (jñānalakṣaṇa)",
    "sensory-inputs/percept/extraordinary/yogic": "Yóguica (yogaja)",
    "symbolic-entities": "Entidades simbólicas",
    "symbolic-entities/sign": "Signo (clasificación de Peirce)",
    "symbolic-entities/sign/icon": "Ícono — por semejanza",
    "symbolic-entities/sign/icon/image": "Imagen",
    "symbolic-entities/sign/icon/diagram": "Diagrama",
    "symbolic-entities/sign/icon/metaphor": "Metáfora",
    "symbolic-entities/sign/index": "Índice — por conexión causal",
    "symbolic-entities/sign/index/symptom": "Síntoma",
    "symbolic-entities/sign/index/trace": "Huella",
    "symbolic-entities/sign/index/pointer": "Indicador",
    "symbolic-entities/sign/symbol-conventional": "Símbolo — por convención",
    "symbolic-entities/sign/symbol-conventional/word": "Palabra",
    "symbolic-entities/sign/symbol-conventional/numeral": "Numeral",
    "symbolic-entities/sign/symbol-conventional/logical-operator": "Operador lógico",
    "symbolic-entities/symbol": "Símbolo",
    "symbolic-entities/symbol/linguistic": "Símbolo lingüístico",
    "symbolic-entities/symbol/linguistic/phoneme": "Fonema",
    "symbolic-entities/symbol/linguistic/morpheme": "Morfema",
    "symbolic-entities/symbol/linguistic/lexeme": "Lexema",
    "symbolic-entities/symbol/mathematical": "Símbolo matemático",
    "symbolic-entities/symbol/logical": "Símbolo lógico",
    "symbolic-entities/symbol/iconographic": "Símbolo iconográfico",
    "symbolic-entities/data": "Datos",
    "symbolic-entities/data/structured": "Datos estructurados",
    "symbolic-entities/data/structured/tabular": "Tabular",
    "symbolic-entities/data/structured/relational": "Relacional",
    "symbolic-entities/data/semi-structured": "Datos semiestructurados",
    "symbolic-entities/data/semi-structured/serialized": "JSON / XML / YAML",
    "symbolic-entities/data/unstructured": "Datos no estructurados",
    "symbolic-entities/data/unstructured/text": "Texto",
    "symbolic-entities/data/unstructured/image": "Imagen",
    "symbolic-entities/data/unstructured/audio": "Audio",
    "symbolic-entities/data/unstructured/video": "Vídeo",
    "symbolic-entities/data/quantitative": "Datos cuantitativos",
    "symbolic-entities/data/qualitative": "Datos cualitativos",
    "symbolic-entities/code": "Código",
    "symbolic-entities/code/natural-language": "Código en lenguaje natural",
    "symbolic-entities/code/formal-language": "Código en lenguaje formal",
    "symbolic-entities/code/computer": "Código informático",
    "symbolic-entities/code/cryptographic": "Código criptográfico",
    "symbolic-entities/inscription": "Inscripción",
    "symbolic-entities/inscription/oral": "Oral",
    "symbolic-entities/inscription/manuscript": "Manuscrito",
    "symbolic-entities/inscription/print": "Impreso",
    "symbolic-entities/inscription/digital": "Digital",
    "semantic-contents": "Contenidos semánticos",
    "semantic-contents/concept": "Concepto (taṣawwur)",
    "semantic-contents/concept/simple": "Concepto simple",
    "semantic-contents/concept/compound": "Concepto compuesto",
    "semantic-contents/concept/empirical": "Concepto empírico",
    "semantic-contents/concept/empirical/observational": "Observacional",
    "semantic-contents/concept/empirical/experimental": "Experimental",
    "semantic-contents/concept/a-priori": "Concepto a priori",
    "semantic-contents/concept/a-priori/logical": "Lógico",
    "semantic-contents/concept/a-priori/mathematical": "Matemático",
    "semantic-contents/concept/concrete": "Concepto concreto",
    "semantic-contents/concept/abstract": "Concepto abstracto",
    "semantic-contents/idea": "Idea",
    "semantic-contents/idea/innate": "Idea innata (cartesiana)",
    "semantic-contents/idea/adventitious": "Idea adventicia",
    "semantic-contents/idea/constructed": "Idea construida",
    "semantic-contents/idea/clear-distinct": "Idea clara y distinta",
    "semantic-contents/proposition": "Proposición (qaḍiyyah)",
    "semantic-contents/proposition/categorical": "Proposición categórica",
    "semantic-contents/proposition/categorical/universal-affirmative": "Universal afirmativa",
    "semantic-contents/proposition/categorical/universal-negative": "Universal negativa",
    "semantic-contents/proposition/categorical/particular-affirmative": "Particular afirmativa",
    "semantic-contents/proposition/categorical/particular-negative": "Particular negativa",
    "semantic-contents/proposition/hypothetical": "Proposición hipotética",
    "semantic-contents/proposition/hypothetical/conjunctive": "Conjuntiva (muttaṣilah)",
    "semantic-contents/proposition/hypothetical/disjunctive": "Disyuntiva (munfaṣilah)",
    "semantic-contents/proposition/modal": "Proposición modal",
    "semantic-contents/proposition/modal/necessary": "Necesaria",
    "semantic-contents/proposition/modal/possible": "Posible",
    "semantic-contents/proposition/modal/impossible": "Imposible",
    "semantic-contents/information": "Información (DIKW T2)",
    "semantic-contents/information/syntactic": "Información sintáctica",
    "semantic-contents/information/semantic": "Información semántica",
    "semantic-contents/information/pragmatic": "Información pragmática",
    "semantic-contents/fact": "Hecho (wāqiʿah)",
    "semantic-contents/fact/empirical": "Hecho empírico",
    "semantic-contents/fact/mathematical": "Hecho matemático",
    "semantic-contents/fact/logical": "Hecho lógico",
    "semantic-contents/fact/historical": "Hecho histórico",
    "semantic-contents/fact/moral": "Hecho moral",
    "semantic-contents/meaning": "Significado (maʿnā)",
    "semantic-contents/meaning/sense-vs-reference": "Sentido vs. referencia (Frege)",
    "semantic-contents/meaning/connotation-vs-denotation": "Connotación vs. denotación",
    "semantic-contents/meaning/literal-vs-figurative": "Literal vs. figurado",
    "semantic-contents/definition": "Definición (ḥadd)",
    "semantic-contents/definition/real": "Definición real",
    "semantic-contents/definition/nominal": "Definición nominal",
    "semantic-contents/definition/genus-differentia": "Género-diferencia",
    "semantic-contents/definition/ostensive": "Definición ostensiva",
    "epistemic-states": "Estados epistémicos",
    "epistemic-states/compound-ignorance": "Ignorancia compuesta",
    "epistemic-states/simple-ignorance": "Ignorancia simple",
    "epistemic-states/illusion": "Ilusión (wahm)",
    "epistemic-states/illusion/perceptual": "Ilusión perceptiva",
    "epistemic-states/illusion/cognitive": "Ilusión cognitiva",
    "epistemic-states/doubt": "Duda (shakk)",
    "epistemic-states/doubt/methodological": "Duda metodológica",
    "epistemic-states/doubt/habitual": "Duda habitual",
    "epistemic-states/doubt/equipoised": "Duda equilibrada",
    "epistemic-states/opinion": "Opinión (ẓann)",
    "epistemic-states/opinion/probable": "Opinión probable",
    "epistemic-states/opinion/well-grounded": "Opinión bien fundada",
    "epistemic-states/opinion/dispositional": "Opinión disposicional",
    "epistemic-states/belief": "Creencia (iʿtiqād / taṣdīq)",
    "epistemic-states/belief/occurrent": "Creencia ocurrente",
    "epistemic-states/belief/dispositional": "Creencia disposicional",
    "epistemic-states/belief/faith": "Fe (īmān)",
    "epistemic-states/knowledge": "Conocimiento (ʿilm / maʿrifah)",
    "epistemic-states/knowledge/by-mode": "Por modo de representación",
    "epistemic-states/knowledge/by-mode/acquired": "Adquirido (al-ʿilm al-ḥuṣūlī)",
    "epistemic-states/knowledge/by-mode/presential": "Presencial (al-ʿilm al-ḥuḍūrī)",
    "epistemic-states/knowledge/by-content": "Por tipo de contenido",
    "epistemic-states/knowledge/by-content/propositional": "Proposicional (saber-que)",
    "epistemic-states/knowledge/by-content/propositional/a-priori-analytic": "A priori — analítico",
    "epistemic-states/knowledge/by-content/propositional/a-priori-synthetic": "A priori — sintético",
    "epistemic-states/knowledge/by-content/propositional/a-posteriori-empirical": "A posteriori — empírico",
    "epistemic-states/knowledge/by-content/propositional/a-posteriori-testimonial": "A posteriori — testimonial",
    "epistemic-states/knowledge/by-content/procedural": "Procedimental (saber-cómo)",
    "epistemic-states/knowledge/by-content/procedural/motor": "Habilidad motriz",
    "epistemic-states/knowledge/by-content/procedural/cognitive": "Habilidad cognitiva",
    "epistemic-states/knowledge/by-content/procedural/social": "Habilidad social",
    "epistemic-states/knowledge/by-content/acquaintance": "Conocimiento directo (saber-de)",
    "epistemic-states/knowledge/by-content/acquaintance/direct-experience": "Por experiencia directa",
    "epistemic-states/knowledge/by-content/acquaintance/memory": "Por memoria",
    "epistemic-states/knowledge/by-content/tacit": "Tácito (Polanyi)",
    "epistemic-states/knowledge/by-source": "Por fuente",
    "epistemic-states/knowledge/by-source/sensory": "Conocimiento sensorial",
    "epistemic-states/knowledge/by-source/rational": "Conocimiento racional",
    "epistemic-states/knowledge/by-source/testimonial": "Conocimiento testimonial",
    "epistemic-states/knowledge/by-source/revelatory": "Conocimiento revelado",
    "epistemic-states/certainty": "Certeza (yaqīn)",
    "epistemic-states/certainty/logical": "Certeza lógica",
    "epistemic-states/certainty/mathematical": "Certeza matemática",
    "epistemic-states/certainty/metaphysical": "Certeza metafísica",
    "epistemic-states/certainty/moral": "Certeza moral",
    "epistemic-states/certainty/religious": "Certeza religiosa",
    "epistemic-states/certainty/religious/ilm-al-yaqin": "ʿIlm al-yaqīn — conocimiento de la certeza",
    "epistemic-states/certainty/religious/ayn-al-yaqin": "ʿAyn al-yaqīn — ojo de la certeza",
    "epistemic-states/certainty/religious/haqq-al-yaqin": "Ḥaqq al-yaqīn — verdad de la certeza",
    "higher-order-constructs": "Constructos de orden superior",
    "higher-order-constructs/hypothesis": "Hipótesis (faraḍiyyah)",
    "higher-order-constructs/hypothesis/working": "Hipótesis de trabajo",
    "higher-order-constructs/hypothesis/statistical": "Hipótesis estadística",
    "higher-order-constructs/hypothesis/statistical/null": "Hipótesis nula",
    "higher-order-constructs/hypothesis/statistical/alternative": "Hipótesis alternativa",
    "higher-order-constructs/hypothesis/causal": "Hipótesis causal",
    "higher-order-constructs/theory": "Teoría (naẓariyyah)",
    "higher-order-constructs/theory/empirical": "Teoría empírica",
    "higher-order-constructs/theory/empirical/descriptive": "Descriptiva",
    "higher-order-constructs/theory/empirical/explanatory": "Explicativa",
    "higher-order-constructs/theory/empirical/predictive": "Predictiva",
    "higher-order-constructs/theory/formal": "Teoría formal",
    "higher-order-constructs/theory/normative": "Teoría normativa",
    "higher-order-constructs/model": "Modelo (namūdhaj)",
    "higher-order-constructs/model/physical": "Modelo físico",
    "higher-order-constructs/model/mathematical": "Modelo matemático",
    "higher-order-constructs/model/computational": "Modelo computacional",
    "higher-order-constructs/model/conceptual": "Modelo conceptual",
    "higher-order-constructs/law": "Ley (qānūn)",
    "higher-order-constructs/law/natural": "Ley natural",
    "higher-order-constructs/law/natural/universal": "Ley universal",
    "higher-order-constructs/law/natural/statistical": "Ley estadística",
    "higher-order-constructs/law/logical": "Ley lógica",
    "higher-order-constructs/law/logical/identity": "Identidad",
    "higher-order-constructs/law/logical/non-contradiction": "No contradicción",
    "higher-order-constructs/law/logical/excluded-middle": "Tercio excluso",
    "higher-order-constructs/law/divine": "Ley divina (sharīʿah)",
    "higher-order-constructs/law/positive": "Ley positiva",
    "higher-order-constructs/doctrine": "Doctrina (madhhab)",
    "higher-order-constructs/doctrine/religious": "Doctrina religiosa",
    "higher-order-constructs/doctrine/philosophical": "Doctrina filosófica",
    "higher-order-constructs/doctrine/scientific": "Doctrina científica",
    "higher-order-constructs/insight": "Perspicacia (baṣīrah)",
    "higher-order-constructs/insight/aesthetic": "Perspicacia estética",
    "higher-order-constructs/insight/mystical": "Perspicacia mística",
    "higher-order-constructs/insight/scientific": "Perspicacia científica",
    "higher-order-constructs/wisdom": "Sabiduría (ḥikmah)",
    "higher-order-constructs/wisdom/theoretical": "Sabiduría teórica (sophia)",
    "higher-order-constructs/wisdom/practical": "Sabiduría práctica (phronēsis)",
    "higher-order-constructs/wisdom/productive-craft": "Oficio productivo (technē)",
    "higher-order-constructs/wisdom/spiritual": "Sabiduría espiritual",
    "higher-order-constructs/worldview": "Cosmovisión (ruʾyah kawniyyah)",
    "higher-order-constructs/worldview/religious": "Cosmovisión religiosa",
    "higher-order-constructs/worldview/secular": "Cosmovisión secular",
    "higher-order-constructs/worldview/syncretic": "Cosmovisión sincrética",
    "perception": "Percepción / Sensación",
    "perception/external": "Percepción externa",
    "perception/internal": "Percepción interna",
    "perception/self": "Autopercepción",
    "perception/extraordinary": "Percepción extraordinaria",
    "inference": "Inferencia / Razón",
    "inference/deductive": "Inferencia deductiva",
    "inference/inductive": "Inferencia inductiva",
    "inference/abductive": "Inferencia abductiva",
    "inference/necessary": "Razón necesaria",
    "inference/speculative": "Razón especulativa",
    "testimony": "Testimonio",
    "testimony/direct-witness": "Testimonio de testigo directo",
    "testimony/reported": "Testimonio reportado",
    "testimony/authoritative": "Testimonio autoritativo",
    "testimony/scriptural": "Testimonio escritural",
    "mass-transmission": "Transmisión masiva (al-tawatur)",
    "mass-transmission/verbal": "Transmisión masiva verbal",
    "mass-transmission/meaning": "Transmisión masiva por significado",
    "mass-transmission/practical": "Transmisión masiva práctica",
    "comparison": "Comparación / Analogía",
    "comparison/ratio-legis": "Analogía por ratio legis",
    "comparison/indication": "Analogía por indicación",
    "comparison/resemblance": "Analogía por semejanza",
    "comparison/a-fortiori": "Analogía a fortiori",
    "postulation": "Postulación / IBE",
    "postulation/from-perceived": "Desde un hecho percibido",
    "postulation/from-heard": "Desde un hecho escuchado",
    "postulation/ibe": "Inferencia a la mejor explicación",
    "non-apprehension": "No aprehensión",
    "non-apprehension/prior": "Ausencia previa",
    "non-apprehension/posterior": "Ausencia posterior",
    "non-apprehension/mutual": "Ausencia mutua",
    "non-apprehension/absolute": "Ausencia absoluta",
    "memory": "Memoria",
    "memory/recollection": "Recuerdo",
    "memory/recognition": "Reconocimiento",
    "memory/episodic": "Memoria episódica",
    "memory/semantic": "Memoria semántica",
    "innate-disposition": "Disposición innata / Intuición",
    "innate-disposition/primordial": "Disposición primordial (suní)",
    "innate-disposition/first-principles": "Intuición de los primeros principios",
    "innate-disposition/moral": "Conocimiento moral innato",
    "innate-disposition/axioms": "Axiomas autoevidentes",
    "inspiration": "Inspiración / Aprehensión mística",
    "inspiration/ilham": "Ilhām (inspiración)",
    "inspiration/kashf": "Kashf (revelación)",
    "inspiration/dream-vision": "Visión onírica verdadera",
    "revelation": "Revelación",
    "revelation/recited": "Revelación recitada (Corán)",
    "revelation/non-recited": "Revelación no recitada (Sunna)",
    "revelation/modes-of-receiving": "Modos de recepción de la revelación",
    "unclassifiable": "No clasificable",
}


# =============================================================================
# FR — French (use NARROW NO-BREAK SPACE U+202F before ":" and ";")
# =============================================================================
# We don't use ":" or ";" in label values, so the NNBSP rule mostly doesn't
# trigger here — but kept the convention in mind for future labels.
FR = {
    "epistemic-content": "Contenu épistémique",
    "sensory-inputs": "Entrées sensorielles",
    "sensory-inputs/signal": "Signal",
    "sensory-inputs/signal/physical": "Signal physique",
    "sensory-inputs/signal/physical/electromagnetic": "Électromagnétique",
    "sensory-inputs/signal/physical/acoustic": "Acoustique",
    "sensory-inputs/signal/physical/mechanical": "Mécanique",
    "sensory-inputs/signal/physical/chemical": "Chimique",
    "sensory-inputs/signal/biological": "Signal biologique",
    "sensory-inputs/signal/biological/neural": "Neural",
    "sensory-inputs/signal/biological/hormonal": "Hormonal",
    "sensory-inputs/signal/biological/bioelectric": "Bioélectrique",
    "sensory-inputs/stimulus": "Stimulus",
    "sensory-inputs/stimulus/distal": "Stimulus distal",
    "sensory-inputs/stimulus/proximal": "Stimulus proximal",
    "sensory-inputs/stimulus/conditioned": "Stimulus conditionné",
    "sensory-inputs/stimulus/unconditioned": "Stimulus inconditionné",
    "sensory-inputs/sense-datum": "Donnée sensorielle",
    "sensory-inputs/sense-datum/visual": "Qualia visuel",
    "sensory-inputs/sense-datum/auditory": "Qualia auditif",
    "sensory-inputs/sense-datum/tactile": "Qualia tactile",
    "sensory-inputs/sense-datum/olfactory": "Qualia olfactif",
    "sensory-inputs/sense-datum/gustatory": "Qualia gustatif",
    "sensory-inputs/sense-datum/proprioceptive": "Qualia proprioceptif",
    "sensory-inputs/percept": "Percept",
    "sensory-inputs/percept/indeterminate": "Percept indéterminé (nirvikalpa)",
    "sensory-inputs/percept/indeterminate/pure-sensation": "Sensation pure",
    "sensory-inputs/percept/determinate": "Percept déterminé (savikalpa)",
    "sensory-inputs/percept/determinate/object-recognition": "Reconnaissance d’objet",
    "sensory-inputs/percept/determinate/categorized": "Perception catégorisée",
    "sensory-inputs/percept/extraordinary": "Perception extraordinaire (alaukika)",
    "sensory-inputs/percept/extraordinary/generic": "Générique (sāmānyalakṣaṇa)",
    "sensory-inputs/percept/extraordinary/acquired": "Acquise (jñānalakṣaṇa)",
    "sensory-inputs/percept/extraordinary/yogic": "Yogique (yogaja)",
    "symbolic-entities": "Entités symboliques",
    "symbolic-entities/sign": "Signe (classification de Peirce)",
    "symbolic-entities/sign/icon": "Icône — par ressemblance",
    "symbolic-entities/sign/icon/image": "Image",
    "symbolic-entities/sign/icon/diagram": "Diagramme",
    "symbolic-entities/sign/icon/metaphor": "Métaphore",
    "symbolic-entities/sign/index": "Index — par connexion causale",
    "symbolic-entities/sign/index/symptom": "Symptôme",
    "symbolic-entities/sign/index/trace": "Trace",
    "symbolic-entities/sign/index/pointer": "Indicateur",
    "symbolic-entities/sign/symbol-conventional": "Symbole — par convention",
    "symbolic-entities/sign/symbol-conventional/word": "Mot",
    "symbolic-entities/sign/symbol-conventional/numeral": "Chiffre",
    "symbolic-entities/sign/symbol-conventional/logical-operator": "Opérateur logique",
    "symbolic-entities/symbol": "Symbole",
    "symbolic-entities/symbol/linguistic": "Symbole linguistique",
    "symbolic-entities/symbol/linguistic/phoneme": "Phonème",
    "symbolic-entities/symbol/linguistic/morpheme": "Morphème",
    "symbolic-entities/symbol/linguistic/lexeme": "Lexème",
    "symbolic-entities/symbol/mathematical": "Symbole mathématique",
    "symbolic-entities/symbol/logical": "Symbole logique",
    "symbolic-entities/symbol/iconographic": "Symbole iconographique",
    "symbolic-entities/data": "Données",
    "symbolic-entities/data/structured": "Données structurées",
    "symbolic-entities/data/structured/tabular": "Tabulaire",
    "symbolic-entities/data/structured/relational": "Relationnel",
    "symbolic-entities/data/semi-structured": "Données semi-structurées",
    "symbolic-entities/data/semi-structured/serialized": "JSON / XML / YAML",
    "symbolic-entities/data/unstructured": "Données non structurées",
    "symbolic-entities/data/unstructured/text": "Texte",
    "symbolic-entities/data/unstructured/image": "Image",
    "symbolic-entities/data/unstructured/audio": "Audio",
    "symbolic-entities/data/unstructured/video": "Vidéo",
    "symbolic-entities/data/quantitative": "Données quantitatives",
    "symbolic-entities/data/qualitative": "Données qualitatives",
    "symbolic-entities/code": "Code",
    "symbolic-entities/code/natural-language": "Code en langue naturelle",
    "symbolic-entities/code/formal-language": "Code en langage formel",
    "symbolic-entities/code/computer": "Code informatique",
    "symbolic-entities/code/cryptographic": "Code cryptographique",
    "symbolic-entities/inscription": "Inscription",
    "symbolic-entities/inscription/oral": "Orale",
    "symbolic-entities/inscription/manuscript": "Manuscrite",
    "symbolic-entities/inscription/print": "Imprimée",
    "symbolic-entities/inscription/digital": "Numérique",
    "semantic-contents": "Contenus sémantiques",
    "semantic-contents/concept": "Concept (taṣawwur)",
    "semantic-contents/concept/simple": "Concept simple",
    "semantic-contents/concept/compound": "Concept composé",
    "semantic-contents/concept/empirical": "Concept empirique",
    "semantic-contents/concept/empirical/observational": "Observationnel",
    "semantic-contents/concept/empirical/experimental": "Expérimental",
    "semantic-contents/concept/a-priori": "Concept a priori",
    "semantic-contents/concept/a-priori/logical": "Logique",
    "semantic-contents/concept/a-priori/mathematical": "Mathématique",
    "semantic-contents/concept/concrete": "Concept concret",
    "semantic-contents/concept/abstract": "Concept abstrait",
    "semantic-contents/idea": "Idée",
    "semantic-contents/idea/innate": "Idée innée (cartésienne)",
    "semantic-contents/idea/adventitious": "Idée adventice",
    "semantic-contents/idea/constructed": "Idée construite",
    "semantic-contents/idea/clear-distinct": "Idée claire et distincte",
    "semantic-contents/proposition": "Proposition (qaḍiyyah)",
    "semantic-contents/proposition/categorical": "Proposition catégorique",
    "semantic-contents/proposition/categorical/universal-affirmative": "Universelle affirmative",
    "semantic-contents/proposition/categorical/universal-negative": "Universelle négative",
    "semantic-contents/proposition/categorical/particular-affirmative": "Particulière affirmative",
    "semantic-contents/proposition/categorical/particular-negative": "Particulière négative",
    "semantic-contents/proposition/hypothetical": "Proposition hypothétique",
    "semantic-contents/proposition/hypothetical/conjunctive": "Conjonctive (muttaṣilah)",
    "semantic-contents/proposition/hypothetical/disjunctive": "Disjonctive (munfaṣilah)",
    "semantic-contents/proposition/modal": "Proposition modale",
    "semantic-contents/proposition/modal/necessary": "Nécessaire",
    "semantic-contents/proposition/modal/possible": "Possible",
    "semantic-contents/proposition/modal/impossible": "Impossible",
    "semantic-contents/information": "Information (DIKW T2)",
    "semantic-contents/information/syntactic": "Information syntaxique",
    "semantic-contents/information/semantic": "Information sémantique",
    "semantic-contents/information/pragmatic": "Information pragmatique",
    "semantic-contents/fact": "Fait (wāqiʿah)",
    "semantic-contents/fact/empirical": "Fait empirique",
    "semantic-contents/fact/mathematical": "Fait mathématique",
    "semantic-contents/fact/logical": "Fait logique",
    "semantic-contents/fact/historical": "Fait historique",
    "semantic-contents/fact/moral": "Fait moral",
    "semantic-contents/meaning": "Signification (maʿnā)",
    "semantic-contents/meaning/sense-vs-reference": "Sens vs. référence (Frege)",
    "semantic-contents/meaning/connotation-vs-denotation": "Connotation vs. dénotation",
    "semantic-contents/meaning/literal-vs-figurative": "Littéral vs. figuré",
    "semantic-contents/definition": "Définition (ḥadd)",
    "semantic-contents/definition/real": "Définition réelle",
    "semantic-contents/definition/nominal": "Définition nominale",
    "semantic-contents/definition/genus-differentia": "Genre-différence",
    "semantic-contents/definition/ostensive": "Définition ostensive",
    "epistemic-states": "États épistémiques",
    "epistemic-states/compound-ignorance": "Ignorance composée",
    "epistemic-states/simple-ignorance": "Ignorance simple",
    "epistemic-states/illusion": "Illusion (wahm)",
    "epistemic-states/illusion/perceptual": "Illusion perceptive",
    "epistemic-states/illusion/cognitive": "Illusion cognitive",
    "epistemic-states/doubt": "Doute (shakk)",
    "epistemic-states/doubt/methodological": "Doute méthodologique",
    "epistemic-states/doubt/habitual": "Doute habituel",
    "epistemic-states/doubt/equipoised": "Doute équilibré",
    "epistemic-states/opinion": "Opinion (ẓann)",
    "epistemic-states/opinion/probable": "Opinion probable",
    "epistemic-states/opinion/well-grounded": "Opinion bien fondée",
    "epistemic-states/opinion/dispositional": "Opinion dispositionnelle",
    "epistemic-states/belief": "Croyance (iʿtiqād / taṣdīq)",
    "epistemic-states/belief/occurrent": "Croyance occurrente",
    "epistemic-states/belief/dispositional": "Croyance dispositionnelle",
    "epistemic-states/belief/faith": "Foi (īmān)",
    "epistemic-states/knowledge": "Connaissance (ʿilm / maʿrifah)",
    "epistemic-states/knowledge/by-mode": "Par mode de représentation",
    "epistemic-states/knowledge/by-mode/acquired": "Acquise (al-ʿilm al-ḥuṣūlī)",
    "epistemic-states/knowledge/by-mode/presential": "Présentielle (al-ʿilm al-ḥuḍūrī)",
    "epistemic-states/knowledge/by-content": "Par type de contenu",
    "epistemic-states/knowledge/by-content/propositional": "Propositionnelle (savoir-que)",
    "epistemic-states/knowledge/by-content/propositional/a-priori-analytic": "A priori — analytique",
    "epistemic-states/knowledge/by-content/propositional/a-priori-synthetic": "A priori — synthétique",
    "epistemic-states/knowledge/by-content/propositional/a-posteriori-empirical": "A posteriori — empirique",
    "epistemic-states/knowledge/by-content/propositional/a-posteriori-testimonial": "A posteriori — testimoniale",
    "epistemic-states/knowledge/by-content/procedural": "Procédurale (savoir-faire)",
    "epistemic-states/knowledge/by-content/procedural/motor": "Compétence motrice",
    "epistemic-states/knowledge/by-content/procedural/cognitive": "Compétence cognitive",
    "epistemic-states/knowledge/by-content/procedural/social": "Compétence sociale",
    "epistemic-states/knowledge/by-content/acquaintance": "Connaissance directe (savoir-de)",
    "epistemic-states/knowledge/by-content/acquaintance/direct-experience": "Par expérience directe",
    "epistemic-states/knowledge/by-content/acquaintance/memory": "Par mémoire",
    "epistemic-states/knowledge/by-content/tacit": "Tacite (Polanyi)",
    "epistemic-states/knowledge/by-source": "Par source",
    "epistemic-states/knowledge/by-source/sensory": "Connaissance sensorielle",
    "epistemic-states/knowledge/by-source/rational": "Connaissance rationnelle",
    "epistemic-states/knowledge/by-source/testimonial": "Connaissance testimoniale",
    "epistemic-states/knowledge/by-source/revelatory": "Connaissance révélée",
    "epistemic-states/certainty": "Certitude (yaqīn)",
    "epistemic-states/certainty/logical": "Certitude logique",
    "epistemic-states/certainty/mathematical": "Certitude mathématique",
    "epistemic-states/certainty/metaphysical": "Certitude métaphysique",
    "epistemic-states/certainty/moral": "Certitude morale",
    "epistemic-states/certainty/religious": "Certitude religieuse",
    "epistemic-states/certainty/religious/ilm-al-yaqin": "ʿIlm al-yaqīn — savoir de la certitude",
    "epistemic-states/certainty/religious/ayn-al-yaqin": "ʿAyn al-yaqīn — œil de la certitude",
    "epistemic-states/certainty/religious/haqq-al-yaqin": "Ḥaqq al-yaqīn — vérité de la certitude",
    "higher-order-constructs": "Constructions d’ordre supérieur",
    "higher-order-constructs/hypothesis": "Hypothèse (faraḍiyyah)",
    "higher-order-constructs/hypothesis/working": "Hypothèse de travail",
    "higher-order-constructs/hypothesis/statistical": "Hypothèse statistique",
    "higher-order-constructs/hypothesis/statistical/null": "Hypothèse nulle",
    "higher-order-constructs/hypothesis/statistical/alternative": "Hypothèse alternative",
    "higher-order-constructs/hypothesis/causal": "Hypothèse causale",
    "higher-order-constructs/theory": "Théorie (naẓariyyah)",
    "higher-order-constructs/theory/empirical": "Théorie empirique",
    "higher-order-constructs/theory/empirical/descriptive": "Descriptive",
    "higher-order-constructs/theory/empirical/explanatory": "Explicative",
    "higher-order-constructs/theory/empirical/predictive": "Prédictive",
    "higher-order-constructs/theory/formal": "Théorie formelle",
    "higher-order-constructs/theory/normative": "Théorie normative",
    "higher-order-constructs/model": "Modèle (namūdhaj)",
    "higher-order-constructs/model/physical": "Modèle physique",
    "higher-order-constructs/model/mathematical": "Modèle mathématique",
    "higher-order-constructs/model/computational": "Modèle computationnel",
    "higher-order-constructs/model/conceptual": "Modèle conceptuel",
    "higher-order-constructs/law": "Loi (qānūn)",
    "higher-order-constructs/law/natural": "Loi naturelle",
    "higher-order-constructs/law/natural/universal": "Loi universelle",
    "higher-order-constructs/law/natural/statistical": "Loi statistique",
    "higher-order-constructs/law/logical": "Loi logique",
    "higher-order-constructs/law/logical/identity": "Identité",
    "higher-order-constructs/law/logical/non-contradiction": "Non-contradiction",
    "higher-order-constructs/law/logical/excluded-middle": "Tiers exclu",
    "higher-order-constructs/law/divine": "Loi divine (sharīʿah)",
    "higher-order-constructs/law/positive": "Loi positive",
    "higher-order-constructs/doctrine": "Doctrine (madhhab)",
    "higher-order-constructs/doctrine/religious": "Doctrine religieuse",
    "higher-order-constructs/doctrine/philosophical": "Doctrine philosophique",
    "higher-order-constructs/doctrine/scientific": "Doctrine scientifique",
    "higher-order-constructs/insight": "Perspicacité (baṣīrah)",
    "higher-order-constructs/insight/aesthetic": "Perspicacité esthétique",
    "higher-order-constructs/insight/mystical": "Perspicacité mystique",
    "higher-order-constructs/insight/scientific": "Perspicacité scientifique",
    "higher-order-constructs/wisdom": "Sagesse (ḥikmah)",
    "higher-order-constructs/wisdom/theoretical": "Sagesse théorique (sophia)",
    "higher-order-constructs/wisdom/practical": "Sagesse pratique (phronēsis)",
    "higher-order-constructs/wisdom/productive-craft": "Métier productif (technē)",
    "higher-order-constructs/wisdom/spiritual": "Sagesse spirituelle",
    "higher-order-constructs/worldview": "Vision du monde (ruʾyah kawniyyah)",
    "higher-order-constructs/worldview/religious": "Vision religieuse du monde",
    "higher-order-constructs/worldview/secular": "Vision séculière du monde",
    "higher-order-constructs/worldview/syncretic": "Vision syncrétique du monde",
    "perception": "Perception / Sensation",
    "perception/external": "Perception externe",
    "perception/internal": "Perception interne",
    "perception/self": "Perception de soi",
    "perception/extraordinary": "Perception extraordinaire",
    "inference": "Inférence / Raison",
    "inference/deductive": "Inférence déductive",
    "inference/inductive": "Inférence inductive",
    "inference/abductive": "Inférence abductive",
    "inference/necessary": "Raison nécessaire",
    "inference/speculative": "Raison spéculative",
    "testimony": "Témoignage",
    "testimony/direct-witness": "Témoignage de témoin direct",
    "testimony/reported": "Témoignage rapporté",
    "testimony/authoritative": "Témoignage faisant autorité",
    "testimony/scriptural": "Témoignage scripturaire",
    "mass-transmission": "Transmission massive (al-tawatur)",
    "mass-transmission/verbal": "Transmission massive verbale",
    "mass-transmission/meaning": "Transmission massive par sens",
    "mass-transmission/practical": "Transmission massive pratique",
    "comparison": "Comparaison / Analogie",
    "comparison/ratio-legis": "Analogie par ratio legis",
    "comparison/indication": "Analogie par indication",
    "comparison/resemblance": "Analogie par ressemblance",
    "comparison/a-fortiori": "Analogie a fortiori",
    "postulation": "Postulation / IBE",
    "postulation/from-perceived": "À partir d’un fait perçu",
    "postulation/from-heard": "À partir d’un fait entendu",
    "postulation/ibe": "Inférence à la meilleure explication",
    "non-apprehension": "Non-appréhension",
    "non-apprehension/prior": "Absence antérieure",
    "non-apprehension/posterior": "Absence postérieure",
    "non-apprehension/mutual": "Absence mutuelle",
    "non-apprehension/absolute": "Absence absolue",
    "memory": "Mémoire",
    "memory/recollection": "Souvenir",
    "memory/recognition": "Reconnaissance",
    "memory/episodic": "Mémoire épisodique",
    "memory/semantic": "Mémoire sémantique",
    "innate-disposition": "Disposition innée / Intuition",
    "innate-disposition/primordial": "Disposition primordiale (sunnite)",
    "innate-disposition/first-principles": "Intuition des premiers principes",
    "innate-disposition/moral": "Connaissance morale innée",
    "innate-disposition/axioms": "Axiomes évidents",
    "inspiration": "Inspiration / Appréhension mystique",
    "inspiration/ilham": "Ilhām (inspiration)",
    "inspiration/kashf": "Kashf (dévoilement)",
    "inspiration/dream-vision": "Vision onirique véridique",
    "revelation": "Révélation",
    "revelation/recited": "Révélation récitée (Coran)",
    "revelation/non-recited": "Révélation non récitée (Sunna)",
    "revelation/modes-of-receiving": "Modes de réception de la révélation",
    "unclassifiable": "Non classifiable",
}


# =============================================================================
# PT — Portuguese (European Portuguese conventions)
# =============================================================================
PT = {
    "epistemic-content": "Conteúdo epistémico",
    "sensory-inputs": "Entradas sensoriais",
    "sensory-inputs/signal": "Sinal",
    "sensory-inputs/signal/physical": "Sinal físico",
    "sensory-inputs/signal/physical/electromagnetic": "Eletromagnético",
    "sensory-inputs/signal/physical/acoustic": "Acústico",
    "sensory-inputs/signal/physical/mechanical": "Mecânico",
    "sensory-inputs/signal/physical/chemical": "Químico",
    "sensory-inputs/signal/biological": "Sinal biológico",
    "sensory-inputs/signal/biological/neural": "Neural",
    "sensory-inputs/signal/biological/hormonal": "Hormonal",
    "sensory-inputs/signal/biological/bioelectric": "Bioelétrico",
    "sensory-inputs/stimulus": "Estímulo",
    "sensory-inputs/stimulus/distal": "Estímulo distal",
    "sensory-inputs/stimulus/proximal": "Estímulo proximal",
    "sensory-inputs/stimulus/conditioned": "Estímulo condicionado",
    "sensory-inputs/stimulus/unconditioned": "Estímulo incondicionado",
    "sensory-inputs/sense-datum": "Dado sensorial",
    "sensory-inputs/sense-datum/visual": "Qualia visual",
    "sensory-inputs/sense-datum/auditory": "Qualia auditiva",
    "sensory-inputs/sense-datum/tactile": "Qualia tátil",
    "sensory-inputs/sense-datum/olfactory": "Qualia olfativa",
    "sensory-inputs/sense-datum/gustatory": "Qualia gustativa",
    "sensory-inputs/sense-datum/proprioceptive": "Qualia propriocetiva",
    "sensory-inputs/percept": "Perceto",
    "sensory-inputs/percept/indeterminate": "Perceto indeterminado (nirvikalpa)",
    "sensory-inputs/percept/indeterminate/pure-sensation": "Sensação pura",
    "sensory-inputs/percept/determinate": "Perceto determinado (savikalpa)",
    "sensory-inputs/percept/determinate/object-recognition": "Reconhecimento de objetos",
    "sensory-inputs/percept/determinate/categorized": "Perceção categorizada",
    "sensory-inputs/percept/extraordinary": "Perceção extraordinária (alaukika)",
    "sensory-inputs/percept/extraordinary/generic": "Genérica (sāmānyalakṣaṇa)",
    "sensory-inputs/percept/extraordinary/acquired": "Adquirida (jñānalakṣaṇa)",
    "sensory-inputs/percept/extraordinary/yogic": "Iogue (yogaja)",
    "symbolic-entities": "Entidades simbólicas",
    "symbolic-entities/sign": "Signo (classificação de Peirce)",
    "symbolic-entities/sign/icon": "Ícone — por semelhança",
    "symbolic-entities/sign/icon/image": "Imagem",
    "symbolic-entities/sign/icon/diagram": "Diagrama",
    "symbolic-entities/sign/icon/metaphor": "Metáfora",
    "symbolic-entities/sign/index": "Índice — por conexão causal",
    "symbolic-entities/sign/index/symptom": "Sintoma",
    "symbolic-entities/sign/index/trace": "Vestígio",
    "symbolic-entities/sign/index/pointer": "Apontador",
    "symbolic-entities/sign/symbol-conventional": "Símbolo — por convenção",
    "symbolic-entities/sign/symbol-conventional/word": "Palavra",
    "symbolic-entities/sign/symbol-conventional/numeral": "Numeral",
    "symbolic-entities/sign/symbol-conventional/logical-operator": "Operador lógico",
    "symbolic-entities/symbol": "Símbolo",
    "symbolic-entities/symbol/linguistic": "Símbolo linguístico",
    "symbolic-entities/symbol/linguistic/phoneme": "Fonema",
    "symbolic-entities/symbol/linguistic/morpheme": "Morfema",
    "symbolic-entities/symbol/linguistic/lexeme": "Lexema",
    "symbolic-entities/symbol/mathematical": "Símbolo matemático",
    "symbolic-entities/symbol/logical": "Símbolo lógico",
    "symbolic-entities/symbol/iconographic": "Símbolo iconográfico",
    "symbolic-entities/data": "Dados",
    "symbolic-entities/data/structured": "Dados estruturados",
    "symbolic-entities/data/structured/tabular": "Tabular",
    "symbolic-entities/data/structured/relational": "Relacional",
    "symbolic-entities/data/semi-structured": "Dados semiestruturados",
    "symbolic-entities/data/semi-structured/serialized": "JSON / XML / YAML",
    "symbolic-entities/data/unstructured": "Dados não estruturados",
    "symbolic-entities/data/unstructured/text": "Texto",
    "symbolic-entities/data/unstructured/image": "Imagem",
    "symbolic-entities/data/unstructured/audio": "Áudio",
    "symbolic-entities/data/unstructured/video": "Vídeo",
    "symbolic-entities/data/quantitative": "Dados quantitativos",
    "symbolic-entities/data/qualitative": "Dados qualitativos",
    "symbolic-entities/code": "Código",
    "symbolic-entities/code/natural-language": "Código em linguagem natural",
    "symbolic-entities/code/formal-language": "Código em linguagem formal",
    "symbolic-entities/code/computer": "Código informático",
    "symbolic-entities/code/cryptographic": "Código criptográfico",
    "symbolic-entities/inscription": "Inscrição",
    "symbolic-entities/inscription/oral": "Oral",
    "symbolic-entities/inscription/manuscript": "Manuscrita",
    "symbolic-entities/inscription/print": "Impressa",
    "symbolic-entities/inscription/digital": "Digital",
    "semantic-contents": "Conteúdos semânticos",
    "semantic-contents/concept": "Conceito (taṣawwur)",
    "semantic-contents/concept/simple": "Conceito simples",
    "semantic-contents/concept/compound": "Conceito composto",
    "semantic-contents/concept/empirical": "Conceito empírico",
    "semantic-contents/concept/empirical/observational": "Observacional",
    "semantic-contents/concept/empirical/experimental": "Experimental",
    "semantic-contents/concept/a-priori": "Conceito a priori",
    "semantic-contents/concept/a-priori/logical": "Lógico",
    "semantic-contents/concept/a-priori/mathematical": "Matemático",
    "semantic-contents/concept/concrete": "Conceito concreto",
    "semantic-contents/concept/abstract": "Conceito abstrato",
    "semantic-contents/idea": "Ideia",
    "semantic-contents/idea/innate": "Ideia inata (cartesiana)",
    "semantic-contents/idea/adventitious": "Ideia adventícia",
    "semantic-contents/idea/constructed": "Ideia construída",
    "semantic-contents/idea/clear-distinct": "Ideia clara e distinta",
    "semantic-contents/proposition": "Proposição (qaḍiyyah)",
    "semantic-contents/proposition/categorical": "Proposição categórica",
    "semantic-contents/proposition/categorical/universal-affirmative": "Universal afirmativa",
    "semantic-contents/proposition/categorical/universal-negative": "Universal negativa",
    "semantic-contents/proposition/categorical/particular-affirmative": "Particular afirmativa",
    "semantic-contents/proposition/categorical/particular-negative": "Particular negativa",
    "semantic-contents/proposition/hypothetical": "Proposição hipotética",
    "semantic-contents/proposition/hypothetical/conjunctive": "Conjuntiva (muttaṣilah)",
    "semantic-contents/proposition/hypothetical/disjunctive": "Disjuntiva (munfaṣilah)",
    "semantic-contents/proposition/modal": "Proposição modal",
    "semantic-contents/proposition/modal/necessary": "Necessária",
    "semantic-contents/proposition/modal/possible": "Possível",
    "semantic-contents/proposition/modal/impossible": "Impossível",
    "semantic-contents/information": "Informação (DIKW T2)",
    "semantic-contents/information/syntactic": "Informação sintática",
    "semantic-contents/information/semantic": "Informação semântica",
    "semantic-contents/information/pragmatic": "Informação pragmática",
    "semantic-contents/fact": "Facto (wāqiʿah)",
    "semantic-contents/fact/empirical": "Facto empírico",
    "semantic-contents/fact/mathematical": "Facto matemático",
    "semantic-contents/fact/logical": "Facto lógico",
    "semantic-contents/fact/historical": "Facto histórico",
    "semantic-contents/fact/moral": "Facto moral",
    "semantic-contents/meaning": "Significado (maʿnā)",
    "semantic-contents/meaning/sense-vs-reference": "Sentido vs. referência (Frege)",
    "semantic-contents/meaning/connotation-vs-denotation": "Conotação vs. denotação",
    "semantic-contents/meaning/literal-vs-figurative": "Literal vs. figurado",
    "semantic-contents/definition": "Definição (ḥadd)",
    "semantic-contents/definition/real": "Definição real",
    "semantic-contents/definition/nominal": "Definição nominal",
    "semantic-contents/definition/genus-differentia": "Género-diferença",
    "semantic-contents/definition/ostensive": "Definição ostensiva",
    "epistemic-states": "Estados epistémicos",
    "epistemic-states/compound-ignorance": "Ignorância composta",
    "epistemic-states/simple-ignorance": "Ignorância simples",
    "epistemic-states/illusion": "Ilusão (wahm)",
    "epistemic-states/illusion/perceptual": "Ilusão percetiva",
    "epistemic-states/illusion/cognitive": "Ilusão cognitiva",
    "epistemic-states/doubt": "Dúvida (shakk)",
    "epistemic-states/doubt/methodological": "Dúvida metodológica",
    "epistemic-states/doubt/habitual": "Dúvida habitual",
    "epistemic-states/doubt/equipoised": "Dúvida equilibrada",
    "epistemic-states/opinion": "Opinião (ẓann)",
    "epistemic-states/opinion/probable": "Opinião provável",
    "epistemic-states/opinion/well-grounded": "Opinião bem fundamentada",
    "epistemic-states/opinion/dispositional": "Opinião disposicional",
    "epistemic-states/belief": "Crença (iʿtiqād / taṣdīq)",
    "epistemic-states/belief/occurrent": "Crença ocorrente",
    "epistemic-states/belief/dispositional": "Crença disposicional",
    "epistemic-states/belief/faith": "Fé (īmān)",
    "epistemic-states/knowledge": "Conhecimento (ʿilm / maʿrifah)",
    "epistemic-states/knowledge/by-mode": "Por modo de representação",
    "epistemic-states/knowledge/by-mode/acquired": "Adquirido (al-ʿilm al-ḥuṣūlī)",
    "epistemic-states/knowledge/by-mode/presential": "Presencial (al-ʿilm al-ḥuḍūrī)",
    "epistemic-states/knowledge/by-content": "Por tipo de conteúdo",
    "epistemic-states/knowledge/by-content/propositional": "Proposicional (saber-que)",
    "epistemic-states/knowledge/by-content/propositional/a-priori-analytic": "A priori — analítico",
    "epistemic-states/knowledge/by-content/propositional/a-priori-synthetic": "A priori — sintético",
    "epistemic-states/knowledge/by-content/propositional/a-posteriori-empirical": "A posteriori — empírico",
    "epistemic-states/knowledge/by-content/propositional/a-posteriori-testimonial": "A posteriori — testemunhal",
    "epistemic-states/knowledge/by-content/procedural": "Procedimental (saber-como)",
    "epistemic-states/knowledge/by-content/procedural/motor": "Habilidade motora",
    "epistemic-states/knowledge/by-content/procedural/cognitive": "Habilidade cognitiva",
    "epistemic-states/knowledge/by-content/procedural/social": "Habilidade social",
    "epistemic-states/knowledge/by-content/acquaintance": "Conhecimento direto (saber-de)",
    "epistemic-states/knowledge/by-content/acquaintance/direct-experience": "Por experiência direta",
    "epistemic-states/knowledge/by-content/acquaintance/memory": "Por memória",
    "epistemic-states/knowledge/by-content/tacit": "Tácito (Polanyi)",
    "epistemic-states/knowledge/by-source": "Por fonte",
    "epistemic-states/knowledge/by-source/sensory": "Conhecimento sensorial",
    "epistemic-states/knowledge/by-source/rational": "Conhecimento racional",
    "epistemic-states/knowledge/by-source/testimonial": "Conhecimento testemunhal",
    "epistemic-states/knowledge/by-source/revelatory": "Conhecimento revelado",
    "epistemic-states/certainty": "Certeza (yaqīn)",
    "epistemic-states/certainty/logical": "Certeza lógica",
    "epistemic-states/certainty/mathematical": "Certeza matemática",
    "epistemic-states/certainty/metaphysical": "Certeza metafísica",
    "epistemic-states/certainty/moral": "Certeza moral",
    "epistemic-states/certainty/religious": "Certeza religiosa",
    "epistemic-states/certainty/religious/ilm-al-yaqin": "ʿIlm al-yaqīn — conhecimento da certeza",
    "epistemic-states/certainty/religious/ayn-al-yaqin": "ʿAyn al-yaqīn — olho da certeza",
    "epistemic-states/certainty/religious/haqq-al-yaqin": "Ḥaqq al-yaqīn — verdade da certeza",
    "higher-order-constructs": "Construções de ordem superior",
    "higher-order-constructs/hypothesis": "Hipótese (faraḍiyyah)",
    "higher-order-constructs/hypothesis/working": "Hipótese de trabalho",
    "higher-order-constructs/hypothesis/statistical": "Hipótese estatística",
    "higher-order-constructs/hypothesis/statistical/null": "Hipótese nula",
    "higher-order-constructs/hypothesis/statistical/alternative": "Hipótese alternativa",
    "higher-order-constructs/hypothesis/causal": "Hipótese causal",
    "higher-order-constructs/theory": "Teoria (naẓariyyah)",
    "higher-order-constructs/theory/empirical": "Teoria empírica",
    "higher-order-constructs/theory/empirical/descriptive": "Descritiva",
    "higher-order-constructs/theory/empirical/explanatory": "Explicativa",
    "higher-order-constructs/theory/empirical/predictive": "Preditiva",
    "higher-order-constructs/theory/formal": "Teoria formal",
    "higher-order-constructs/theory/normative": "Teoria normativa",
    "higher-order-constructs/model": "Modelo (namūdhaj)",
    "higher-order-constructs/model/physical": "Modelo físico",
    "higher-order-constructs/model/mathematical": "Modelo matemático",
    "higher-order-constructs/model/computational": "Modelo computacional",
    "higher-order-constructs/model/conceptual": "Modelo conceptual",
    "higher-order-constructs/law": "Lei (qānūn)",
    "higher-order-constructs/law/natural": "Lei natural",
    "higher-order-constructs/law/natural/universal": "Lei universal",
    "higher-order-constructs/law/natural/statistical": "Lei estatística",
    "higher-order-constructs/law/logical": "Lei lógica",
    "higher-order-constructs/law/logical/identity": "Identidade",
    "higher-order-constructs/law/logical/non-contradiction": "Não contradição",
    "higher-order-constructs/law/logical/excluded-middle": "Terceiro excluído",
    "higher-order-constructs/law/divine": "Lei divina (sharīʿah)",
    "higher-order-constructs/law/positive": "Lei positiva",
    "higher-order-constructs/doctrine": "Doutrina (madhhab)",
    "higher-order-constructs/doctrine/religious": "Doutrina religiosa",
    "higher-order-constructs/doctrine/philosophical": "Doutrina filosófica",
    "higher-order-constructs/doctrine/scientific": "Doutrina científica",
    "higher-order-constructs/insight": "Perspicácia (baṣīrah)",
    "higher-order-constructs/insight/aesthetic": "Perspicácia estética",
    "higher-order-constructs/insight/mystical": "Perspicácia mística",
    "higher-order-constructs/insight/scientific": "Perspicácia científica",
    "higher-order-constructs/wisdom": "Sabedoria (ḥikmah)",
    "higher-order-constructs/wisdom/theoretical": "Sabedoria teórica (sophia)",
    "higher-order-constructs/wisdom/practical": "Sabedoria prática (phronēsis)",
    "higher-order-constructs/wisdom/productive-craft": "Ofício produtivo (technē)",
    "higher-order-constructs/wisdom/spiritual": "Sabedoria espiritual",
    "higher-order-constructs/worldview": "Cosmovisão (ruʾyah kawniyyah)",
    "higher-order-constructs/worldview/religious": "Cosmovisão religiosa",
    "higher-order-constructs/worldview/secular": "Cosmovisão secular",
    "higher-order-constructs/worldview/syncretic": "Cosmovisão sincrética",
    "perception": "Perceção / Sensação",
    "perception/external": "Perceção externa",
    "perception/internal": "Perceção interna",
    "perception/self": "Autoperceção",
    "perception/extraordinary": "Perceção extraordinária",
    "inference": "Inferência / Razão",
    "inference/deductive": "Inferência dedutiva",
    "inference/inductive": "Inferência indutiva",
    "inference/abductive": "Inferência abdutiva",
    "inference/necessary": "Razão necessária",
    "inference/speculative": "Razão especulativa",
    "testimony": "Testemunho",
    "testimony/direct-witness": "Testemunho de testemunha direta",
    "testimony/reported": "Testemunho relatado",
    "testimony/authoritative": "Testemunho autoritativo",
    "testimony/scriptural": "Testemunho escritural",
    "mass-transmission": "Transmissão massiva (al-tawatur)",
    "mass-transmission/verbal": "Transmissão massiva verbal",
    "mass-transmission/meaning": "Transmissão massiva por significado",
    "mass-transmission/practical": "Transmissão massiva prática",
    "comparison": "Comparação / Analogia",
    "comparison/ratio-legis": "Analogia por ratio legis",
    "comparison/indication": "Analogia por indicação",
    "comparison/resemblance": "Analogia por semelhança",
    "comparison/a-fortiori": "Analogia a fortiori",
    "postulation": "Postulação / IBE",
    "postulation/from-perceived": "A partir de facto percebido",
    "postulation/from-heard": "A partir de facto ouvido",
    "postulation/ibe": "Inferência para a melhor explicação",
    "non-apprehension": "Não apreensão",
    "non-apprehension/prior": "Ausência prévia",
    "non-apprehension/posterior": "Ausência posterior",
    "non-apprehension/mutual": "Ausência mútua",
    "non-apprehension/absolute": "Ausência absoluta",
    "memory": "Memória",
    "memory/recollection": "Recordação",
    "memory/recognition": "Reconhecimento",
    "memory/episodic": "Memória episódica",
    "memory/semantic": "Memória semântica",
    "innate-disposition": "Disposição inata / Intuição",
    "innate-disposition/primordial": "Disposição primordial (sunita)",
    "innate-disposition/first-principles": "Intuição dos primeiros princípios",
    "innate-disposition/moral": "Conhecimento moral inato",
    "innate-disposition/axioms": "Axiomas autoevidentes",
    "inspiration": "Inspiração / Apreensão mística",
    "inspiration/ilham": "Ilhām (inspiração)",
    "inspiration/kashf": "Kashf (revelação)",
    "inspiration/dream-vision": "Visão onírica verdadeira",
    "revelation": "Revelação",
    "revelation/recited": "Revelação recitada (Alcorão)",
    "revelation/non-recited": "Revelação não recitada (Suna)",
    "revelation/modes-of-receiving": "Modos de receção da revelação",
    "unclassifiable": "Não classificável",
}


LOCALES = {"de": DE, "es": ES, "fr": FR, "pt": PT}


def apply_taxonomy(locale: str, translations: dict) -> tuple[int, bool]:
    """Insert/replace cece.taxonomy in src/lib/i18n/<locale>.json.

    Returns (count, was_replaced). Preserves cece key order — taxonomy
    goes after INSERT_AFTER ('disambiguation'), or appended at the end of
    cece if disambiguation is missing.
    """
    path = LOCALE_DIR / f"{locale}.json"
    with path.open("r", encoding="utf-8") as f:
        data = json.load(f)
    cece = data.setdefault("cece", {})
    was_replaced = "taxonomy" in cece

    # Rebuild cece preserving order, dropping any prior taxonomy, then
    # inserting taxonomy right after INSERT_AFTER.
    new_cece = {}
    inserted = False
    for k, v in cece.items():
        if k == "taxonomy":
            continue  # drop old
        new_cece[k] = v
        if k == INSERT_AFTER and not inserted:
            new_cece["taxonomy"] = translations
            inserted = True
    if not inserted:
        new_cece["taxonomy"] = translations
    data["cece"] = new_cece

    with path.open("w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
        f.write("\n")
    return (len(translations), was_replaced)


def main():
    # Cross-check: every locale must mirror en.json's 277 keys exactly.
    en_path = LOCALE_DIR / "en.json"
    with en_path.open("r", encoding="utf-8") as f:
        en_data = json.load(f)
    en_keys = set(en_data["cece"]["taxonomy"].keys())
    if len(en_keys) != 277:
        print(f"ERROR: en.json cece.taxonomy has {len(en_keys)} keys (expected 277)")
        return

    for locale, translations in LOCALES.items():
        loc_keys = set(translations.keys())
        missing = en_keys - loc_keys
        extra = loc_keys - en_keys
        if missing:
            print(f"ERROR [{locale}]: missing {len(missing)} keys: {sorted(missing)[:5]}...")
            return
        if extra:
            print(f"ERROR [{locale}]: extra {len(extra)} keys: {sorted(extra)[:5]}...")
            return
        if len(translations) != 277:
            print(f"ERROR [{locale}]: has {len(translations)} keys (expected 277)")
            return

    # Apply.
    for locale, translations in LOCALES.items():
        count, replaced = apply_taxonomy(locale, translations)
        verb = "replaced" if replaced else "inserted"
        print(f"{locale}.json: cece.taxonomy {verb} ({count} keys)")

    # Final verification: re-read each file, parse JSON, count keys.
    print()
    print("--- verification ---")
    for locale in LOCALES:
        path = LOCALE_DIR / f"{locale}.json"
        with path.open("r", encoding="utf-8") as f:
            d = json.load(f)
        n = len(d.get("cece", {}).get("taxonomy", {}))
        status = "OK" if n == 277 else "FAIL"
        print(f"{status} {locale}.json: {n} taxonomy keys")


if __name__ == "__main__":
    main()
