#!/usr/bin/env python3
"""
MIG-022 §E.3.d — Backfill cece.taxonomy.* for 4 RTL+Indic locales:
  fa.json (Farsi), he.json (Hebrew), hi.json (Hindi), ur.json (Urdu).

Source of truth: en.json + ar.json already have the full 277-key block
(seeded by §E.3.a from the Rust struct). For fa/ur, Arabic is structurally
close — we adapt with Farsi/Urdu grammatical adjustments. For he/hi we
translate fresh from English.

Run:
    python lab/scripts/mig022_e3d_taxonomy_rtl_indic.py

Idempotent: replaces cece.taxonomy in each of the 4 locales every time.
"""
import json
from pathlib import Path

ROOT = Path(r"E:\مشاريع كلاود\Constellation")
LOCALES_DIR = ROOT / "src/lib/i18n"

# ---------------------------------------------------------------------------
# Translations
# Each dict has exactly 277 keys mirroring en.json's cece.taxonomy keys.
# ---------------------------------------------------------------------------

FA = {
    "epistemic-content": "محتوای معرفتی",
    "sensory-inputs": "ورودی‌های حسی",
    "sensory-inputs/signal": "سیگنال",
    "sensory-inputs/signal/physical": "سیگنال فیزیکی",
    "sensory-inputs/signal/physical/electromagnetic": "الکترومغناطیسی",
    "sensory-inputs/signal/physical/acoustic": "صوتی",
    "sensory-inputs/signal/physical/mechanical": "مکانیکی",
    "sensory-inputs/signal/physical/chemical": "شیمیایی",
    "sensory-inputs/signal/biological": "سیگنال زیستی",
    "sensory-inputs/signal/biological/neural": "عصبی",
    "sensory-inputs/signal/biological/hormonal": "هورمونی",
    "sensory-inputs/signal/biological/bioelectric": "زیست‌الکتریکی",
    "sensory-inputs/stimulus": "محرک",
    "sensory-inputs/stimulus/distal": "محرک دور",
    "sensory-inputs/stimulus/proximal": "محرک نزدیک",
    "sensory-inputs/stimulus/conditioned": "محرک شرطی",
    "sensory-inputs/stimulus/unconditioned": "محرک غیرشرطی",
    "sensory-inputs/sense-datum": "داده حسی",
    "sensory-inputs/sense-datum/visual": "کیفیات بصری",
    "sensory-inputs/sense-datum/auditory": "کیفیات شنیداری",
    "sensory-inputs/sense-datum/tactile": "کیفیات لامسه",
    "sensory-inputs/sense-datum/olfactory": "کیفیات بویایی",
    "sensory-inputs/sense-datum/gustatory": "کیفیات چشایی",
    "sensory-inputs/sense-datum/proprioceptive": "کیفیات حس عمقی",
    "sensory-inputs/percept": "ادراک حسی",
    "sensory-inputs/percept/indeterminate": "ادراک نامتعین (nirvikalpa)",
    "sensory-inputs/percept/indeterminate/pure-sensation": "احساس محض",
    "sensory-inputs/percept/determinate": "ادراک متعین (savikalpa)",
    "sensory-inputs/percept/determinate/object-recognition": "بازشناسی شیء",
    "sensory-inputs/percept/determinate/categorized": "ادراک طبقه‌بندی‌شده",
    "sensory-inputs/percept/extraordinary": "ادراک فوق‌العاده (alaukika)",
    "sensory-inputs/percept/extraordinary/generic": "عمومی (sāmānyalakṣaṇa)",
    "sensory-inputs/percept/extraordinary/acquired": "اکتسابی (jñānalakṣaṇa)",
    "sensory-inputs/percept/extraordinary/yogic": "یوگی (yogaja)",
    "symbolic-entities": "موجودیت‌های نمادین",
    "symbolic-entities/sign": "نشانه (طبقه‌بندی پیرس)",
    "symbolic-entities/sign/icon": "شمایل — به مشابهت",
    "symbolic-entities/sign/icon/image": "تصویر",
    "symbolic-entities/sign/icon/diagram": "نمودار",
    "symbolic-entities/sign/icon/metaphor": "استعاره",
    "symbolic-entities/sign/index": "نمایه — به ارتباط علّی",
    "symbolic-entities/sign/index/symptom": "نشانه (علامت)",
    "symbolic-entities/sign/index/trace": "اثر",
    "symbolic-entities/sign/index/pointer": "اشاره‌گر",
    "symbolic-entities/sign/symbol-conventional": "نماد قراردادی — به اصطلاح",
    "symbolic-entities/sign/symbol-conventional/word": "واژه",
    "symbolic-entities/sign/symbol-conventional/numeral": "عدد",
    "symbolic-entities/sign/symbol-conventional/logical-operator": "عملگر منطقی",
    "symbolic-entities/symbol": "نماد",
    "symbolic-entities/symbol/linguistic": "نماد زبانی",
    "symbolic-entities/symbol/linguistic/phoneme": "واج",
    "symbolic-entities/symbol/linguistic/morpheme": "تکواژ",
    "symbolic-entities/symbol/linguistic/lexeme": "واژگان",
    "symbolic-entities/symbol/mathematical": "نماد ریاضی",
    "symbolic-entities/symbol/logical": "نماد منطقی",
    "symbolic-entities/symbol/iconographic": "نماد شمایل‌نگارانه",
    "symbolic-entities/data": "داده",
    "symbolic-entities/data/structured": "داده ساخت‌یافته",
    "symbolic-entities/data/structured/tabular": "جدولی",
    "symbolic-entities/data/structured/relational": "رابطه‌ای",
    "symbolic-entities/data/semi-structured": "داده نیمه‌ساخت‌یافته",
    "symbolic-entities/data/semi-structured/serialized": "JSON / XML / YAML",
    "symbolic-entities/data/unstructured": "داده ساخت‌نیافته",
    "symbolic-entities/data/unstructured/text": "متن",
    "symbolic-entities/data/unstructured/image": "تصویر",
    "symbolic-entities/data/unstructured/audio": "صدا",
    "symbolic-entities/data/unstructured/video": "ویدیو",
    "symbolic-entities/data/quantitative": "داده کمّی",
    "symbolic-entities/data/qualitative": "داده کیفی",
    "symbolic-entities/code": "رمز",
    "symbolic-entities/code/natural-language": "رمز زبان طبیعی",
    "symbolic-entities/code/formal-language": "رمز زبان صوری",
    "symbolic-entities/code/computer": "رمز رایانه‌ای",
    "symbolic-entities/code/cryptographic": "رمز رمزنگاری",
    "symbolic-entities/inscription": "ثبت / کتیبه",
    "symbolic-entities/inscription/oral": "شفاهی",
    "symbolic-entities/inscription/manuscript": "دست‌نوشته",
    "symbolic-entities/inscription/print": "چاپی",
    "symbolic-entities/inscription/digital": "دیجیتال",
    "semantic-contents": "محتویات دلالی",
    "semantic-contents/concept": "مفهوم (taṣawwur)",
    "semantic-contents/concept/simple": "مفهوم بسیط",
    "semantic-contents/concept/compound": "مفهوم مرکب",
    "semantic-contents/concept/empirical": "مفهوم تجربی",
    "semantic-contents/concept/empirical/observational": "مشاهده‌ای",
    "semantic-contents/concept/empirical/experimental": "آزمایشی",
    "semantic-contents/concept/a-priori": "مفهوم پیشینی",
    "semantic-contents/concept/a-priori/logical": "منطقی",
    "semantic-contents/concept/a-priori/mathematical": "ریاضی",
    "semantic-contents/concept/concrete": "مفهوم عینی",
    "semantic-contents/concept/abstract": "مفهوم انتزاعی",
    "semantic-contents/idea": "ایده",
    "semantic-contents/idea/innate": "ایده فطری (دکارتی)",
    "semantic-contents/idea/adventitious": "ایده اکتسابی",
    "semantic-contents/idea/constructed": "ایده ساخته‌شده",
    "semantic-contents/idea/clear-distinct": "ایده واضح و متمایز",
    "semantic-contents/proposition": "قضیه (qaḍiyyah)",
    "semantic-contents/proposition/categorical": "قضیه حملی",
    "semantic-contents/proposition/categorical/universal-affirmative": "موجبه کلی",
    "semantic-contents/proposition/categorical/universal-negative": "سالبه کلی",
    "semantic-contents/proposition/categorical/particular-affirmative": "موجبه جزئی",
    "semantic-contents/proposition/categorical/particular-negative": "سالبه جزئی",
    "semantic-contents/proposition/hypothetical": "قضیه شرطی",
    "semantic-contents/proposition/hypothetical/conjunctive": "متصله (muttaṣilah)",
    "semantic-contents/proposition/hypothetical/disjunctive": "منفصله (munfaṣilah)",
    "semantic-contents/proposition/modal": "قضیه موجّهه",
    "semantic-contents/proposition/modal/necessary": "ضروری",
    "semantic-contents/proposition/modal/possible": "ممکن",
    "semantic-contents/proposition/modal/impossible": "ممتنع",
    "semantic-contents/information": "اطلاعات (DIKW T2)",
    "semantic-contents/information/syntactic": "اطلاعات نحوی",
    "semantic-contents/information/semantic": "اطلاعات معنایی",
    "semantic-contents/information/pragmatic": "اطلاعات کاربردی",
    "semantic-contents/fact": "واقعیت (wāqiʿah)",
    "semantic-contents/fact/empirical": "واقعیت تجربی",
    "semantic-contents/fact/mathematical": "واقعیت ریاضی",
    "semantic-contents/fact/logical": "واقعیت منطقی",
    "semantic-contents/fact/historical": "واقعیت تاریخی",
    "semantic-contents/fact/moral": "واقعیت اخلاقی",
    "semantic-contents/meaning": "معنا (maʿnā)",
    "semantic-contents/meaning/sense-vs-reference": "معنا در برابر مرجع (فرگه)",
    "semantic-contents/meaning/connotation-vs-denotation": "تضمین در برابر دلالت",
    "semantic-contents/meaning/literal-vs-figurative": "حقیقی در برابر مجازی",
    "semantic-contents/definition": "تعریف (ḥadd)",
    "semantic-contents/definition/real": "تعریف حقیقی",
    "semantic-contents/definition/nominal": "تعریف اسمی",
    "semantic-contents/definition/genus-differentia": "جنس و فصل",
    "semantic-contents/definition/ostensive": "تعریف اشاری",
    "epistemic-states": "حالات معرفتی",
    "epistemic-states/compound-ignorance": "جهل مرکب",
    "epistemic-states/simple-ignorance": "جهل بسیط",
    "epistemic-states/illusion": "وهم (wahm)",
    "epistemic-states/illusion/perceptual": "وهم ادراکی",
    "epistemic-states/illusion/cognitive": "وهم شناختی",
    "epistemic-states/doubt": "شک (shakk)",
    "epistemic-states/doubt/methodological": "شک روش‌شناختی",
    "epistemic-states/doubt/habitual": "شک عادتی",
    "epistemic-states/doubt/equipoised": "شک متساوی‌الطرفین",
    "epistemic-states/opinion": "ظن (ẓann)",
    "epistemic-states/opinion/probable": "ظن غالب",
    "epistemic-states/opinion/well-grounded": "ظن مستدل",
    "epistemic-states/opinion/dispositional": "ظن استعدادی",
    "epistemic-states/belief": "اعتقاد (iʿtiqād / taṣdīq)",
    "epistemic-states/belief/occurrent": "اعتقاد فعلی",
    "epistemic-states/belief/dispositional": "اعتقاد استعدادی",
    "epistemic-states/belief/faith": "ایمان (īmān)",
    "epistemic-states/knowledge": "علم / معرفت (ʿilm / maʿrifah)",
    "epistemic-states/knowledge/by-mode": "بر حسب نحوه بازنمایی",
    "epistemic-states/knowledge/by-mode/acquired": "حصولی (al-ʿilm al-ḥuṣūlī)",
    "epistemic-states/knowledge/by-mode/presential": "حضوری (al-ʿilm al-ḥuḍūrī)",
    "epistemic-states/knowledge/by-content": "بر حسب نوع محتوا",
    "epistemic-states/knowledge/by-content/propositional": "گزاره‌ای (دانستن-که)",
    "epistemic-states/knowledge/by-content/propositional/a-priori-analytic": "پیشینی — تحلیلی",
    "epistemic-states/knowledge/by-content/propositional/a-priori-synthetic": "پیشینی — ترکیبی",
    "epistemic-states/knowledge/by-content/propositional/a-posteriori-empirical": "پسینی — تجربی",
    "epistemic-states/knowledge/by-content/propositional/a-posteriori-testimonial": "پسینی — شهادتی",
    "epistemic-states/knowledge/by-content/procedural": "رویه‌ای (دانستن-چگونه)",
    "epistemic-states/knowledge/by-content/procedural/motor": "مهارت حرکتی",
    "epistemic-states/knowledge/by-content/procedural/cognitive": "مهارت شناختی",
    "epistemic-states/knowledge/by-content/procedural/social": "مهارت اجتماعی",
    "epistemic-states/knowledge/by-content/acquaintance": "آشنایی (دانستن-از)",
    "epistemic-states/knowledge/by-content/acquaintance/direct-experience": "از طریق تجربه مستقیم",
    "epistemic-states/knowledge/by-content/acquaintance/memory": "از طریق حافظه",
    "epistemic-states/knowledge/by-content/tacit": "ضمنی (پولانی)",
    "epistemic-states/knowledge/by-source": "بر حسب منبع",
    "epistemic-states/knowledge/by-source/sensory": "علم حسی",
    "epistemic-states/knowledge/by-source/rational": "علم عقلی",
    "epistemic-states/knowledge/by-source/testimonial": "علم خبری",
    "epistemic-states/knowledge/by-source/revelatory": "علم وحیانی",
    "epistemic-states/certainty": "یقین (yaqīn)",
    "epistemic-states/certainty/logical": "یقین منطقی",
    "epistemic-states/certainty/mathematical": "یقین ریاضی",
    "epistemic-states/certainty/metaphysical": "یقین متافیزیکی",
    "epistemic-states/certainty/moral": "یقین اخلاقی",
    "epistemic-states/certainty/religious": "یقین دینی",
    "epistemic-states/certainty/religious/ilm-al-yaqin": "علم الیقین — علم به یقین",
    "epistemic-states/certainty/religious/ayn-al-yaqin": "عین الیقین — چشم یقین",
    "epistemic-states/certainty/religious/haqq-al-yaqin": "حق الیقین — حقیقت یقین",
    "higher-order-constructs": "ساخت‌های مرتبه بالا",
    "higher-order-constructs/hypothesis": "فرضیه (faraḍiyyah)",
    "higher-order-constructs/hypothesis/working": "فرضیه کاری",
    "higher-order-constructs/hypothesis/statistical": "فرضیه آماری",
    "higher-order-constructs/hypothesis/statistical/null": "فرضیه صفر",
    "higher-order-constructs/hypothesis/statistical/alternative": "فرضیه جایگزین",
    "higher-order-constructs/hypothesis/causal": "فرضیه علّی",
    "higher-order-constructs/theory": "نظریه (naẓariyyah)",
    "higher-order-constructs/theory/empirical": "نظریه تجربی",
    "higher-order-constructs/theory/empirical/descriptive": "توصیفی",
    "higher-order-constructs/theory/empirical/explanatory": "تفسیری",
    "higher-order-constructs/theory/empirical/predictive": "پیش‌بینی‌کننده",
    "higher-order-constructs/theory/formal": "نظریه صوری",
    "higher-order-constructs/theory/normative": "نظریه هنجاری",
    "higher-order-constructs/model": "مدل (namūdhaj)",
    "higher-order-constructs/model/physical": "مدل فیزیکی",
    "higher-order-constructs/model/mathematical": "مدل ریاضی",
    "higher-order-constructs/model/computational": "مدل محاسباتی",
    "higher-order-constructs/model/conceptual": "مدل مفهومی",
    "higher-order-constructs/law": "قانون (qānūn)",
    "higher-order-constructs/law/natural": "قانون طبیعی",
    "higher-order-constructs/law/natural/universal": "قانون کلی",
    "higher-order-constructs/law/natural/statistical": "قانون آماری",
    "higher-order-constructs/law/logical": "قانون منطقی",
    "higher-order-constructs/law/logical/identity": "هوهویت",
    "higher-order-constructs/law/logical/non-contradiction": "عدم تناقض",
    "higher-order-constructs/law/logical/excluded-middle": "طرد شق ثالث",
    "higher-order-constructs/law/divine": "قانون الهی (sharīʿah)",
    "higher-order-constructs/law/positive": "قانون موضوعه",
    "higher-order-constructs/doctrine": "مذهب / دکترین (madhhab)",
    "higher-order-constructs/doctrine/religious": "دکترین دینی",
    "higher-order-constructs/doctrine/philosophical": "دکترین فلسفی",
    "higher-order-constructs/doctrine/scientific": "دکترین علمی",
    "higher-order-constructs/insight": "بصیرت (baṣīrah)",
    "higher-order-constructs/insight/aesthetic": "بصیرت زیبایی‌شناختی",
    "higher-order-constructs/insight/mystical": "بصیرت عرفانی",
    "higher-order-constructs/insight/scientific": "بصیرت علمی",
    "higher-order-constructs/wisdom": "حکمت (ḥikmah)",
    "higher-order-constructs/wisdom/theoretical": "حکمت نظری (sophia)",
    "higher-order-constructs/wisdom/practical": "حکمت عملی (phronēsis)",
    "higher-order-constructs/wisdom/productive-craft": "صنعت سازنده (technē)",
    "higher-order-constructs/wisdom/spiritual": "حکمت معنوی",
    "higher-order-constructs/worldview": "جهان‌بینی (ruʾyah kawniyyah)",
    "higher-order-constructs/worldview/religious": "جهان‌بینی دینی",
    "higher-order-constructs/worldview/secular": "جهان‌بینی سکولار",
    "higher-order-constructs/worldview/syncretic": "جهان‌بینی التقاطی",
    "perception": "ادراک / احساس",
    "perception/external": "ادراک بیرونی",
    "perception/internal": "ادراک درونی",
    "perception/self": "خودادراکی",
    "perception/extraordinary": "ادراک فوق‌العاده",
    "inference": "استنتاج / عقل",
    "inference/deductive": "استنتاج قیاسی",
    "inference/inductive": "استنتاج استقرایی",
    "inference/abductive": "استنتاج فرضی",
    "inference/necessary": "عقل ضروری",
    "inference/speculative": "عقل نظری",
    "testimony": "شهادت / خبر",
    "testimony/direct-witness": "شهادت مستقیم",
    "testimony/reported": "خبر منقول",
    "testimony/authoritative": "خبر ثقه",
    "testimony/scriptural": "نقل شرعی",
    "mass-transmission": "تواتر (al-tawatur)",
    "mass-transmission/verbal": "تواتر لفظی",
    "mass-transmission/meaning": "تواتر معنوی",
    "mass-transmission/practical": "تواتر عملی",
    "comparison": "قیاس (qiyas / anumana)",
    "comparison/ratio-legis": "قیاس علت",
    "comparison/indication": "قیاس دلالت",
    "comparison/resemblance": "قیاس شَبَه",
    "comparison/a-fortiori": "قیاس اولویت",
    "postulation": "استنباط افتراضی / IBE",
    "postulation/from-perceived": "از واقعه مشاهده‌شده",
    "postulation/from-heard": "از خبر شنیده‌شده",
    "postulation/ibe": "استدلال به بهترین تبیین",
    "non-apprehension": "عدم ادراک",
    "non-apprehension/prior": "عدم سابق",
    "non-apprehension/posterior": "عدم لاحق",
    "non-apprehension/mutual": "عدم متقابل",
    "non-apprehension/absolute": "عدم مطلق",
    "memory": "حافظه",
    "memory/recollection": "تذکر",
    "memory/recognition": "بازشناسی",
    "memory/episodic": "حافظه رویدادی",
    "memory/semantic": "حافظه معنایی",
    "innate-disposition": "فطرت / حدس",
    "innate-disposition/primordial": "فطرت آغازین (سنّی)",
    "innate-disposition/first-principles": "حدس اصول اولیه",
    "innate-disposition/moral": "معرفت اخلاقی فطری",
    "innate-disposition/axioms": "بدیهیات",
    "inspiration": "الهام / کشف عرفانی",
    "inspiration/ilham": "الهام (ilhām)",
    "inspiration/kashf": "کشف",
    "inspiration/dream-vision": "رؤیای صادقه",
    "revelation": "وحی",
    "revelation/recited": "وحی متلوّ (قرآن)",
    "revelation/non-recited": "وحی غیر متلوّ (سنّت)",
    "revelation/modes-of-receiving": "انحاء دریافت وحی",
    "unclassifiable": "غیر قابل طبقه‌بندی",
}

UR = {
    "epistemic-content": "علمیاتی مواد",
    "sensory-inputs": "حسی مدخلات",
    "sensory-inputs/signal": "اشارہ / سگنل",
    "sensory-inputs/signal/physical": "طبیعی سگنل",
    "sensory-inputs/signal/physical/electromagnetic": "برقی مقناطیسی",
    "sensory-inputs/signal/physical/acoustic": "صوتی",
    "sensory-inputs/signal/physical/mechanical": "میکانیکی",
    "sensory-inputs/signal/physical/chemical": "کیمیائی",
    "sensory-inputs/signal/biological": "حیاتی سگنل",
    "sensory-inputs/signal/biological/neural": "عصبی",
    "sensory-inputs/signal/biological/hormonal": "ہارمونی",
    "sensory-inputs/signal/biological/bioelectric": "حیاتی برقی",
    "sensory-inputs/stimulus": "محرک",
    "sensory-inputs/stimulus/distal": "دور کا محرک",
    "sensory-inputs/stimulus/proximal": "قریبی محرک",
    "sensory-inputs/stimulus/conditioned": "مشروط محرک",
    "sensory-inputs/stimulus/unconditioned": "غیر مشروط محرک",
    "sensory-inputs/sense-datum": "حسی معطیہ",
    "sensory-inputs/sense-datum/visual": "بصری کیفیات",
    "sensory-inputs/sense-datum/auditory": "سمعی کیفیات",
    "sensory-inputs/sense-datum/tactile": "لمسی کیفیات",
    "sensory-inputs/sense-datum/olfactory": "شامی کیفیات",
    "sensory-inputs/sense-datum/gustatory": "ذائقی کیفیات",
    "sensory-inputs/sense-datum/proprioceptive": "خود حسی کیفیات",
    "sensory-inputs/percept": "ادراک حسی",
    "sensory-inputs/percept/indeterminate": "غیر متعین ادراک (nirvikalpa)",
    "sensory-inputs/percept/indeterminate/pure-sensation": "محض احساس",
    "sensory-inputs/percept/determinate": "متعین ادراک (savikalpa)",
    "sensory-inputs/percept/determinate/object-recognition": "شے کی شناخت",
    "sensory-inputs/percept/determinate/categorized": "زمرہ بند ادراک",
    "sensory-inputs/percept/extraordinary": "غیر معمولی ادراک (alaukika)",
    "sensory-inputs/percept/extraordinary/generic": "عمومی (sāmānyalakṣaṇa)",
    "sensory-inputs/percept/extraordinary/acquired": "اکتسابی (jñānalakṣaṇa)",
    "sensory-inputs/percept/extraordinary/yogic": "یوگیہ (yogaja)",
    "symbolic-entities": "علامتی اشیاء",
    "symbolic-entities/sign": "نشان (پرس کی درجہ بندی)",
    "symbolic-entities/sign/icon": "آئیکن — مشابہت سے",
    "symbolic-entities/sign/icon/image": "تصویر",
    "symbolic-entities/sign/icon/diagram": "خاکہ",
    "symbolic-entities/sign/icon/metaphor": "استعارہ",
    "symbolic-entities/sign/index": "اشاریہ — سببی تعلق سے",
    "symbolic-entities/sign/index/symptom": "علامت",
    "symbolic-entities/sign/index/trace": "اثر",
    "symbolic-entities/sign/index/pointer": "اشارہ کنندہ",
    "symbolic-entities/sign/symbol-conventional": "علامت — اصطلاح سے",
    "symbolic-entities/sign/symbol-conventional/word": "لفظ",
    "symbolic-entities/sign/symbol-conventional/numeral": "عدد",
    "symbolic-entities/sign/symbol-conventional/logical-operator": "منطقی عامل",
    "symbolic-entities/symbol": "علامت",
    "symbolic-entities/symbol/linguistic": "لسانی علامت",
    "symbolic-entities/symbol/linguistic/phoneme": "صوتیہ",
    "symbolic-entities/symbol/linguistic/morpheme": "صرفیہ",
    "symbolic-entities/symbol/linguistic/lexeme": "لفظیہ",
    "symbolic-entities/symbol/mathematical": "ریاضیاتی علامت",
    "symbolic-entities/symbol/logical": "منطقی علامت",
    "symbolic-entities/symbol/iconographic": "آئیکنی علامت",
    "symbolic-entities/data": "ڈیٹا",
    "symbolic-entities/data/structured": "ساختہ شدہ ڈیٹا",
    "symbolic-entities/data/structured/tabular": "جدولی",
    "symbolic-entities/data/structured/relational": "رابطی",
    "symbolic-entities/data/semi-structured": "نیم ساختہ ڈیٹا",
    "symbolic-entities/data/semi-structured/serialized": "JSON / XML / YAML",
    "symbolic-entities/data/unstructured": "غیر ساختہ ڈیٹا",
    "symbolic-entities/data/unstructured/text": "متن",
    "symbolic-entities/data/unstructured/image": "تصویر",
    "symbolic-entities/data/unstructured/audio": "آڈیو",
    "symbolic-entities/data/unstructured/video": "ویڈیو",
    "symbolic-entities/data/quantitative": "مقداری ڈیٹا",
    "symbolic-entities/data/qualitative": "کیفی ڈیٹا",
    "symbolic-entities/code": "کوڈ",
    "symbolic-entities/code/natural-language": "فطری زبان کا کوڈ",
    "symbolic-entities/code/formal-language": "صوری زبان کا کوڈ",
    "symbolic-entities/code/computer": "کمپیوٹر کوڈ",
    "symbolic-entities/code/cryptographic": "خفیہ نگاری کا کوڈ",
    "symbolic-entities/inscription": "تحریر / کتبہ",
    "symbolic-entities/inscription/oral": "زبانی",
    "symbolic-entities/inscription/manuscript": "مخطوطہ",
    "symbolic-entities/inscription/print": "مطبوعہ",
    "symbolic-entities/inscription/digital": "ڈیجیٹل",
    "semantic-contents": "دلالی مواد",
    "semantic-contents/concept": "تصور (taṣawwur)",
    "semantic-contents/concept/simple": "سادہ تصور",
    "semantic-contents/concept/compound": "مرکب تصور",
    "semantic-contents/concept/empirical": "تجربی تصور",
    "semantic-contents/concept/empirical/observational": "مشاہداتی",
    "semantic-contents/concept/empirical/experimental": "تجرباتی",
    "semantic-contents/concept/a-priori": "قبلی تصور",
    "semantic-contents/concept/a-priori/logical": "منطقی",
    "semantic-contents/concept/a-priori/mathematical": "ریاضیاتی",
    "semantic-contents/concept/concrete": "ٹھوس تصور",
    "semantic-contents/concept/abstract": "تجریدی تصور",
    "semantic-contents/idea": "خیال",
    "semantic-contents/idea/innate": "فطری خیال (دکارتی)",
    "semantic-contents/idea/adventitious": "اکتسابی خیال",
    "semantic-contents/idea/constructed": "ساختہ خیال",
    "semantic-contents/idea/clear-distinct": "واضح اور ممتاز خیال",
    "semantic-contents/proposition": "قضیہ (qaḍiyyah)",
    "semantic-contents/proposition/categorical": "حملی قضیہ",
    "semantic-contents/proposition/categorical/universal-affirmative": "موجبہ کلیہ",
    "semantic-contents/proposition/categorical/universal-negative": "سالبہ کلیہ",
    "semantic-contents/proposition/categorical/particular-affirmative": "موجبہ جزئیہ",
    "semantic-contents/proposition/categorical/particular-negative": "سالبہ جزئیہ",
    "semantic-contents/proposition/hypothetical": "شرطی قضیہ",
    "semantic-contents/proposition/hypothetical/conjunctive": "متصلہ (muttaṣilah)",
    "semantic-contents/proposition/hypothetical/disjunctive": "منفصلہ (munfaṣilah)",
    "semantic-contents/proposition/modal": "موجہہ قضیہ",
    "semantic-contents/proposition/modal/necessary": "ضروری",
    "semantic-contents/proposition/modal/possible": "ممکن",
    "semantic-contents/proposition/modal/impossible": "ممتنع",
    "semantic-contents/information": "معلومات (DIKW T2)",
    "semantic-contents/information/syntactic": "نحوی معلومات",
    "semantic-contents/information/semantic": "دلالی معلومات",
    "semantic-contents/information/pragmatic": "تداولی معلومات",
    "semantic-contents/fact": "حقیقت / واقعہ (wāqiʿah)",
    "semantic-contents/fact/empirical": "تجربی حقیقت",
    "semantic-contents/fact/mathematical": "ریاضیاتی حقیقت",
    "semantic-contents/fact/logical": "منطقی حقیقت",
    "semantic-contents/fact/historical": "تاریخی حقیقت",
    "semantic-contents/fact/moral": "اخلاقی حقیقت",
    "semantic-contents/meaning": "معنی (maʿnā)",
    "semantic-contents/meaning/sense-vs-reference": "معنی بمقابلہ مرجع (Frege)",
    "semantic-contents/meaning/connotation-vs-denotation": "تضمین بمقابلہ دلالت",
    "semantic-contents/meaning/literal-vs-figurative": "حقیقی بمقابلہ مجازی",
    "semantic-contents/definition": "تعریف (ḥadd)",
    "semantic-contents/definition/real": "حقیقی تعریف",
    "semantic-contents/definition/nominal": "اسمی تعریف",
    "semantic-contents/definition/genus-differentia": "جنس و فصل",
    "semantic-contents/definition/ostensive": "اشاری تعریف",
    "epistemic-states": "علمی حالات",
    "epistemic-states/compound-ignorance": "جہل مرکب",
    "epistemic-states/simple-ignorance": "جہل بسیط",
    "epistemic-states/illusion": "وہم (wahm)",
    "epistemic-states/illusion/perceptual": "ادراکی وہم",
    "epistemic-states/illusion/cognitive": "شناختی وہم",
    "epistemic-states/doubt": "شک (shakk)",
    "epistemic-states/doubt/methodological": "منہاجی شک",
    "epistemic-states/doubt/habitual": "عادتی شک",
    "epistemic-states/doubt/equipoised": "متساوی الطرفین شک",
    "epistemic-states/opinion": "ظن (ẓann)",
    "epistemic-states/opinion/probable": "غالب ظن",
    "epistemic-states/opinion/well-grounded": "مستدل ظن",
    "epistemic-states/opinion/dispositional": "استعدادی ظن",
    "epistemic-states/belief": "اعتقاد (iʿtiqād / taṣdīq)",
    "epistemic-states/belief/occurrent": "حالی اعتقاد",
    "epistemic-states/belief/dispositional": "استعدادی اعتقاد",
    "epistemic-states/belief/faith": "ایمان (īmān)",
    "epistemic-states/knowledge": "علم / معرفت (ʿilm / maʿrifah)",
    "epistemic-states/knowledge/by-mode": "نمط نمائش کے لحاظ سے",
    "epistemic-states/knowledge/by-mode/acquired": "حصولی (al-ʿilm al-ḥuṣūlī)",
    "epistemic-states/knowledge/by-mode/presential": "حضوری (al-ʿilm al-ḥuḍūrī)",
    "epistemic-states/knowledge/by-content": "مواد کی نوعیت کے لحاظ سے",
    "epistemic-states/knowledge/by-content/propositional": "قضوی (جاننا کہ)",
    "epistemic-states/knowledge/by-content/propositional/a-priori-analytic": "قبلی — تحلیلی",
    "epistemic-states/knowledge/by-content/propositional/a-priori-synthetic": "قبلی — ترکیبی",
    "epistemic-states/knowledge/by-content/propositional/a-posteriori-empirical": "بعدی — تجربی",
    "epistemic-states/knowledge/by-content/propositional/a-posteriori-testimonial": "بعدی — خبری",
    "epistemic-states/knowledge/by-content/procedural": "اجرائی (جاننا کیسے)",
    "epistemic-states/knowledge/by-content/procedural/motor": "حرکی مہارت",
    "epistemic-states/knowledge/by-content/procedural/cognitive": "شناختی مہارت",
    "epistemic-states/knowledge/by-content/procedural/social": "سماجی مہارت",
    "epistemic-states/knowledge/by-content/acquaintance": "آشنائی (جاننا از)",
    "epistemic-states/knowledge/by-content/acquaintance/direct-experience": "براہ راست تجربے سے",
    "epistemic-states/knowledge/by-content/acquaintance/memory": "حافظے سے",
    "epistemic-states/knowledge/by-content/tacit": "ضمنی (Polanyi)",
    "epistemic-states/knowledge/by-source": "مصدر کے لحاظ سے",
    "epistemic-states/knowledge/by-source/sensory": "حسی علم",
    "epistemic-states/knowledge/by-source/rational": "عقلی علم",
    "epistemic-states/knowledge/by-source/testimonial": "خبری علم",
    "epistemic-states/knowledge/by-source/revelatory": "وحیی علم",
    "epistemic-states/certainty": "یقین (yaqīn)",
    "epistemic-states/certainty/logical": "منطقی یقین",
    "epistemic-states/certainty/mathematical": "ریاضیاتی یقین",
    "epistemic-states/certainty/metaphysical": "مابعد الطبیعیاتی یقین",
    "epistemic-states/certainty/moral": "اخلاقی یقین",
    "epistemic-states/certainty/religious": "دینی یقین",
    "epistemic-states/certainty/religious/ilm-al-yaqin": "علم الیقین — یقین کا علم",
    "epistemic-states/certainty/religious/ayn-al-yaqin": "عین الیقین — یقین کی آنکھ",
    "epistemic-states/certainty/religious/haqq-al-yaqin": "حق الیقین — یقین کی حقیقت",
    "higher-order-constructs": "اعلیٰ مرتبہ تشکیلات",
    "higher-order-constructs/hypothesis": "فرضیہ (faraḍiyyah)",
    "higher-order-constructs/hypothesis/working": "عملی فرضیہ",
    "higher-order-constructs/hypothesis/statistical": "شماریاتی فرضیہ",
    "higher-order-constructs/hypothesis/statistical/null": "صفر فرضیہ",
    "higher-order-constructs/hypothesis/statistical/alternative": "متبادل فرضیہ",
    "higher-order-constructs/hypothesis/causal": "سببی فرضیہ",
    "higher-order-constructs/theory": "نظریہ (naẓariyyah)",
    "higher-order-constructs/theory/empirical": "تجربی نظریہ",
    "higher-order-constructs/theory/empirical/descriptive": "وصفی",
    "higher-order-constructs/theory/empirical/explanatory": "تفسیری",
    "higher-order-constructs/theory/empirical/predictive": "پیش گو",
    "higher-order-constructs/theory/formal": "صوری نظریہ",
    "higher-order-constructs/theory/normative": "معیاری نظریہ",
    "higher-order-constructs/model": "نمونہ (namūdhaj)",
    "higher-order-constructs/model/physical": "طبیعی نمونہ",
    "higher-order-constructs/model/mathematical": "ریاضیاتی نمونہ",
    "higher-order-constructs/model/computational": "حسابی نمونہ",
    "higher-order-constructs/model/conceptual": "تصوری نمونہ",
    "higher-order-constructs/law": "قانون (qānūn)",
    "higher-order-constructs/law/natural": "طبیعی قانون",
    "higher-order-constructs/law/natural/universal": "کلی قانون",
    "higher-order-constructs/law/natural/statistical": "شماریاتی قانون",
    "higher-order-constructs/law/logical": "منطقی قانون",
    "higher-order-constructs/law/logical/identity": "ہوہویت",
    "higher-order-constructs/law/logical/non-contradiction": "عدم تناقض",
    "higher-order-constructs/law/logical/excluded-middle": "ثالث مرفوع",
    "higher-order-constructs/law/divine": "الہی قانون (sharīʿah)",
    "higher-order-constructs/law/positive": "وضعی قانون",
    "higher-order-constructs/doctrine": "مذہب / دکترین (madhhab)",
    "higher-order-constructs/doctrine/religious": "دینی دکترین",
    "higher-order-constructs/doctrine/philosophical": "فلسفی دکترین",
    "higher-order-constructs/doctrine/scientific": "سائنسی دکترین",
    "higher-order-constructs/insight": "بصیرت (baṣīrah)",
    "higher-order-constructs/insight/aesthetic": "جمالیاتی بصیرت",
    "higher-order-constructs/insight/mystical": "عرفانی بصیرت",
    "higher-order-constructs/insight/scientific": "سائنسی بصیرت",
    "higher-order-constructs/wisdom": "حکمت (ḥikmah)",
    "higher-order-constructs/wisdom/theoretical": "نظری حکمت (sophia)",
    "higher-order-constructs/wisdom/practical": "عملی حکمت (phronēsis)",
    "higher-order-constructs/wisdom/productive-craft": "پیداواری ہنر (technē)",
    "higher-order-constructs/wisdom/spiritual": "روحانی حکمت",
    "higher-order-constructs/worldview": "جہاں بینی (ruʾyah kawniyyah)",
    "higher-order-constructs/worldview/religious": "دینی جہاں بینی",
    "higher-order-constructs/worldview/secular": "لادینی جہاں بینی",
    "higher-order-constructs/worldview/syncretic": "تلفیقی جہاں بینی",
    "perception": "ادراک / احساس",
    "perception/external": "بیرونی ادراک",
    "perception/internal": "اندرونی ادراک",
    "perception/self": "خود ادراک",
    "perception/extraordinary": "غیر معمولی ادراک",
    "inference": "استنتاج / عقل",
    "inference/deductive": "استنباطی استنتاج",
    "inference/inductive": "استقرائی استنتاج",
    "inference/abductive": "اختزالی استنتاج",
    "inference/necessary": "ضروری عقل",
    "inference/speculative": "نظری عقل",
    "testimony": "شہادت / خبر",
    "testimony/direct-witness": "براہ راست گواہی",
    "testimony/reported": "منقول خبر",
    "testimony/authoritative": "خبر ثقہ",
    "testimony/scriptural": "نقل شرعی",
    "mass-transmission": "تواتر (al-tawatur)",
    "mass-transmission/verbal": "لفظی تواتر",
    "mass-transmission/meaning": "معنوی تواتر",
    "mass-transmission/practical": "عملی تواتر",
    "comparison": "قیاس (qiyas / anumana)",
    "comparison/ratio-legis": "قیاس علت",
    "comparison/indication": "قیاس دلالت",
    "comparison/resemblance": "قیاس شبہ",
    "comparison/a-fortiori": "قیاس اولیٰ",
    "postulation": "افتراضی استنباط / IBE",
    "postulation/from-perceived": "مشاہدہ شدہ واقعے سے",
    "postulation/from-heard": "سنی ہوئی خبر سے",
    "postulation/ibe": "بہترین تفسیر کی طرف استدلال",
    "non-apprehension": "عدم ادراک",
    "non-apprehension/prior": "سابق عدم",
    "non-apprehension/posterior": "لاحق عدم",
    "non-apprehension/mutual": "متقابل عدم",
    "non-apprehension/absolute": "مطلق عدم",
    "memory": "حافظہ",
    "memory/recollection": "تذکر",
    "memory/recognition": "تعرف",
    "memory/episodic": "واقعاتی حافظہ",
    "memory/semantic": "دلالی حافظہ",
    "innate-disposition": "فطرت / حدس",
    "innate-disposition/primordial": "ابتدائی فطرت (سنی)",
    "innate-disposition/first-principles": "اصول اولیہ کا حدس",
    "innate-disposition/moral": "فطری اخلاقی معرفت",
    "innate-disposition/axioms": "بدیہیات",
    "inspiration": "الہام / عرفانی کشف",
    "inspiration/ilham": "الہام (ilhām)",
    "inspiration/kashf": "کشف",
    "inspiration/dream-vision": "صادقہ خواب",
    "revelation": "وحی",
    "revelation/recited": "متلو وحی (قرآن)",
    "revelation/non-recited": "غیر متلو وحی (سنت)",
    "revelation/modes-of-receiving": "وحی کی وصولی کے طریقے",
    "unclassifiable": "غیر قابل درجہ بندی",
}

HE = {
    "epistemic-content": "תוכן אפיסטמי",
    "sensory-inputs": "קלטים חושיים",
    "sensory-inputs/signal": "אות",
    "sensory-inputs/signal/physical": "אות פיזיקלי",
    "sensory-inputs/signal/physical/electromagnetic": "אלקטרומגנטי",
    "sensory-inputs/signal/physical/acoustic": "אקוסטי",
    "sensory-inputs/signal/physical/mechanical": "מכני",
    "sensory-inputs/signal/physical/chemical": "כימי",
    "sensory-inputs/signal/biological": "אות ביולוגי",
    "sensory-inputs/signal/biological/neural": "עצבי",
    "sensory-inputs/signal/biological/hormonal": "הורמונלי",
    "sensory-inputs/signal/biological/bioelectric": "ביו-חשמלי",
    "sensory-inputs/stimulus": "גירוי",
    "sensory-inputs/stimulus/distal": "גירוי דיסטלי",
    "sensory-inputs/stimulus/proximal": "גירוי פרוקסימלי",
    "sensory-inputs/stimulus/conditioned": "גירוי מותנה",
    "sensory-inputs/stimulus/unconditioned": "גירוי בלתי מותנה",
    "sensory-inputs/sense-datum": "נתון חושי",
    "sensory-inputs/sense-datum/visual": "קואליה חזותית",
    "sensory-inputs/sense-datum/auditory": "קואליה שמיעתית",
    "sensory-inputs/sense-datum/tactile": "קואליה מישושית",
    "sensory-inputs/sense-datum/olfactory": "קואליה ריחנית",
    "sensory-inputs/sense-datum/gustatory": "קואליה טעמית",
    "sensory-inputs/sense-datum/proprioceptive": "קואליה פרופריוצפטיבית",
    "sensory-inputs/percept": "תפיסה חושית",
    "sensory-inputs/percept/indeterminate": "תפיסה בלתי מוגדרת (nirvikalpa)",
    "sensory-inputs/percept/indeterminate/pure-sensation": "תחושה טהורה",
    "sensory-inputs/percept/determinate": "תפיסה מוגדרת (savikalpa)",
    "sensory-inputs/percept/determinate/object-recognition": "זיהוי אובייקט",
    "sensory-inputs/percept/determinate/categorized": "תפיסה מקוטלגת",
    "sensory-inputs/percept/extraordinary": "תפיסה יוצאת דופן (alaukika)",
    "sensory-inputs/percept/extraordinary/generic": "גנרית (sāmānyalakṣaṇa)",
    "sensory-inputs/percept/extraordinary/acquired": "נרכשת (jñānalakṣaṇa)",
    "sensory-inputs/percept/extraordinary/yogic": "יוגית (yogaja)",
    "symbolic-entities": "ישויות סמליות",
    "symbolic-entities/sign": "סימן (סיווג פירס)",
    "symbolic-entities/sign/icon": "אייקון — לפי דמיון",
    "symbolic-entities/sign/icon/image": "תמונה",
    "symbolic-entities/sign/icon/diagram": "דיאגרמה",
    "symbolic-entities/sign/icon/metaphor": "מטאפורה",
    "symbolic-entities/sign/index": "אינדקס — לפי קשר סיבתי",
    "symbolic-entities/sign/index/symptom": "סימפטום",
    "symbolic-entities/sign/index/trace": "עקבה",
    "symbolic-entities/sign/index/pointer": "מצביע",
    "symbolic-entities/sign/symbol-conventional": "סמל — לפי מוסכמה",
    "symbolic-entities/sign/symbol-conventional/word": "מילה",
    "symbolic-entities/sign/symbol-conventional/numeral": "ספרה",
    "symbolic-entities/sign/symbol-conventional/logical-operator": "אופרטור לוגי",
    "symbolic-entities/symbol": "סמל",
    "symbolic-entities/symbol/linguistic": "סמל לשוני",
    "symbolic-entities/symbol/linguistic/phoneme": "פונמה",
    "symbolic-entities/symbol/linguistic/morpheme": "מורפמה",
    "symbolic-entities/symbol/linguistic/lexeme": "לקסמה",
    "symbolic-entities/symbol/mathematical": "סמל מתמטי",
    "symbolic-entities/symbol/logical": "סמל לוגי",
    "symbolic-entities/symbol/iconographic": "סמל איקונוגרפי",
    "symbolic-entities/data": "נתונים",
    "symbolic-entities/data/structured": "נתונים מובנים",
    "symbolic-entities/data/structured/tabular": "טבלאיים",
    "symbolic-entities/data/structured/relational": "רלציוניים",
    "symbolic-entities/data/semi-structured": "נתונים חצי-מובנים",
    "symbolic-entities/data/semi-structured/serialized": "JSON / XML / YAML",
    "symbolic-entities/data/unstructured": "נתונים לא מובנים",
    "symbolic-entities/data/unstructured/text": "טקסט",
    "symbolic-entities/data/unstructured/image": "תמונה",
    "symbolic-entities/data/unstructured/audio": "אודיו",
    "symbolic-entities/data/unstructured/video": "וידאו",
    "symbolic-entities/data/quantitative": "נתונים כמותיים",
    "symbolic-entities/data/qualitative": "נתונים איכותיים",
    "symbolic-entities/code": "קוד",
    "symbolic-entities/code/natural-language": "קוד שפה טבעית",
    "symbolic-entities/code/formal-language": "קוד שפה פורמלית",
    "symbolic-entities/code/computer": "קוד מחשב",
    "symbolic-entities/code/cryptographic": "קוד קריפטוגרפי",
    "symbolic-entities/inscription": "כתובת / רישום",
    "symbolic-entities/inscription/oral": "בעל-פה",
    "symbolic-entities/inscription/manuscript": "כתב-יד",
    "symbolic-entities/inscription/print": "דפוס",
    "symbolic-entities/inscription/digital": "דיגיטלי",
    "semantic-contents": "תכנים סמנטיים",
    "semantic-contents/concept": "מושג (taṣawwur)",
    "semantic-contents/concept/simple": "מושג פשוט",
    "semantic-contents/concept/compound": "מושג מורכב",
    "semantic-contents/concept/empirical": "מושג אמפירי",
    "semantic-contents/concept/empirical/observational": "תצפיתי",
    "semantic-contents/concept/empirical/experimental": "ניסויי",
    "semantic-contents/concept/a-priori": "מושג אפריורי",
    "semantic-contents/concept/a-priori/logical": "לוגי",
    "semantic-contents/concept/a-priori/mathematical": "מתמטי",
    "semantic-contents/concept/concrete": "מושג קונקרטי",
    "semantic-contents/concept/abstract": "מושג מופשט",
    "semantic-contents/idea": "רעיון",
    "semantic-contents/idea/innate": "רעיון מולד (קרטזיאני)",
    "semantic-contents/idea/adventitious": "רעיון נרכש",
    "semantic-contents/idea/constructed": "רעיון בנוי",
    "semantic-contents/idea/clear-distinct": "רעיון בהיר ומובחן",
    "semantic-contents/proposition": "פסוק / טענה (qaḍiyyah)",
    "semantic-contents/proposition/categorical": "טענה קטגורית",
    "semantic-contents/proposition/categorical/universal-affirmative": "כוללת חיובית",
    "semantic-contents/proposition/categorical/universal-negative": "כוללת שלילית",
    "semantic-contents/proposition/categorical/particular-affirmative": "פרטית חיובית",
    "semantic-contents/proposition/categorical/particular-negative": "פרטית שלילית",
    "semantic-contents/proposition/hypothetical": "טענה היפותטית",
    "semantic-contents/proposition/hypothetical/conjunctive": "מחוברת (muttaṣilah)",
    "semantic-contents/proposition/hypothetical/disjunctive": "מפורקת (munfaṣilah)",
    "semantic-contents/proposition/modal": "טענה מודלית",
    "semantic-contents/proposition/modal/necessary": "הכרחית",
    "semantic-contents/proposition/modal/possible": "אפשרית",
    "semantic-contents/proposition/modal/impossible": "בלתי אפשרית",
    "semantic-contents/information": "מידע (DIKW T2)",
    "semantic-contents/information/syntactic": "מידע תחבירי",
    "semantic-contents/information/semantic": "מידע סמנטי",
    "semantic-contents/information/pragmatic": "מידע פרגמטי",
    "semantic-contents/fact": "עובדה (wāqiʿah)",
    "semantic-contents/fact/empirical": "עובדה אמפירית",
    "semantic-contents/fact/mathematical": "עובדה מתמטית",
    "semantic-contents/fact/logical": "עובדה לוגית",
    "semantic-contents/fact/historical": "עובדה היסטורית",
    "semantic-contents/fact/moral": "עובדה מוסרית",
    "semantic-contents/meaning": "משמעות (maʿnā)",
    "semantic-contents/meaning/sense-vs-reference": "משמעות מול ייחוס (פרגה)",
    "semantic-contents/meaning/connotation-vs-denotation": "קונוטציה מול דנוטציה",
    "semantic-contents/meaning/literal-vs-figurative": "מילולי מול ציורי",
    "semantic-contents/definition": "הגדרה (ḥadd)",
    "semantic-contents/definition/real": "הגדרה ממשית",
    "semantic-contents/definition/nominal": "הגדרה נומינלית",
    "semantic-contents/definition/genus-differentia": "סוג והבדל",
    "semantic-contents/definition/ostensive": "הגדרה אוסטנסיבית",
    "epistemic-states": "מצבים אפיסטמיים",
    "epistemic-states/compound-ignorance": "בורות מורכבת",
    "epistemic-states/simple-ignorance": "בורות פשוטה",
    "epistemic-states/illusion": "אשליה (wahm)",
    "epistemic-states/illusion/perceptual": "אשליה תפיסתית",
    "epistemic-states/illusion/cognitive": "אשליה קוגניטיבית",
    "epistemic-states/doubt": "ספק (shakk)",
    "epistemic-states/doubt/methodological": "ספק מתודולוגי",
    "epistemic-states/doubt/habitual": "ספק הרגלי",
    "epistemic-states/doubt/equipoised": "ספק מאוזן",
    "epistemic-states/opinion": "דעה (ẓann)",
    "epistemic-states/opinion/probable": "דעה סבירה",
    "epistemic-states/opinion/well-grounded": "דעה מבוססת היטב",
    "epistemic-states/opinion/dispositional": "דעה דיספוזיציונית",
    "epistemic-states/belief": "אמונה (iʿtiqād / taṣdīq)",
    "epistemic-states/belief/occurrent": "אמונה מתרחשת",
    "epistemic-states/belief/dispositional": "אמונה דיספוזיציונית",
    "epistemic-states/belief/faith": "אמונה דתית (īmān)",
    "epistemic-states/knowledge": "ידע (ʿilm / maʿrifah)",
    "epistemic-states/knowledge/by-mode": "לפי אופן הייצוג",
    "epistemic-states/knowledge/by-mode/acquired": "נרכש (al-ʿilm al-ḥuṣūlī)",
    "epistemic-states/knowledge/by-mode/presential": "נוכח (al-ʿilm al-ḥuḍūrī)",
    "epistemic-states/knowledge/by-content": "לפי סוג התוכן",
    "epistemic-states/knowledge/by-content/propositional": "פרופוזיציונלי (ידיעה-ש)",
    "epistemic-states/knowledge/by-content/propositional/a-priori-analytic": "אפריורי — אנליטי",
    "epistemic-states/knowledge/by-content/propositional/a-priori-synthetic": "אפריורי — סינתטי",
    "epistemic-states/knowledge/by-content/propositional/a-posteriori-empirical": "אפוסטריורי — אמפירי",
    "epistemic-states/knowledge/by-content/propositional/a-posteriori-testimonial": "אפוסטריורי — עדותי",
    "epistemic-states/knowledge/by-content/procedural": "פרוצדורלי (ידיעה-איך)",
    "epistemic-states/knowledge/by-content/procedural/motor": "מיומנות מוטורית",
    "epistemic-states/knowledge/by-content/procedural/cognitive": "מיומנות קוגניטיבית",
    "epistemic-states/knowledge/by-content/procedural/social": "מיומנות חברתית",
    "epistemic-states/knowledge/by-content/acquaintance": "היכרות (ידיעה-של)",
    "epistemic-states/knowledge/by-content/acquaintance/direct-experience": "באמצעות חוויה ישירה",
    "epistemic-states/knowledge/by-content/acquaintance/memory": "באמצעות זיכרון",
    "epistemic-states/knowledge/by-content/tacit": "טקיט (פולני)",
    "epistemic-states/knowledge/by-source": "לפי מקור",
    "epistemic-states/knowledge/by-source/sensory": "ידע חושי",
    "epistemic-states/knowledge/by-source/rational": "ידע רציונלי",
    "epistemic-states/knowledge/by-source/testimonial": "ידע עדותי",
    "epistemic-states/knowledge/by-source/revelatory": "ידע התגלותי",
    "epistemic-states/certainty": "ודאות (yaqīn)",
    "epistemic-states/certainty/logical": "ודאות לוגית",
    "epistemic-states/certainty/mathematical": "ודאות מתמטית",
    "epistemic-states/certainty/metaphysical": "ודאות מטפיזית",
    "epistemic-states/certainty/moral": "ודאות מוסרית",
    "epistemic-states/certainty/religious": "ודאות דתית",
    "epistemic-states/certainty/religious/ilm-al-yaqin": "ʿIlm al-yaqīn — ידיעת הוודאות",
    "epistemic-states/certainty/religious/ayn-al-yaqin": "ʿAyn al-yaqīn — עין הוודאות",
    "epistemic-states/certainty/religious/haqq-al-yaqin": "Ḥaqq al-yaqīn — אמת הוודאות",
    "higher-order-constructs": "מבנים מסדר גבוה",
    "higher-order-constructs/hypothesis": "השערה (faraḍiyyah)",
    "higher-order-constructs/hypothesis/working": "השערת עבודה",
    "higher-order-constructs/hypothesis/statistical": "השערה סטטיסטית",
    "higher-order-constructs/hypothesis/statistical/null": "השערת אפס",
    "higher-order-constructs/hypothesis/statistical/alternative": "השערה חלופית",
    "higher-order-constructs/hypothesis/causal": "השערה סיבתית",
    "higher-order-constructs/theory": "תאוריה (naẓariyyah)",
    "higher-order-constructs/theory/empirical": "תאוריה אמפירית",
    "higher-order-constructs/theory/empirical/descriptive": "תיאורית",
    "higher-order-constructs/theory/empirical/explanatory": "הסברית",
    "higher-order-constructs/theory/empirical/predictive": "חיזויית",
    "higher-order-constructs/theory/formal": "תאוריה פורמלית",
    "higher-order-constructs/theory/normative": "תאוריה נורמטיבית",
    "higher-order-constructs/model": "מודל (namūdhaj)",
    "higher-order-constructs/model/physical": "מודל פיזיקלי",
    "higher-order-constructs/model/mathematical": "מודל מתמטי",
    "higher-order-constructs/model/computational": "מודל חישובי",
    "higher-order-constructs/model/conceptual": "מודל מושגי",
    "higher-order-constructs/law": "חוק (qānūn)",
    "higher-order-constructs/law/natural": "חוק טבע",
    "higher-order-constructs/law/natural/universal": "חוק אוניברסלי",
    "higher-order-constructs/law/natural/statistical": "חוק סטטיסטי",
    "higher-order-constructs/law/logical": "חוק לוגי",
    "higher-order-constructs/law/logical/identity": "זהות",
    "higher-order-constructs/law/logical/non-contradiction": "אי-סתירה",
    "higher-order-constructs/law/logical/excluded-middle": "השלישי הנמנע",
    "higher-order-constructs/law/divine": "חוק אלוהי (sharīʿah)",
    "higher-order-constructs/law/positive": "חוק פוזיטיבי",
    "higher-order-constructs/doctrine": "דוקטרינה (madhhab)",
    "higher-order-constructs/doctrine/religious": "דוקטרינה דתית",
    "higher-order-constructs/doctrine/philosophical": "דוקטרינה פילוסופית",
    "higher-order-constructs/doctrine/scientific": "דוקטרינה מדעית",
    "higher-order-constructs/insight": "תובנה (baṣīrah)",
    "higher-order-constructs/insight/aesthetic": "תובנה אסתטית",
    "higher-order-constructs/insight/mystical": "תובנה מיסטית",
    "higher-order-constructs/insight/scientific": "תובנה מדעית",
    "higher-order-constructs/wisdom": "חוכמה (ḥikmah)",
    "higher-order-constructs/wisdom/theoretical": "חוכמה תאורטית (sophia)",
    "higher-order-constructs/wisdom/practical": "חוכמה מעשית (phronēsis)",
    "higher-order-constructs/wisdom/productive-craft": "מלאכה יצרנית (technē)",
    "higher-order-constructs/wisdom/spiritual": "חוכמה רוחנית",
    "higher-order-constructs/worldview": "השקפת עולם (ruʾyah kawniyyah)",
    "higher-order-constructs/worldview/religious": "השקפת עולם דתית",
    "higher-order-constructs/worldview/secular": "השקפת עולם חילונית",
    "higher-order-constructs/worldview/syncretic": "השקפת עולם סינקרטית",
    "perception": "תפיסה / תחושה",
    "perception/external": "תפיסה חיצונית",
    "perception/internal": "תפיסה פנימית",
    "perception/self": "תפיסה עצמית",
    "perception/extraordinary": "תפיסה יוצאת דופן",
    "inference": "היסק / שכל",
    "inference/deductive": "היסק דדוקטיבי",
    "inference/inductive": "היסק אינדוקטיבי",
    "inference/abductive": "היסק אבדוקטיבי",
    "inference/necessary": "שכל הכרחי",
    "inference/speculative": "שכל ספקולטיבי",
    "testimony": "עדות",
    "testimony/direct-witness": "עדות עד ישיר",
    "testimony/reported": "עדות מדווחת",
    "testimony/authoritative": "עדות סמכותית",
    "testimony/scriptural": "עדות מן הכתובים",
    "mass-transmission": "תוואתור (al-tawatur)",
    "mass-transmission/verbal": "תוואתור מילולי",
    "mass-transmission/meaning": "תוואתור משמעותי",
    "mass-transmission/practical": "תוואתור מעשי",
    "comparison": "השוואה / אנלוגיה (qiyas / anumana)",
    "comparison/ratio-legis": "אנלוגיה לפי טעם החוק",
    "comparison/indication": "אנלוגיה לפי הצבעה",
    "comparison/resemblance": "אנלוגיה לפי דמיון",
    "comparison/a-fortiori": "אנלוגיה לפי קל וחומר",
    "postulation": "הנחה / IBE",
    "postulation/from-perceived": "מעובדה נתפסת",
    "postulation/from-heard": "מעובדה נשמעת",
    "postulation/ibe": "היסק להסבר הטוב ביותר",
    "non-apprehension": "אי-תפיסה",
    "non-apprehension/prior": "היעדר קודם",
    "non-apprehension/posterior": "היעדר מאוחר",
    "non-apprehension/mutual": "היעדר הדדי",
    "non-apprehension/absolute": "היעדר מוחלט",
    "memory": "זיכרון",
    "memory/recollection": "היזכרות",
    "memory/recognition": "הכרה",
    "memory/episodic": "זיכרון אפיזודי",
    "memory/semantic": "זיכרון סמנטי",
    "innate-disposition": "נטייה מולדת / אינטואיציה",
    "innate-disposition/primordial": "נטייה ראשיתית (סוני)",
    "innate-disposition/first-principles": "אינטואיציה של עקרונות ראשונים",
    "innate-disposition/moral": "ידע מוסרי מולד",
    "innate-disposition/axioms": "אקסיומות ברורות מאליהן",
    "inspiration": "השראה / תפיסה מיסטית",
    "inspiration/ilham": "Ilhām (השראה)",
    "inspiration/kashf": "Kashf (חשיפה)",
    "inspiration/dream-vision": "חזון חלום אמיתי",
    "revelation": "התגלות / וחי",
    "revelation/recited": "התגלות מקריאה (קוראן)",
    "revelation/non-recited": "התגלות לא-מקריאה (סונה)",
    "revelation/modes-of-receiving": "אופני קבלת ההתגלות",
    "unclassifiable": "בלתי ניתן לסיווג",
}

HI = {
    "epistemic-content": "ज्ञानात्मक सामग्री",
    "sensory-inputs": "इंद्रिय निविष्टियाँ",
    "sensory-inputs/signal": "संकेत",
    "sensory-inputs/signal/physical": "भौतिक संकेत",
    "sensory-inputs/signal/physical/electromagnetic": "विद्युत-चुंबकीय",
    "sensory-inputs/signal/physical/acoustic": "ध्वनिक",
    "sensory-inputs/signal/physical/mechanical": "यांत्रिक",
    "sensory-inputs/signal/physical/chemical": "रासायनिक",
    "sensory-inputs/signal/biological": "जैविक संकेत",
    "sensory-inputs/signal/biological/neural": "तंत्रिकीय",
    "sensory-inputs/signal/biological/hormonal": "हार्मोनल",
    "sensory-inputs/signal/biological/bioelectric": "जैव-विद्युत",
    "sensory-inputs/stimulus": "उद्दीपन",
    "sensory-inputs/stimulus/distal": "दूरस्थ उद्दीपन",
    "sensory-inputs/stimulus/proximal": "निकटस्थ उद्दीपन",
    "sensory-inputs/stimulus/conditioned": "अनुबद्ध उद्दीपन",
    "sensory-inputs/stimulus/unconditioned": "अनुबद्ध न उद्दीपन",
    "sensory-inputs/sense-datum": "इंद्रिय-दत्त",
    "sensory-inputs/sense-datum/visual": "दृश्य क्वालिया",
    "sensory-inputs/sense-datum/auditory": "श्रवण क्वालिया",
    "sensory-inputs/sense-datum/tactile": "स्पर्श क्वालिया",
    "sensory-inputs/sense-datum/olfactory": "घ्राण क्वालिया",
    "sensory-inputs/sense-datum/gustatory": "स्वाद क्वालिया",
    "sensory-inputs/sense-datum/proprioceptive": "स्व-संवेदी क्वालिया",
    "sensory-inputs/percept": "प्रत्यक्ष",
    "sensory-inputs/percept/indeterminate": "निर्विकल्प प्रत्यक्ष",
    "sensory-inputs/percept/indeterminate/pure-sensation": "शुद्ध संवेदना",
    "sensory-inputs/percept/determinate": "सविकल्प प्रत्यक्ष",
    "sensory-inputs/percept/determinate/object-recognition": "वस्तु पहचान",
    "sensory-inputs/percept/determinate/categorized": "वर्गीकृत प्रत्यक्ष",
    "sensory-inputs/percept/extraordinary": "अलौकिक प्रत्यक्ष",
    "sensory-inputs/percept/extraordinary/generic": "सामान्यलक्षण",
    "sensory-inputs/percept/extraordinary/acquired": "ज्ञानलक्षण",
    "sensory-inputs/percept/extraordinary/yogic": "योगज",
    "symbolic-entities": "प्रतीकात्मक सत्ताएँ",
    "symbolic-entities/sign": "चिह्न (पीयर्स वर्गीकरण)",
    "symbolic-entities/sign/icon": "आइकन — सादृश्य द्वारा",
    "symbolic-entities/sign/icon/image": "छवि",
    "symbolic-entities/sign/icon/diagram": "आरेख",
    "symbolic-entities/sign/icon/metaphor": "रूपक",
    "symbolic-entities/sign/index": "सूचक — कारणात्मक संबंध से",
    "symbolic-entities/sign/index/symptom": "लक्षण",
    "symbolic-entities/sign/index/trace": "अवशेष",
    "symbolic-entities/sign/index/pointer": "संकेतक",
    "symbolic-entities/sign/symbol-conventional": "प्रतीक — परंपरा से",
    "symbolic-entities/sign/symbol-conventional/word": "शब्द",
    "symbolic-entities/sign/symbol-conventional/numeral": "अंक",
    "symbolic-entities/sign/symbol-conventional/logical-operator": "तार्किक संकारक",
    "symbolic-entities/symbol": "प्रतीक",
    "symbolic-entities/symbol/linguistic": "भाषाई प्रतीक",
    "symbolic-entities/symbol/linguistic/phoneme": "स्वनिम",
    "symbolic-entities/symbol/linguistic/morpheme": "रूपिम",
    "symbolic-entities/symbol/linguistic/lexeme": "शब्दिम",
    "symbolic-entities/symbol/mathematical": "गणितीय प्रतीक",
    "symbolic-entities/symbol/logical": "तार्किक प्रतीक",
    "symbolic-entities/symbol/iconographic": "प्रतिमामूलक प्रतीक",
    "symbolic-entities/data": "डेटा",
    "symbolic-entities/data/structured": "संरचित डेटा",
    "symbolic-entities/data/structured/tabular": "सारणीबद्ध",
    "symbolic-entities/data/structured/relational": "संबंधात्मक",
    "symbolic-entities/data/semi-structured": "अर्ध-संरचित डेटा",
    "symbolic-entities/data/semi-structured/serialized": "JSON / XML / YAML",
    "symbolic-entities/data/unstructured": "असंरचित डेटा",
    "symbolic-entities/data/unstructured/text": "पाठ",
    "symbolic-entities/data/unstructured/image": "छवि",
    "symbolic-entities/data/unstructured/audio": "ऑडियो",
    "symbolic-entities/data/unstructured/video": "वीडियो",
    "symbolic-entities/data/quantitative": "मात्रात्मक डेटा",
    "symbolic-entities/data/qualitative": "गुणात्मक डेटा",
    "symbolic-entities/code": "कोड",
    "symbolic-entities/code/natural-language": "प्राकृतिक भाषा कोड",
    "symbolic-entities/code/formal-language": "औपचारिक भाषा कोड",
    "symbolic-entities/code/computer": "कंप्यूटर कोड",
    "symbolic-entities/code/cryptographic": "क्रिप्टोग्राफिक कोड",
    "symbolic-entities/inscription": "अभिलेख",
    "symbolic-entities/inscription/oral": "मौखिक",
    "symbolic-entities/inscription/manuscript": "हस्तलिखित",
    "symbolic-entities/inscription/print": "मुद्रित",
    "symbolic-entities/inscription/digital": "डिजिटल",
    "semantic-contents": "अर्थपरक सामग्री",
    "semantic-contents/concept": "संकल्पना (तसव्वुर)",
    "semantic-contents/concept/simple": "साधारण संकल्पना",
    "semantic-contents/concept/compound": "यौगिक संकल्पना",
    "semantic-contents/concept/empirical": "अनुभवजन्य संकल्पना",
    "semantic-contents/concept/empirical/observational": "प्रेक्षणात्मक",
    "semantic-contents/concept/empirical/experimental": "प्रायोगिक",
    "semantic-contents/concept/a-priori": "पूर्व-स्वतःसिद्ध संकल्पना",
    "semantic-contents/concept/a-priori/logical": "तार्किक",
    "semantic-contents/concept/a-priori/mathematical": "गणितीय",
    "semantic-contents/concept/concrete": "मूर्त संकल्पना",
    "semantic-contents/concept/abstract": "अमूर्त संकल्पना",
    "semantic-contents/idea": "विचार",
    "semantic-contents/idea/innate": "जन्मजात विचार (कार्तीसीय)",
    "semantic-contents/idea/adventitious": "अर्जित विचार",
    "semantic-contents/idea/constructed": "रचित विचार",
    "semantic-contents/idea/clear-distinct": "स्पष्ट और विशिष्ट विचार",
    "semantic-contents/proposition": "वाक्य-कथन (कज़िय्या)",
    "semantic-contents/proposition/categorical": "श्रेणीगत कथन",
    "semantic-contents/proposition/categorical/universal-affirmative": "सार्वत्रिक सकारात्मक",
    "semantic-contents/proposition/categorical/universal-negative": "सार्वत्रिक नकारात्मक",
    "semantic-contents/proposition/categorical/particular-affirmative": "विशेष सकारात्मक",
    "semantic-contents/proposition/categorical/particular-negative": "विशेष नकारात्मक",
    "semantic-contents/proposition/hypothetical": "परिकल्पनीय कथन",
    "semantic-contents/proposition/hypothetical/conjunctive": "संयुक्त (मुत्तसिला)",
    "semantic-contents/proposition/hypothetical/disjunctive": "वियुक्त (मुनफ़सिला)",
    "semantic-contents/proposition/modal": "मोडल कथन",
    "semantic-contents/proposition/modal/necessary": "आवश्यक",
    "semantic-contents/proposition/modal/possible": "संभव",
    "semantic-contents/proposition/modal/impossible": "असंभव",
    "semantic-contents/information": "सूचना (DIKW T2)",
    "semantic-contents/information/syntactic": "वाक्य-रचनात्मक सूचना",
    "semantic-contents/information/semantic": "अर्थपरक सूचना",
    "semantic-contents/information/pragmatic": "व्यवहारिक सूचना",
    "semantic-contents/fact": "तथ्य (वाक़िआ)",
    "semantic-contents/fact/empirical": "अनुभवजन्य तथ्य",
    "semantic-contents/fact/mathematical": "गणितीय तथ्य",
    "semantic-contents/fact/logical": "तार्किक तथ्य",
    "semantic-contents/fact/historical": "ऐतिहासिक तथ्य",
    "semantic-contents/fact/moral": "नैतिक तथ्य",
    "semantic-contents/meaning": "अर्थ (माना)",
    "semantic-contents/meaning/sense-vs-reference": "अर्थ बनाम संदर्भ (फ़्रेगे)",
    "semantic-contents/meaning/connotation-vs-denotation": "गुणार्थ बनाम मूलार्थ",
    "semantic-contents/meaning/literal-vs-figurative": "शाब्दिक बनाम लाक्षणिक",
    "semantic-contents/definition": "परिभाषा (हद्द)",
    "semantic-contents/definition/real": "वास्तविक परिभाषा",
    "semantic-contents/definition/nominal": "नाममात्र परिभाषा",
    "semantic-contents/definition/genus-differentia": "जाति-भेद",
    "semantic-contents/definition/ostensive": "प्रदर्शनात्मक परिभाषा",
    "epistemic-states": "ज्ञानात्मक अवस्थाएँ",
    "epistemic-states/compound-ignorance": "मिश्रित अज्ञान",
    "epistemic-states/simple-ignorance": "साधारण अज्ञान",
    "epistemic-states/illusion": "भ्रम (वहम)",
    "epistemic-states/illusion/perceptual": "प्रत्यक्षात्मक भ्रम",
    "epistemic-states/illusion/cognitive": "संज्ञानात्मक भ्रम",
    "epistemic-states/doubt": "संदेह (शक्क)",
    "epistemic-states/doubt/methodological": "पद्धतिगत संदेह",
    "epistemic-states/doubt/habitual": "अभ्यासगत संदेह",
    "epistemic-states/doubt/equipoised": "समतुलित संदेह",
    "epistemic-states/opinion": "मत (ज़न्न)",
    "epistemic-states/opinion/probable": "प्रबल मत",
    "epistemic-states/opinion/well-grounded": "सुसमर्थित मत",
    "epistemic-states/opinion/dispositional": "स्वभावजन्य मत",
    "epistemic-states/belief": "विश्वास (इतिक़ाद / तसदीक़)",
    "epistemic-states/belief/occurrent": "सक्रिय विश्वास",
    "epistemic-states/belief/dispositional": "स्वभावजन्य विश्वास",
    "epistemic-states/belief/faith": "श्रद्धा / ईमान",
    "epistemic-states/knowledge": "ज्ञान (इल्म / मारिफ़ा)",
    "epistemic-states/knowledge/by-mode": "प्रतिनिधित्व की रीति के अनुसार",
    "epistemic-states/knowledge/by-mode/acquired": "अर्जित (al-ʿilm al-ḥuṣūlī)",
    "epistemic-states/knowledge/by-mode/presential": "उपस्थितिजन्य (al-ʿilm al-ḥuḍūrī)",
    "epistemic-states/knowledge/by-content": "सामग्री-प्रकार के अनुसार",
    "epistemic-states/knowledge/by-content/propositional": "वचनात्मक (जानना-कि)",
    "epistemic-states/knowledge/by-content/propositional/a-priori-analytic": "पूर्वसिद्ध — विश्लेषणात्मक",
    "epistemic-states/knowledge/by-content/propositional/a-priori-synthetic": "पूर्वसिद्ध — संश्लेषणात्मक",
    "epistemic-states/knowledge/by-content/propositional/a-posteriori-empirical": "अनुभवोत्तर — अनुभवजन्य",
    "epistemic-states/knowledge/by-content/propositional/a-posteriori-testimonial": "अनुभवोत्तर — साक्ष्यपरक",
    "epistemic-states/knowledge/by-content/procedural": "प्रक्रियात्मक (जानना-कैसे)",
    "epistemic-states/knowledge/by-content/procedural/motor": "गतिक कौशल",
    "epistemic-states/knowledge/by-content/procedural/cognitive": "संज्ञानात्मक कौशल",
    "epistemic-states/knowledge/by-content/procedural/social": "सामाजिक कौशल",
    "epistemic-states/knowledge/by-content/acquaintance": "परिचय (जानना-का)",
    "epistemic-states/knowledge/by-content/acquaintance/direct-experience": "प्रत्यक्ष अनुभव से",
    "epistemic-states/knowledge/by-content/acquaintance/memory": "स्मृति से",
    "epistemic-states/knowledge/by-content/tacit": "मौन ज्ञान (पोलानी)",
    "epistemic-states/knowledge/by-source": "स्रोत के अनुसार",
    "epistemic-states/knowledge/by-source/sensory": "इंद्रियजन्य ज्ञान",
    "epistemic-states/knowledge/by-source/rational": "तर्कजन्य ज्ञान",
    "epistemic-states/knowledge/by-source/testimonial": "साक्ष्यपरक ज्ञान",
    "epistemic-states/knowledge/by-source/revelatory": "प्रकटनात्मक ज्ञान",
    "epistemic-states/certainty": "निश्चय (यक़ीन)",
    "epistemic-states/certainty/logical": "तार्किक निश्चय",
    "epistemic-states/certainty/mathematical": "गणितीय निश्चय",
    "epistemic-states/certainty/metaphysical": "तत्त्वमीमांसीय निश्चय",
    "epistemic-states/certainty/moral": "नैतिक निश्चय",
    "epistemic-states/certainty/religious": "धार्मिक निश्चय",
    "epistemic-states/certainty/religious/ilm-al-yaqin": "इल्म अल-यक़ीन — निश्चय का ज्ञान",
    "epistemic-states/certainty/religious/ayn-al-yaqin": "ऐन अल-यक़ीन — निश्चय की दृष्टि",
    "epistemic-states/certainty/religious/haqq-al-yaqin": "हक़्क़ अल-यक़ीन — निश्चय का सत्य",
    "higher-order-constructs": "उच्चतर-क्रम संरचनाएँ",
    "higher-order-constructs/hypothesis": "परिकल्पना (फ़र्ज़िया)",
    "higher-order-constructs/hypothesis/working": "कार्यकारी परिकल्पना",
    "higher-order-constructs/hypothesis/statistical": "सांख्यिकीय परिकल्पना",
    "higher-order-constructs/hypothesis/statistical/null": "शून्य परिकल्पना",
    "higher-order-constructs/hypothesis/statistical/alternative": "वैकल्पिक परिकल्पना",
    "higher-order-constructs/hypothesis/causal": "कारणात्मक परिकल्पना",
    "higher-order-constructs/theory": "सिद्धांत (नज़रिया)",
    "higher-order-constructs/theory/empirical": "अनुभवजन्य सिद्धांत",
    "higher-order-constructs/theory/empirical/descriptive": "वर्णनात्मक",
    "higher-order-constructs/theory/empirical/explanatory": "व्याख्यात्मक",
    "higher-order-constructs/theory/empirical/predictive": "पूर्वानुमानात्मक",
    "higher-order-constructs/theory/formal": "औपचारिक सिद्धांत",
    "higher-order-constructs/theory/normative": "मानक सिद्धांत",
    "higher-order-constructs/model": "मॉडल (नमूज़ज)",
    "higher-order-constructs/model/physical": "भौतिक मॉडल",
    "higher-order-constructs/model/mathematical": "गणितीय मॉडल",
    "higher-order-constructs/model/computational": "कंप्यूटेशनल मॉडल",
    "higher-order-constructs/model/conceptual": "संकल्पनात्मक मॉडल",
    "higher-order-constructs/law": "नियम (क़ानून)",
    "higher-order-constructs/law/natural": "प्राकृतिक नियम",
    "higher-order-constructs/law/natural/universal": "सार्वत्रिक नियम",
    "higher-order-constructs/law/natural/statistical": "सांख्यिकीय नियम",
    "higher-order-constructs/law/logical": "तार्किक नियम",
    "higher-order-constructs/law/logical/identity": "तदात्म्य",
    "higher-order-constructs/law/logical/non-contradiction": "अविरोध",
    "higher-order-constructs/law/logical/excluded-middle": "मध्य-निषेध",
    "higher-order-constructs/law/divine": "दिव्य विधि (शरीअत)",
    "higher-order-constructs/law/positive": "सकारात्मक विधि",
    "higher-order-constructs/doctrine": "सिद्धांत-वाद (मज़हब)",
    "higher-order-constructs/doctrine/religious": "धार्मिक सिद्धांत",
    "higher-order-constructs/doctrine/philosophical": "दार्शनिक सिद्धांत",
    "higher-order-constructs/doctrine/scientific": "वैज्ञानिक सिद्धांत",
    "higher-order-constructs/insight": "अंतर्दृष्टि (बसीरत)",
    "higher-order-constructs/insight/aesthetic": "सौंदर्यात्मक अंतर्दृष्टि",
    "higher-order-constructs/insight/mystical": "रहस्यात्मक अंतर्दृष्टि",
    "higher-order-constructs/insight/scientific": "वैज्ञानिक अंतर्दृष्टि",
    "higher-order-constructs/wisdom": "प्रज्ञा (हिकमत)",
    "higher-order-constructs/wisdom/theoretical": "सैद्धांतिक प्रज्ञा (sophia)",
    "higher-order-constructs/wisdom/practical": "व्यावहारिक प्रज्ञा (phronēsis)",
    "higher-order-constructs/wisdom/productive-craft": "उत्पादक शिल्प (technē)",
    "higher-order-constructs/wisdom/spiritual": "आध्यात्मिक प्रज्ञा",
    "higher-order-constructs/worldview": "विश्व-दृष्टि (रुऊया कौनिय्या)",
    "higher-order-constructs/worldview/religious": "धार्मिक विश्व-दृष्टि",
    "higher-order-constructs/worldview/secular": "धर्मनिरपेक्ष विश्व-दृष्टि",
    "higher-order-constructs/worldview/syncretic": "समन्वयवादी विश्व-दृष्टि",
    "perception": "प्रत्यक्ष / संवेदना",
    "perception/external": "बाह्य प्रत्यक्ष",
    "perception/internal": "आंतरिक प्रत्यक्ष",
    "perception/self": "आत्म-प्रत्यक्ष",
    "perception/extraordinary": "अलौकिक प्रत्यक्ष",
    "inference": "अनुमान / तर्क",
    "inference/deductive": "निगमनात्मक अनुमान",
    "inference/inductive": "आगमनात्मक अनुमान",
    "inference/abductive": "अपहरणात्मक अनुमान",
    "inference/necessary": "आवश्यक तर्क",
    "inference/speculative": "अनुमानात्मक तर्क",
    "testimony": "साक्ष्य / शब्द",
    "testimony/direct-witness": "प्रत्यक्षदर्शी साक्ष्य",
    "testimony/reported": "प्रतिवेदित साक्ष्य",
    "testimony/authoritative": "प्रामाणिक साक्ष्य",
    "testimony/scriptural": "शास्त्रीय साक्ष्य",
    "mass-transmission": "अल-तवातुर (al-tawatur)",
    "mass-transmission/verbal": "शाब्दिक तवातुर",
    "mass-transmission/meaning": "अर्थपरक तवातुर",
    "mass-transmission/practical": "व्यावहारिक तवातुर",
    "comparison": "अनुमान / उपमान (qiyas / anumana)",
    "comparison/ratio-legis": "विधिहेतुगत उपमा",
    "comparison/indication": "संकेत-आधारित उपमा",
    "comparison/resemblance": "सादृश्य-आधारित उपमा",
    "comparison/a-fortiori": "और-अधिक-कारण उपमा",
    "postulation": "अर्थापत्ति / IBE",
    "postulation/from-perceived": "प्रत्यक्ष तथ्य से",
    "postulation/from-heard": "श्रुत तथ्य से",
    "postulation/ibe": "श्रेष्ठ व्याख्या तक अनुमान",
    "non-apprehension": "अनुपलब्धि",
    "non-apprehension/prior": "प्रागभाव",
    "non-apprehension/posterior": "प्रध्वंसाभाव",
    "non-apprehension/mutual": "अन्योन्याभाव",
    "non-apprehension/absolute": "अत्यन्ताभाव",
    "memory": "स्मृति",
    "memory/recollection": "प्रत्यभिज्ञा",
    "memory/recognition": "अभिज्ञान",
    "memory/episodic": "घटना-स्मृति",
    "memory/semantic": "अर्थपरक स्मृति",
    "innate-disposition": "स्वाभाविक प्रवृत्ति / सहज ज्ञान",
    "innate-disposition/primordial": "मूल-प्रवृत्ति (फ़ितरा, सुन्नी)",
    "innate-disposition/first-principles": "प्रथम सिद्धांतों का सहज ज्ञान",
    "innate-disposition/moral": "जन्मजात नैतिक ज्ञान",
    "innate-disposition/axioms": "स्वतःसिद्ध स्वसिद्ध",
    "inspiration": "प्रेरणा / रहस्यानुभूति",
    "inspiration/ilham": "इल्हाम (प्रेरणा)",
    "inspiration/kashf": "कश्फ़ (अनावरण)",
    "inspiration/dream-vision": "सत्य स्वप्न-दर्शन",
    "revelation": "प्रकटन / वहय",
    "revelation/recited": "पठित प्रकटन (क़ुरआन)",
    "revelation/non-recited": "अपठित प्रकटन (सुन्ना)",
    "revelation/modes-of-receiving": "प्रकटन प्राप्ति के प्रकार",
    "unclassifiable": "अवर्गीकृत",
}


# ---------------------------------------------------------------------------
# Apply
# ---------------------------------------------------------------------------

LOCALES = {
    "fa": FA,
    "ur": UR,
    "he": HE,
    "hi": HI,
}


def apply_locale(lang: str, taxonomy_block: dict) -> tuple[int, int]:
    """Replace cece.taxonomy in the locale file. Returns (added, replaced)."""
    json_path = LOCALES_DIR / f"{lang}.json"
    with json_path.open("r", encoding="utf-8") as f:
        data = json.load(f)
    cece = data.setdefault("cece", {})
    existing = cece.get("taxonomy") or {}
    cece["taxonomy"] = taxonomy_block
    with json_path.open("w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
        f.write("\n")
    added = sum(1 for k in taxonomy_block if k not in existing)
    replaced = sum(1 for k in taxonomy_block if k in existing)
    return added, replaced


def main() -> None:
    # Load en.json to verify key parity.
    en_path = LOCALES_DIR / "en.json"
    with en_path.open("r", encoding="utf-8") as f:
        en_data = json.load(f)
    en_keys = set(en_data["cece"]["taxonomy"].keys())
    print(f"en.json cece.taxonomy: {len(en_keys)} keys (source of truth)")
    print()

    for lang, block in LOCALES.items():
        block_keys = set(block.keys())
        missing = en_keys - block_keys
        extra = block_keys - en_keys
        if missing:
            raise SystemExit(f"FAIL [{lang}]: missing {len(missing)} keys: {sorted(missing)[:5]}...")
        if extra:
            raise SystemExit(f"FAIL [{lang}]: {len(extra)} extra keys not in en: {sorted(extra)[:5]}...")
        added, replaced = apply_locale(lang, block)
        # Re-load + verify post-write.
        with (LOCALES_DIR / f"{lang}.json").open("r", encoding="utf-8") as f:
            after = json.load(f)
        post_count = len(after["cece"]["taxonomy"])
        print(
            f"[{lang}] wrote {len(block)} keys "
            f"(added={added}, replaced={replaced}); post-write count={post_count}"
        )
        if post_count != 277:
            raise SystemExit(f"FAIL [{lang}]: expected 277 keys post-write, got {post_count}")
    print()
    print("All 4 locales backfilled successfully (277 keys each).")


if __name__ == "__main__":
    main()
