#!/usr/bin/env python3
"""
Constellation Lexicon — concepts.json → lexicon_v1.tsv emitter.

Reads the hand-curated concept list from concepts.json and writes a
deterministic TSV in the format consumed by
src-tauri/src/lexicon/parse.rs::parse().

Determinism rules (reproducible byte-identical output given same input):
  - Rows sorted by concept id, stably.
  - Language columns sorted alphabetically by lang code within each row.
  - Lemmas within a single (concept × language) cell: first-seen order
    preserved (preferred lemma first), duplicates dropped after the
    first occurrence.
  - Header comment block is a fixed literal.
  - No trailing whitespace; LF line endings regardless of host OS.

Exits non-zero with a descriptive stderr message if concepts.json is
malformed. validate.py does the deeper content checks; build.py is
only expected to catch structural issues (missing required fields,
unknown PoS, lemma value not a list).

Usage:
    python build.py                    # writes the TSV
    python build.py --stdout           # prints the TSV to stdout only
    python build.py --dry-run          # counts rows + lemmas, writes nothing
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any, Dict, List

# ─── Constants ────────────────────────────────────────────────────────────────

REPO_ROOT = Path(__file__).resolve().parents[2]
CONCEPTS_JSON = Path(__file__).parent / "concepts.json"
OUTPUT_TSV = REPO_ROOT / "src-tauri" / "src" / "lexicon" / "data" / "lexicon_v1.tsv"

# ISO-639-1 codes that round-trip with arabic::Lang::code.
SUPPORTED_LANGS = ["ar", "de", "en", "es", "fa", "fr", "he", "hi",
                   "ja", "ko", "pt", "ru", "tr", "ur", "zh"]

# Valid arabic::PartOfSpeech variants. Empty string means Unknown
# (handled at parse time).
VALID_POS = {"Noun", "Verb", "Adjective", "Adverb",
             "ProperNoun", "Particle", "Foreign", "Unknown"}

# Fixed header block emitted on top of every regenerated TSV. Mirrors
# the seed_v1.tsv comment block so anyone opening either file in an
# editor finds the same conventions documented in place.
HEADER = """\
# Constellation Lexicon — production corpus v1 (M11-data).
#
# This file is GENERATED by lab/m11-data/build.py. Do not hand-edit —
# edit lab/m11-data/concepts.json and rerun build.py instead.
#
# Format per row (TAB-separated):
#
#   concept_id<TAB>pos<TAB>lang:lemma,lemma,...<TAB>lang:lemma,lemma,...<TAB>...
#
# See lab/m11-data/README.md for the full schema and the regeneration
# workflow. Every concept in this corpus is Constellation-original
# content — no third-party wordnet data is consumed. The file is
# redistributable under whatever license Constellation chooses, now
# and forever.
"""

# ─── Helpers ──────────────────────────────────────────────────────────────────

def die(msg: str, code: int = 1) -> None:
    print(f"build.py: error: {msg}", file=sys.stderr)
    sys.exit(code)


def load_concepts() -> List[Dict[str, Any]]:
    """Parse concepts.json, do structural validation, return the concept list."""
    if not CONCEPTS_JSON.exists():
        die(f"concepts.json not found at {CONCEPTS_JSON}")

    try:
        with CONCEPTS_JSON.open(encoding="utf-8") as fh:
            doc = json.load(fh)
    except json.JSONDecodeError as e:
        die(f"concepts.json is not valid JSON: {e}")

    if not isinstance(doc, dict):
        die("concepts.json root must be an object")
    if doc.get("schema_version") != 1:
        die(f"unsupported schema_version={doc.get('schema_version')!r}; expected 1")
    concepts = doc.get("concepts")
    if not isinstance(concepts, list):
        die("concepts.json: 'concepts' key must be a list")

    seen_ids: Dict[str, int] = {}
    for idx, c in enumerate(concepts):
        if not isinstance(c, dict):
            die(f"concept #{idx} is not an object")
        cid = c.get("id")
        if not isinstance(cid, str) or not cid:
            die(f"concept #{idx}: 'id' must be a non-empty string")
        if cid in seen_ids:
            die(f"duplicate concept id {cid!r} at #{idx} (first seen at #{seen_ids[cid]})")
        seen_ids[cid] = idx

        pos = c.get("pos", "Unknown")
        if pos not in VALID_POS:
            die(f"concept {cid!r}: invalid pos {pos!r}; expected one of {sorted(VALID_POS)}")

        lemmas = c.get("lemmas")
        if not isinstance(lemmas, dict):
            die(f"concept {cid!r}: 'lemmas' must be an object (got {type(lemmas).__name__})")
        for lang, values in lemmas.items():
            if lang not in SUPPORTED_LANGS:
                die(f"concept {cid!r}: unknown lang key {lang!r}; expected one of {SUPPORTED_LANGS}")
            if not isinstance(values, list):
                die(f"concept {cid!r}: lemmas[{lang!r}] must be a list")
            for v in values:
                if not isinstance(v, str):
                    die(f"concept {cid!r}: lemmas[{lang!r}] contains non-string {v!r}")
                if "\t" in v or "\n" in v:
                    die(f"concept {cid!r}: lemmas[{lang!r}] contains control char in {v!r}")

    return concepts


def dedup_preserving_order(items: List[str]) -> List[str]:
    """Drop duplicates after the first occurrence, preserving input order."""
    seen = set()
    out = []
    for x in items:
        if x in seen:
            continue
        seen.add(x)
        out.append(x)
    return out


def render_row(concept: Dict[str, Any]) -> str:
    """Emit a single TSV row for one concept. No trailing newline."""
    cid = concept["id"]
    pos = concept.get("pos", "Unknown")
    pos_col = "" if pos == "Unknown" else pos

    lemmas = concept["lemmas"]
    # Sort language keys alphabetically for determinism. Drop empty
    # lists — skipping empty cells keeps rows compact on narrow
    # concepts (e.g. if a language has no good translation yet, the
    # column is simply absent, not `lang:`).
    lang_cols: List[str] = []
    for lang in sorted(lemmas.keys()):
        values = dedup_preserving_order([v.strip() for v in lemmas[lang]])
        values = [v for v in values if v]  # drop empties
        if not values:
            continue
        lang_cols.append(f"{lang}:{','.join(values)}")

    return "\t".join([f"c:{cid}", pos_col, *lang_cols])


def render_tsv(concepts: List[Dict[str, Any]]) -> str:
    """Render the full TSV content (header + sorted rows)."""
    sorted_concepts = sorted(concepts, key=lambda c: c["id"])
    rows = [render_row(c) for c in sorted_concepts]
    return HEADER + "\n" + "\n".join(rows) + "\n"


def count_summary(concepts: List[Dict[str, Any]]) -> str:
    """Human-readable counts for --dry-run output."""
    total_lemmas = 0
    per_lang: Dict[str, int] = {lang: 0 for lang in SUPPORTED_LANGS}
    for c in concepts:
        for lang, values in c["lemmas"].items():
            dedup = dedup_preserving_order([v.strip() for v in values if v.strip()])
            per_lang[lang] += len(dedup)
            total_lemmas += len(dedup)

    lines = [
        f"  concepts: {len(concepts)}",
        f"  total lemma strings: {total_lemmas}",
        "  per-language lemma counts:",
    ]
    for lang in SUPPORTED_LANGS:
        cov = per_lang[lang]
        pct = 100.0 * cov / max(1, len(concepts))
        lines.append(f"    {lang}: {cov} ({pct:.0f}% coverage)")
    return "\n".join(lines)


# ─── Entry point ──────────────────────────────────────────────────────────────

def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.strip().splitlines()[0])
    parser.add_argument("--stdout", action="store_true",
                        help="print the TSV to stdout instead of writing to disk")
    parser.add_argument("--dry-run", action="store_true",
                        help="parse + count only; write nothing")
    args = parser.parse_args()

    concepts = load_concepts()

    if args.dry_run:
        print(count_summary(concepts))
        return 0

    tsv = render_tsv(concepts)

    if args.stdout:
        sys.stdout.write(tsv)
        return 0

    OUTPUT_TSV.parent.mkdir(parents=True, exist_ok=True)
    # Write with LF line endings and UTF-8 explicitly; Rust's include_str!
    # is byte-exact, and shipping CRLF would change the djb2 hash across
    # host OSes.
    with OUTPUT_TSV.open("w", encoding="utf-8", newline="\n") as fh:
        fh.write(tsv)

    print(f"wrote {OUTPUT_TSV.relative_to(REPO_ROOT)} ({len(tsv):,} bytes)")
    print(count_summary(concepts))
    return 0


if __name__ == "__main__":
    sys.exit(main())
