#!/usr/bin/env python3
"""
Constellation Lexicon — concepts/*.json → lexicon_v1.tsv emitter.

Reads every `NNN-theme.json` shard from `lab/m11-data/concepts/`, merges
them into a single concept list, and writes a deterministic TSV in the
format consumed by `src-tauri/src/lexicon/parse.rs::parse()`.

# Shard layout (M11-data v2)

Prior to v2 the corpus lived in a single `concepts.json` file. That
scales to ~2K concepts before the file becomes unwieldy for review
and editing. At the 20K-concept target the corpus is sharded by
theme, one file per theme, under `concepts/`:

    concepts/000-core-seed.json          # M11-data v1 foundation (49 concepts)
    concepts/001-body-and-family.json    # body parts, family, kinship
    concepts/002-nature.json             # animals, plants, weather, landscape
    concepts/003-food-and-household.json # food, drink, everyday objects
    concepts/004-qualities.json          # adjectives, colors, numbers
    concepts/005-basic-verbs.json        # core action verbs, emotions
    ...

Each shard is a self-contained `{"schema_version": 1, "concepts": [...]}`
document. The three-digit prefix provides stable lexicographic sort
order; the theme suffix is purely a human navigation aid.

Shards are flattened in filename sort order. Duplicate concept ids
ACROSS shards are a hard error — the build fails with a pointer to
both files. This is the cross-shard dedup invariant.

# Determinism rules (reproducible byte-identical output given same input)

  - Shard filenames read in sort order (so concept input order is stable).
  - Rows in the emitted TSV sorted by concept id, stably.
  - Language columns sorted alphabetically by lang code within each row.
  - Lemmas within a single (concept × language) cell: first-seen order
    preserved (preferred lemma first), duplicates dropped after the
    first occurrence.
  - Header comment block is a fixed literal.
  - No trailing whitespace; LF line endings regardless of host OS.

Exits non-zero with a descriptive stderr message if any shard is
malformed. validate.py does the deeper content checks; build.py is
only expected to catch structural issues (missing required fields,
unknown PoS, lemma value not a list, cross-shard id collisions).

Usage:
    python build.py                    # writes the TSV
    python build.py --stdout           # prints the TSV to stdout only
    python build.py --dry-run          # counts rows + lemmas, writes nothing
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any, Dict, List, Tuple

# ─── Constants ────────────────────────────────────────────────────────────────

REPO_ROOT = Path(__file__).resolve().parents[2]
CONCEPTS_DIR = Path(__file__).parent / "concepts"
OUTPUT_TSV = REPO_ROOT / "src-tauri" / "src" / "lexicon" / "data" / "lexicon_v1.tsv"

# ISO-639-1 codes that round-trip with arabic::Lang::code.
SUPPORTED_LANGS = ["ar", "de", "en", "es", "fa", "fr", "he", "hi",
                   "ja", "ko", "pt", "ru", "tr", "ur", "zh"]

# Valid arabic::PartOfSpeech variants. Empty string means Unknown
# (handled at parse time).
VALID_POS = {"Noun", "Verb", "Adjective", "Adverb",
             "ProperNoun", "Particle", "Foreign", "Unknown"}

# Fixed header block emitted on top of every regenerated TSV. Mirrors
# the seed_v1.tsv comment block so anyone opening either file in an
# editor finds the same conventions documented in place.
HEADER = """\
# Constellation Lexicon — production corpus v1 (M11-data).
#
# This file is GENERATED by lab/m11-data/build.py. Do not hand-edit —
# edit lab/m11-data/concepts.json and rerun build.py instead.
#
# Format per row (TAB-separated):
#
#   concept_id<TAB>pos<TAB>lang:lemma,lemma,...<TAB>lang:lemma,lemma,...<TAB>...
#
# See lab/m11-data/README.md for the full schema and the regeneration
# workflow. Every concept in this corpus is Constellation-original
# content — no third-party wordnet data is consumed. The file is
# redistributable under whatever license Constellation chooses, now
# and forever.
"""

# ─── Helpers ──────────────────────────────────────────────────────────────────

def die(msg: str, code: int = 1) -> None:
    print(f"build.py: error: {msg}", file=sys.stderr)
    sys.exit(code)


def load_shard(path: Path) -> List[Dict[str, Any]]:
    """Parse one `concepts/NNN-theme.json` shard, validate structurally,
    return the concept list. Does not check cross-shard id uniqueness —
    that happens in `load_all_shards`."""
    try:
        with path.open(encoding="utf-8") as fh:
            doc = json.load(fh)
    except json.JSONDecodeError as e:
        die(f"{path.name} is not valid JSON: {e}")

    if not isinstance(doc, dict):
        die(f"{path.name}: root must be an object")
    if doc.get("schema_version") != 1:
        die(f"{path.name}: unsupported schema_version={doc.get('schema_version')!r}; expected 1")
    concepts = doc.get("concepts")
    if not isinstance(concepts, list):
        die(f"{path.name}: 'concepts' key must be a list")

    seen_ids: Dict[str, int] = {}
    for idx, c in enumerate(concepts):
        if not isinstance(c, dict):
            die(f"{path.name}: concept #{idx} is not an object")
        cid = c.get("id")
        if not isinstance(cid, str) or not cid:
            die(f"{path.name}: concept #{idx}: 'id' must be a non-empty string")
        if cid in seen_ids:
            die(f"{path.name}: duplicate concept id {cid!r} at #{idx} "
                f"(first seen at #{seen_ids[cid]})")
        seen_ids[cid] = idx

        pos = c.get("pos", "Unknown")
        if pos not in VALID_POS:
            die(f"{path.name}: concept {cid!r}: invalid pos {pos!r}; "
                f"expected one of {sorted(VALID_POS)}")

        lemmas = c.get("lemmas")
        if not isinstance(lemmas, dict):
            die(f"{path.name}: concept {cid!r}: 'lemmas' must be an object "
                f"(got {type(lemmas).__name__})")
        for lang, values in lemmas.items():
            if lang not in SUPPORTED_LANGS:
                die(f"{path.name}: concept {cid!r}: unknown lang key {lang!r}; "
                    f"expected one of {SUPPORTED_LANGS}")
            if not isinstance(values, list):
                die(f"{path.name}: concept {cid!r}: lemmas[{lang!r}] must be a list")
            for v in values:
                if not isinstance(v, str):
                    die(f"{path.name}: concept {cid!r}: lemmas[{lang!r}] "
                        f"contains non-string {v!r}")
                if "\t" in v or "\n" in v:
                    die(f"{path.name}: concept {cid!r}: lemmas[{lang!r}] "
                        f"contains control char in {v!r}")

    return concepts


def load_all_shards() -> Tuple[List[Dict[str, Any]], List[Tuple[str, int]]]:
    """Walk `concepts/` in filename sort order, parse every `*.json` shard,
    merge into one concept list, cross-shard-dedup-check.

    Returns `(concepts, shard_counts)` where `shard_counts` is a list of
    `(shard_name, concept_count)` pairs in load order — useful for the
    dry-run summary.
    """
    if not CONCEPTS_DIR.is_dir():
        die(f"concepts/ directory not found at {CONCEPTS_DIR}")

    shard_paths = sorted(CONCEPTS_DIR.glob("*.json"))
    if not shard_paths:
        die(f"no *.json shards found in {CONCEPTS_DIR}")

    all_concepts: List[Dict[str, Any]] = []
    id_to_shard: Dict[str, str] = {}
    shard_counts: List[Tuple[str, int]] = []

    for path in shard_paths:
        concepts = load_shard(path)
        for c in concepts:
            cid = c["id"]
            if cid in id_to_shard:
                die(f"cross-shard duplicate concept id {cid!r}: appears in "
                    f"both {id_to_shard[cid]} and {path.name}")
            id_to_shard[cid] = path.name
        all_concepts.extend(concepts)
        shard_counts.append((path.name, len(concepts)))

    return all_concepts, shard_counts


def dedup_preserving_order(items: List[str]) -> List[str]:
    """Drop duplicates after the first occurrence, preserving input order."""
    seen = set()
    out = []
    for x in items:
        if x in seen:
            continue
        seen.add(x)
        out.append(x)
    return out


def render_row(concept: Dict[str, Any]) -> str:
    """Emit a single TSV row for one concept. No trailing newline."""
    cid = concept["id"]
    pos = concept.get("pos", "Unknown")
    pos_col = "" if pos == "Unknown" else pos

    lemmas = concept["lemmas"]
    # Sort language keys alphabetically for determinism. Drop empty
    # lists — skipping empty cells keeps rows compact on narrow
    # concepts (e.g. if a language has no good translation yet, the
    # column is simply absent, not `lang:`).
    lang_cols: List[str] = []
    for lang in sorted(lemmas.keys()):
        values = dedup_preserving_order([v.strip() for v in lemmas[lang]])
        values = [v for v in values if v]  # drop empties
        if not values:
            continue
        lang_cols.append(f"{lang}:{','.join(values)}")

    return "\t".join([f"c:{cid}", pos_col, *lang_cols])


def render_tsv(concepts: List[Dict[str, Any]]) -> str:
    """Render the full TSV content (header + sorted rows)."""
    sorted_concepts = sorted(concepts, key=lambda c: c["id"])
    rows = [render_row(c) for c in sorted_concepts]
    return HEADER + "\n" + "\n".join(rows) + "\n"


def count_summary(concepts: List[Dict[str, Any]],
                  shard_counts: List[Tuple[str, int]]) -> str:
    """Human-readable counts for --dry-run output."""
    total_lemmas = 0
    per_lang: Dict[str, int] = {lang: 0 for lang in SUPPORTED_LANGS}
    for c in concepts:
        for lang, values in c["lemmas"].items():
            dedup = dedup_preserving_order([v.strip() for v in values if v.strip()])
            per_lang[lang] += len(dedup)
            total_lemmas += len(dedup)

    lines = [
        f"  shards: {len(shard_counts)}",
    ]
    for name, n in shard_counts:
        lines.append(f"    {name}: {n}")
    lines.extend([
        f"  concepts: {len(concepts)}",
        f"  total lemma strings: {total_lemmas}",
        "  per-language lemma counts:",
    ])
    for lang in SUPPORTED_LANGS:
        cov = per_lang[lang]
        pct = 100.0 * cov / max(1, len(concepts))
        lines.append(f"    {lang}: {cov} ({pct:.0f}% coverage)")
    return "\n".join(lines)


# ─── Entry point ──────────────────────────────────────────────────────────────

def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.strip().splitlines()[0])
    parser.add_argument("--stdout", action="store_true",
                        help="print the TSV to stdout instead of writing to disk")
    parser.add_argument("--dry-run", action="store_true",
                        help="parse + count only; write nothing")
    args = parser.parse_args()

    concepts, shard_counts = load_all_shards()

    if args.dry_run:
        print(count_summary(concepts, shard_counts))
        return 0

    tsv = render_tsv(concepts)

    if args.stdout:
        sys.stdout.write(tsv)
        return 0

    OUTPUT_TSV.parent.mkdir(parents=True, exist_ok=True)
    # Write with LF line endings and UTF-8 explicitly; Rust's include_str!
    # is byte-exact, and shipping CRLF would change the djb2 hash across
    # host OSes.
    with OUTPUT_TSV.open("w", encoding="utf-8", newline="\n") as fh:
        fh.write(tsv)

    print(f"wrote {OUTPUT_TSV.relative_to(REPO_ROOT)} ({len(tsv):,} bytes)")
    print(count_summary(concepts, shard_counts))
    return 0


if __name__ == "__main__":
    sys.exit(main())
