//! Asset loader for `concept_vectors_v1.bin`.
//!
//! The asset is embedded in the binary via `include_bytes!` so it
//! travels with the executable — no runtime file lookup, no
//! per-machine cache, no platform path forks. The OS pages the
//! data section in lazily on demand.
//!
//! ## Why owned `Box<[f32]>` instead of `&'static [f32]` zero-copy?
//!
//! `include_bytes!` returns `&'static [u8]` aligned to 1 byte. The
//! `f32` matrix inside the file starts at a 4-byte-aligned offset
//! within the file, but the *runtime address* of those bytes depends
//! on where the linker placed `.rodata` — not guaranteed to be
//! `align_of::<f32>() == 4`-aligned. Reinterpreting via
//! `slice::from_raw_parts` is therefore UB on platforms with strict
//! alignment. Copying once at boot into a properly-aligned
//! `Box<[f32]>` is ~30 ms for the 30 MB matrix and removes the
//! footgun entirely.

use crate::bridge_vectors::{ASSET_MAGIC, VECTOR_DIM};

/// The baked asset, embedded at compile time. Generated by the
/// `build_concept_vectors` [[bin]]; see Architect v2 §3.3.
const ASSET_BYTES: &[u8] = include_bytes!("data/concept_vectors_v1.bin");

/// Decoded asset, ready to feed into `ConceptVectorStore::new`.
pub struct ParsedAsset {
    pub count: usize,
    pub dim: usize,
    pub concept_ids: Vec<String>,
    /// Owned, properly f32-aligned matrix. Row-major: row `r` lives
    /// at `matrix[r * dim .. (r+1) * dim]`. L2-normalized.
    pub matrix: Box<[f32]>,
}

/// Parse the baked asset. Cheap to call once at boot; cache the
/// result via the `bridge_vectors::get()` singleton.
pub fn parse() -> Result<ParsedAsset, String> {
    parse_bytes(ASSET_BYTES)
}

fn parse_bytes(bytes: &[u8]) -> Result<ParsedAsset, String> {
    const HEADER_LEN: usize = 8 + 4 + 4; // magic + count + dim
    if bytes.len() < HEADER_LEN {
        return Err(format!("asset too small: {} bytes", bytes.len()));
    }
    if &bytes[..8] != ASSET_MAGIC {
        return Err(format!(
            "bad asset magic: expected {ASSET_MAGIC:?}, got {:?}", &bytes[..8]
        ));
    }
    let count = u32::from_le_bytes([bytes[8], bytes[9], bytes[10], bytes[11]]) as usize;
    let dim = u32::from_le_bytes([bytes[12], bytes[13], bytes[14], bytes[15]]) as usize;
    if dim != VECTOR_DIM {
        return Err(format!(
            "unexpected dim {dim} (asset built for a different model? expected {VECTOR_DIM})"
        ));
    }

    // ── Concept-id table: u16 LE byte_len + UTF-8 bytes per row ──
    let mut concept_ids = Vec::with_capacity(count);
    let mut cursor = HEADER_LEN;
    for i in 0..count {
        if cursor + 2 > bytes.len() {
            return Err(format!("id table truncated at row {i}"));
        }
        let len = u16::from_le_bytes([bytes[cursor], bytes[cursor + 1]]) as usize;
        cursor += 2;
        if cursor + len > bytes.len() {
            return Err(format!("id string truncated at row {i} (len {len})"));
        }
        let id = std::str::from_utf8(&bytes[cursor..cursor + len])
            .map_err(|e| format!("invalid utf-8 in concept id at row {i}: {e}"))?
            .to_string();
        concept_ids.push(id);
        cursor += len;
    }

    // ── Skip alignment pad (writer pads to 4-byte boundary) ──
    let pad = (4 - (cursor % 4)) % 4;
    cursor += pad;

    // ── Vector matrix: count × dim × f32 LE, copied into Box<[f32]> ──
    let needed = count * dim * 4;
    if cursor + needed > bytes.len() {
        return Err(format!(
            "matrix truncated: cursor at {cursor}, need {needed} more bytes, have {} total",
            bytes.len()
        ));
    }
    let mut matrix: Vec<f32> = Vec::with_capacity(count * dim);
    let m_bytes = &bytes[cursor..cursor + needed];
    for chunk in m_bytes.chunks_exact(4) {
        matrix.push(f32::from_le_bytes([chunk[0], chunk[1], chunk[2], chunk[3]]));
    }
    debug_assert_eq!(matrix.len(), count * dim);

    Ok(ParsedAsset {
        count,
        dim,
        concept_ids,
        matrix: matrix.into_boxed_slice(),
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The committed asset must round-trip correctly. This catches
    /// (a) corruption of the .bin during checkin, (b) a magic-or-dim
    /// mismatch if the writer and parser drift apart, and (c) any
    /// length-arithmetic error in the table+matrix layout.
    #[test]
    fn baked_asset_parses() {
        let parsed = parse().expect("baked asset must parse");
        assert_eq!(parsed.dim, VECTOR_DIM);
        assert!(parsed.count > 0, "expected non-empty asset");
        assert_eq!(parsed.concept_ids.len(), parsed.count);
        assert_eq!(parsed.matrix.len(), parsed.count * parsed.dim);
        // Every concept id starts with the M11 namespace prefix.
        assert!(
            parsed.concept_ids.iter().all(|id| id.starts_with("c:")),
            "concept ids should be M11-namespaced (e.g. c:book)"
        );
        // Every row is L2-normalized within tolerance.
        for row in 0..parsed.count.min(50) {
            let off = row * parsed.dim;
            let norm: f32 = parsed.matrix[off..off + parsed.dim]
                .iter().map(|x| x * x).sum::<f32>().sqrt();
            assert!(
                (0.99..=1.01).contains(&norm),
                "row {row} ({}) has norm {norm:.4}", parsed.concept_ids[row]
            );
        }
    }
}
